### ISSUE TITLE
Reiterate on incident concept

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1033]
Incidents are currently not easy to use. The major pain point is that it is not easy to say what has to be done in order to resolve the incident. Things we could chanage:

* Do incidents need an event lifecycle?
* Do incidents need a separate identity (key)?

Ideas:

* Add a new record type `INCIDENT`
* When event processing fails, we create a new event that is an exact copy but has the type `INCIDENT`.
* Whenever we receive a command that updates this entity, we try to reprocess the incident event
* This needs some more thought, e.g. go through incident creation and resolution step by step assuming the users perspective

**Comment by ThorbenLindhauer** [comment]
Implementation detail: fixup TODO in `BpmnStepContext` (see https://github.com/zeebe-io/zeebe/pull/1189#discussion_r209963372)

**Comment by Zelldon** [comment]
## Outcome of the incident workshop:

### Definition of Incidents:

An Incident is workflow execution related and shows an problem/error, which can be resolved by user interaction. Resolving is possible via update retries or update payload, depending on which case of incident.

Incidents can happen on:
 * Mappings - resolvable by update payload
 * Expressions - resolvable by update payload
 * Failed Jobs - resolvable by update retries (and maybe update payload? the operator needs to decide)

An incident is not a technical unexpected exception of the broker, like NPE or out of memory error.

We defined a new shorter and simpler life cycle, which only contains two states.
Created and Deleted or Opened and Closed.

### Resolving

The incidents are no longer implicit resolved by updating retries or payload.
This means we will have an new command to resolve the incident.
This for example makes it possible to update the payload on different scopes or update the retries and payload, before trying to resolve the incident.

The resolve command will immediately resolve the current incident. The execution will try to restart. 
It can happen that the resolving didn't work, then a new incident will be created. This approach helps to reduce and simplify the incident life cycle.

### Further outcome and prerequisites

We decided to merge all stream processors together, this makes it easier to implement incidents and to share state. Furthermore as side effect it should have an performance improvement, since we only need to deserialize the logged events once instead of multiple times for each stream processor etc.

Jobs resolve there payload in the `ACTIVATED` state, this means they will get the updated payload of the task scope for example. No matter which payload concept we choose.
