### ISSUE TITLE
Make keys globally unique

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1037]
Currently, our keys are unique per partition (excluding workflow definitions, because those keys are generated on the system partition). Users (e.g. Operate team) that want to aggregate the records of multiple partitions must therefore always work with a composite identity of (partition id, key). 

We could make that simpler by encoding the partition id into the key (e.g. the first n bits of the key). We should check if the remaining key space is sufficient.

**Comment by Zelldon** [comment]
Let's assume we are using 2 bytes for the partition IDs (maybe to much) and the rest for the keys.

Then we have an `keyspace` of `2^(8*6) = 2^48 = 281474976710656`.
Each year has `31536000` seconds (if we are assume 365 days).
If we assume an system life time of about 25 years, then we have `788400000` seconds for the hole system life time.
Then we can calculate how many keys we can generate at maximum per second, to reach the system life time.

```
>>> maxKeysPerSecond = keySpace / systemLifetimeInSeconds
>>> print(maxKeysPerSecond)
357020.5184051953
```

If we expect only 10 years for example, then we could generate `892551.2960129883` keys at maximum per second. This is not an million but maybe enough?

Lets increase the `keyspace` and say you only can have 256 partitions, then the keyspace would be `2^54=72057594037927936`.
Which means we could generate `228493131.779325` keys at maximum per seconds, which is quite a lot.

Anyway I think out current dispatcher implementation will overflow before the keys are going out, since
the positions is only an `int`.
