### ISSUE TITLE
Broker should not deploy non-executable processes

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1146]
* transformer should ignore those
* follow-up from #1007

**Comment by Zelldon** [comment]
But deployment is created ? Or should it be rejected?

**Comment by ThorbenLindhauer** [comment]
A deployment with `n` executable and `m` non-executable processes should be treated the same as if it was a deployment with `n` executable and 0 non-executable processes. So to answer the question, I believe it should be rejected if there are no other executable processes. Haven't checkd the current behavior, though.

**Comment by saig0** [comment]
Current behavior: 
* if a BPMN contains multiple processes then non-executable processes are ignored and not deployed
* if a BPMN contains no executable process then the deployment is rejected because every BPMN needs at least one executable process 

I think this is the expected behavior. So, this issue can be closed.

**Comment by Zelldon** [comment]
Thanks @saig0
