### ISSUE TITLE
StateController.tryGet(keyBuffer, valueBuffer) indicates key not found for to small value buffer

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1216]
The method `tryGet(keyBuffer, valueBuffer)` checks the returned length of the rocks db `get` call against the length of the provided value buffer to determine if the key was found.

https://github.com/zeebe-io/zeebe/blob/c9af9a02f93fb61695c37215355d72c70e2bdcdf/logstreams/src/main/java/io/zeebe/logstreams/state/StateController.java#L255

This is not aligned with the java doc of the rocks db `get` method
> @return The size of the actual value that matches the specified {@code key} in byte.  If the return value is greater than the length of {@code value}, then it indicates that the size of the input buffer {@code value} is insufficient and partial result will be returned. RocksDB.NOT_FOUND will be returned if the value not found.

So if the constant `NOT_FOUND = -1` is returned the key does not exist. Otherwise if the sizes don't match either a to big or to small buffer was provided. We should then handle this with either returning a new buffer or throwing an exception.

The current implementation could let to situation where a key is not found anymore although it is present.

**Comment by menski** [comment]
@Zelldon any opinion on this?

**Comment by menski** [comment]
Based on this comment we probably should check for greater 0 instead of this `NOT_FOUND` constant.

https://github.com/facebook/rocksdb/blob/38ad3c9f8aa36bec451eb03f8271ad9e6dff54cf/java/src/main/java/org/rocksdb/RocksDB.java#L688-L689

**Comment by Zelldon** [comment]
Yes I stumbled as well about this `tryGet` implementation. 

I think it depends on the use case.
Because if you assume that your value is stored with this key and expected value length and then get returns an larger sizer then the expected value length tryGet would return false. Which is ok because I expected a different value length. I think this is only useful for values which are static in length, like some process ids or keys (long values). 

But if we use this with dynamic value lengths yes then it makes no sense.

Ah you found this comment already. I wanted to show this as well :D 
I had a look in the c++ code and it seems that `-2` can't be returned.
https://github.com/facebook/rocksdb/blob/master/java/rocksjni/rocksjni.cc#L661
Because this is the return value if an exeception appears, but then on Java level you don't get the return value.

**Comment by Zelldon** [comment]
Out dated
