### ISSUE TITLE
Should we define maximum length for some properties

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1333]
If we define for example a maximum length for message name and message correlation key, this would make it easier to handle them. Furthermore this would make it possible to pre-allocate the key buffer, then we have no need to use Expandable buffers.

Is this a big problem/constraint for the user to only have a message name of say 1024 bytes?

**Comment by npepinpe** [comment]
I think long-term this is a must, even if the limitations end up being arbitrary. I think @menski mentioned there is an implicit maximum length already due to our transport (or dispatcher? not sure), but we could further limit it.

Regarding message name, well, a unicode character takes up to 4 bytes (I think?), so 1024 bytes means a potentially string of max length 256. Seems reasonable. We could start with this and make it configurable eventually.

The biggest hurdles come with payloads and deployment resources, I think; I'm not sure what a good heuristic would be there.

**Comment by Zelldon** [comment]
> there is an implicit maximum length already due to our transport (or dispatcher? not sure), but we could further limit it.

Yes currently it is the dispatcher. 

I would like to have the fixed sizes, because it would make life much easier. I agree on making it configurable would be good. Databases have also this concept of defining the maximum length of data so I think it makes sense.

**Comment by menski** [comment]
I think with the introduction of expressions this is not that simple anymore to limit statically. We would have to come up with a general limitation strategy and how to enforce it without breaking workflows.
