### ISSUE TITLE
Provide an efficient index for expire task lock stream processor

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#161]
What we need is a data structure that
* map from task key to event position
* sort task keys by their expiration time
* is fast for insert and remove (most of the time)

The amount of index entries is limited by the fetch size of the open task subscriptions (i.e. the amount of locked tasks).

**Comment by ThorbenLindhauer** [comment]
Review hints:

* `CheckLockExpirationCmd`: 
  * Can use `expirationMap#iterator` instead of instantiating a new iterator
  * `while` loop: `toRemoveEntries.putLong` uses wrong index
  * `for` loop: `toRemoveEntries.getLong` uses wrong index
  * => write tests that catch this
  * zeroeing the `toRemoveEntries` buffer may not be required
* `LockExpirationTest#shouldExpireMultipleLockedTasksAtOnce`
  * Make assertions stronger, i.e. assert that the two most recent `LOCKED` and `LOCK_EXPIRED` events are for tasks 1 and 2
