### ISSUE TITLE
I can update payload with propagating semantics

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#1616]
The way how update payload work should be changed. Currently, the variables are set/updated only locally. Since the job payload is propagated by default, the variables should also be propagated by default to upper scopes.

AT:
* I can create new variables or update the value of existing variables
* the propagation starts at the given scope and set/update the variable in the scope where the variable is defined
* if the variable doesn't exist in a higher scope then the variable is created at the scope of the workflow instance

**Comment by saig0** [comment]
**Edit:** I changed the expected behavior in a way that the broker writes one event for each created/updated variable instead of one event per scope which contains all local variables regardless if updated or not.

**Comment by saig0** [comment]
Currently, we have the problem that we can't update the payload/variables for gateways or intermediate events (if there is not related incident). In the broker, we check if there is an element instance or failed token for the given key. Also, the variable propagation doesn't work because it creates no new scope in the variable state (only for element instances).

**Comment by saig0** [comment]
After introducing variable scopes with #1911, we should use the variable scope key instead of the element instance key for the update payload command. The element instance key doesn't need to belong to variable scope (e.g. for a gateway).

**Comment by npepinpe** [comment]
This is done in #1939; everything is now an element, therefore you can update the payload at any scope by using the correct element instance key. With #1911, incidents will carry the key of the variable scope to update, but since `UPDATE_PAYLOAD` is a `WorkflowInstanceRecord`, we will still use the `elementInstanceKey` to encode the information.
