### ISSUE TITLE
Provide transparent/unified single/batch log stream writer

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1645]
In many cases where we publish records to the log stream, it is up to the object performing the write to decide whether to use the batch or single writer API. This makes reusing a method which writes a single event to the stream difficult, since it must be used with the single stream writer, and similarly for situations where the batch writer API is used.

The goal here is that while there is obviously a point where we decide which writer should be used, it should be done higher up the chain; to that effect, we should provide a single unified interface, so that methods are more easily reused in different contexts.

blocks #1573

**Comment by Zelldon** [comment]
I need this as well for #1573, because I want to trigger the BpmStepHandlers inside the IncidentStreamProcessor, which means on the view of the IncidentStreamProcessor I need to write a batch of events where the StepHandlers assume that they only write a single event. If I use the current TypedStreamWriter they will overwrite each other before the flush.

**Comment by npepinpe** [comment]
This isn't a blocker for me, or urgent, but we can move it up to ready if it blocks you.

**Comment by Zelldon** [comment]
It blocks me.

Do you think it make sense to use batch writer everywhere, instead of using two different writer implementations? I would like to change this that way.

**Comment by npepinpe** [comment]
Using the batch writer incurs a performance impact when we only end up writing a single record, since we have to copy it to memory at least once beforehand, but I think we write more than one event in a lot of cases. I would think it in this case, it would be good to lose on the performance for developer productivity/simplification of the code, and we can later optimise it such that we keep the same interface everywhere, but only do the buffering of all events/commands in memory if we detect we have more than one record to write. 

So first step would be to come up and use the unified interface, backed by batch, and then I would optimize it in a second step so it can handle both cases.

**Comment by Zelldon** [comment]
Aggree :+1:

**Comment by Zelldon** [comment]
Discussed with @saig0 

Approach would be that implementation uses LogStreamBatchWriter and the batch writer checks on flush if only one event is added then it writes it directly via the valueWriter reference to the dispatcher (logic of the LogStreamWriterImpl) otherwise it uses the old batch write logic. On LogStreamBatchWriter#event done is implicit called which means on second event the events are added to the batch buffer.
