### ISSUE TITLE
Followup for #1375: non-strict mapping extraction 

### ISSUE THREAD

**Issue by iamtakingiteasy** [zeebe-io/zeebe#1753]
In #1375 the fix for empty source mapping were merged. However later, in `io.zeebe.broker.workflow.processor.flownode.IOMappingHelper` it was negated by always using strict version of mapping, which brings back the same issue.

I am not sure if strict mapping has any merit at all, to be honest. Interpreting missing values as null or default value for given type is a better option to throwing an exception in my perspective.

---
Edit:
On second thought, I think there are cases when this could be benificial, however not all of them such.

The main case where it is not is when you return your own gRPC structures as a result of service task, and their json is "omitempty", making every zero-value (0, "", false, nil, etc.) omited from serialization.

Anyway I think some discussion to be made how to best approach it. If simply go to replace strict with-non strict, all tests in `io.zeebe.broker.incident.MappingIncidentTest` will no longer have their way to fail mappings they are now, because their current supposedly failing mapping will become valid and functional. And I rather consult how to approach this test suit.

- Would IO-mapping parts of this tests still be relevant?
- Should we find another way to create incidents for this tests?
- Should we have a per-mapping option to choose what to do with missing sources?
- Maybe solve it via coalesce()-like operator (essentialy `$.missingValue || defaultValue` in js)?

**Comment by saig0** [comment]
Hi @iamtakingiteasy , 

thank you for raising this up. You're correct. Currently, the broker creates an incident if an input/output mapping can't be applied. 

We chose this way to indicate early that something is missing/wrong. Otherwise, each worker would need to handle it by itself. Also, a worker would not know if the value is `null` or the payload doesn't contain the key.

Does this make sense for you?

**Comment by iamtakingiteasy** [comment]
Yes, but currently process could in no way continue if key is missing. There should be an option to allow null substitute for missing keys.

**Comment by saig0** [comment]
In order to fix this kind of incident, you need to update the payload and resolve the incident (see https://stage.docs.zeebe.io/reference/incidents.html). After that, the workflow instance continues.

Thank you for your suggestion. I think it is not necessary because you don't need to specify any input mapping. In this case, you get the whole payload and can extract the values by your self.

Also, we plan to change how the payload is handled. For example, a worker should be able to request specific variables (i.e. top-level keys). In this case, it makes sense to return `null` if the variable is not available.

Does this fit to your use case? 
If not, please describe your use case so that we can find a propper solution.

**Comment by iamtakingiteasy** [comment]
Regarding incidents: i see no way to be notified of workflow instance state changes in API. Or even getting a list of active incidents, if to apply inefficient polling. So it is not clear where incident ID should be coming from. Seems like one would have to implement custom exporter for that.

Regarding actual issue: it is the same for output mappings too. And if you think about mapping whole $ there, it is in fact is no better than mapping null on $.missingField -- has exactly the same level of assertion.

So yes, i think we need after all a mechanism to explicitly tell when a mapping should be coalesced to null (or any other default value), rather than escalated to an incident. If syntax i proposed earlier is ok, i think i can start doing my PR on weekend.

**Comment by saig0** [comment]
I'm still not sure. I want to understand your use case a bit better. 

What kind of worker do you have? Is the worker only for one workflow or it is generic?
Why don't you have control over the input and output payload?

**Comment by iamtakingiteasy** [comment]
The worker is a generic multi-workflow go microservice having gRPC communicational interface with other microservices. In order to integrate it into zeebe, I think it would be best to re-use existing gRPC structures as there is already implementation using them, simply mapping incoming payload to a json-tagged structure and returning json-tagged structure as result. In most cases, bpm handler would like as pass-through, switching on a header and simply returning result of corresponding gRPC method called against input json.

The catch is, json-tagged structures generated by protoc for go are having `omitempty` too, meaning every zero-value (0, false, "", nil) would not be present in result of serialization.

To have control over it would mean making exact copy of the same output structures, but without `omitempty` tags, or writing own json serializer that would ignore such tags even if they are present.

Another solution could be indeed writing such custom json serializer and adding an option to zeebe go API, allowing to opt-in for ignoring `omitempty`. And probably, considering that being go-specific issue, it could be better dealt with go-specific solution, so instead of changing zeebe expression parser, maybe changing go API. That I can surely do too, if you think there is no use for coalesce-like functionality.

**Comment by iamtakingiteasy** [comment]
Just say which way you would like more: add short-circuited coalesce expressions for json-expression parser (`$.misingValue || $.probablyMissingValue || $.likelyExistingValue || "fallback-literal"`) or go api change, adding `PayloadFromObjectIgnoreOmitempty(interface{}) (DispatchCompleteJobCommand, error)` to `CompleteJobCommandStep2` interface.

**Comment by menski** [comment]
Hi @iamtakingiteasy,

we talked about this issue more internally and as far as we understand your problem is actually not that your payload does not contain the properties specified in the mapping, but that they get lost during serialization due to the `omitempty` attribute in the generated go proto stubs. 

Although adding the ability to specify default values in expressions also sounds to be useful addition, it would be a bigger topic as it also involves syntax decisions. And in your case would require you to duplicate the default values from the protocol structs to the mapping expressions, which doesn't sound like the right solution. 

To make progress in this issue and find a solution for your use case I would propose to add the ability to the go client to ignore `omitempty`. You could already do this as a workaround in your own code and use one of the string payload methods. Nevertheless we see this as a valuable addition to the go API. And in case you are interested we would love to accept a PR for this feature.

If you are okay with this decision, I would like to ask you one more thing: What should be the default behavior of the `PayloadFromObject` method. At the moment I would suggest that this method should ignore the `omitempty` attribute, as this leads to unexpected behavior/problems as we saw in this issue. Therefor I would add another method which actually opts in to respect `omitempty`. What do you think?

**Comment by iamtakingiteasy** [comment]
I think best to keep default method respecting `omitempty`, because most go developers would expect it to behave like standard json marshaller (they may actually leverage `omitempty` in own structures, this is wide practice) and better not to rise wtf/minute metric.

However acknowledging the problem for those cases when user have not much control over structures he using and not having an option to ignore `omitempty` in standard json marshaller, providing such marshaller in form of additional method from Zeebe API should be sufficient.

Because special case (in respect to majority of go cases) should not be assumed as default. Convenient way to handle it would be enough.

**Comment by iamtakingiteasy** [comment]
Unfortunately i seem to be unable to set assignee or reviewer for my PR.

**Comment by menski** [comment]
Sorry I forgot that this is not possible for you. I assigned myself. Thanks for that fast PR. :+1:
