### ISSUE TITLE
How to: Listen to the event of workflow instance completion

### ISSUE THREAD

**Issue by bhowmikdebarshi** [zeebe-io/zeebe#1797]
Hello

This is more of a "how to" question rather than an issue. 

We can start a workflow instance using following code : 

`WorkflowInstanceEvent event = workflowClient
                    .newCreateInstanceCommand()
                    .bpmnProcessId(bpmnProcessId)
                    .latestVersion()
                    .send()
                    .join()`

Now, is there a way to get notified when the workflow instance will be completed ? that is all the tasks of that workflow will be completed for this particular instance. 

I know I can configure an exporter and keep polling the workflow instance's state by its key. But I guess it will be a better option if I have someway to subscribe the WorkflowInstance's complete state. 

Is there any way to achieve the same ?

**Comment by npepinpe** [comment]
You're right that at the moment, the way to achieve this would be using an exporter, or some ugly modelling workarounds (e.g. have a task right before the finish and a worker to handle it).

What's the use case for this?

**Comment by bhowmikdebarshi** [comment]
Thanks for quick response : 

I have couple of use cases : 
1) I have list of items and I need to perform same processing for each item. Once the processing for all the items are completed, I need to trigger another task. 
I have one bpmn model for itemProcessor. For each item, I will start workflow instance using that bpmn model id. 
If we would have some sort of subscription mechanism, after starting each wf instance, I would subscribe its complete event and mark it as completed once notified. As sson as all events are marked to completed, I would trigger another task. 
I guess, best solution would be to have "Fork / Join Concurrency" workflow for this as described here - https://docs.zeebe.io/basics/workflows.html#fork--join-concurrency 
But I dont have any example for this thing. 

2) Second use case: I have a prcess which involves few long running tasks. So once all tasks in that workflow is completed successfully ( in other word, the workflow instance is completed) or failed, I would want to notify / callback to user.  If I would have some sort of subscription mechanism, I would trigger notify/callback to user as soon as I'm notified that task is completed. It seems right now I have two options - i) have this notifyService as the last task of the workflow or ii) keep polling to exporter for the wf instance and once done, trigger the notifyService.

**Comment by saig0** [comment]
@bhowmikdebarshi thank you for your input. Regarding your use cases

1) This would be a perfect match for a multi-instance call-activity. However, neither multi-instance nor call-activities are currently supported. But you could build something similar by yourself using message correlation:
![image](https://user-images.githubusercontent.com/4305769/50343663-19ba9600-0528-11e9-9a01-75bed1365296.png)

2) I would prefer the first option (the notify service) because Zeebe itself can make sure and track that the notify service is invoked. And the application doesn't need to be aware of the workflow itself.

BTW: there are two new comminity projects to export events to [Hazelcast](https://github.com/zeebe-io/zeebe-hazelcast-exporter) and [Kafka](https://github.com/zeebe-io/zb-kafka-exporter).

**Comment by Zelldon** [comment]
Due to lack of activity I will close this issue, do not hesitate do reopen it if you have further or remaining questions. You could also use the other community channels like the [forum](https://forum.zeebe.io/) or [slack](https://zeebe-slack-invite.herokuapp.com/) if you want to get in touch with us.
