### ISSUE TITLE
Proposal for a consistent error message format

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1813]
Currently we have a lot of errors messages, which are for example send to the client if a command is rejected or an exception is thrown. The message format highly dependents on the developer who was currently implementing.

Examples:

 * `"message with id '%s' is already published"`
 * `"Job is not currently activated"`

I would like to have more consistent errors message which follow the same pattern.
This could for example look like this `Expected to ... with ..., but ... .` .

Examples

 * `"Expected to find a workflow instance with key %d, but found a child element instance."`
 * `"Expected to resolve an incident with key %d, but no incident found."`

So on a error I would like to say what was the expected state and what was the current state, so it might be clearer why this error occurs. 

Maybe it makes sense to define more guidelines.

**Comment by npepinpe** [comment]
As part of #1853 I collected errors that the client will see (i.e. errors the broker sends back to the gateway): https://github.com/zeebe-io/zeebe/wiki/Gateway-to-Broker-error-list

The format above works really well for processor-level command rejections (e.g. job update retries fails because retries is -1), but I'm not sure it works for the rest (e.g. command could not be deserialized). Let's see...

``` 
PARTITION_NOT_FOUND: "Expected to execute command on partition <PARTITION ID> but partition was not found"
MESSAGE_NOT_SUPPORTED: "Expected to execute <ValueType#name()> command but it is not a supported command type."
INVALID_MESSAGE: "Expected to deserialize command for processing but an error occurred: <Throwable#getMessage()>"
INVALID_CLIENT_VERSION: "Expected client to have version <CLIENT VERSION> less than or equal to current protocol version <PROTOCOL VERSION>"
MESSAGE_NOT_SUPPORTED: "Expected to handle message <SBE TEMPLATE ID> but it is not a recognized message."
```

Hm, it works, but it feels contrived for some (e.g. MESSAGE_NOT_SUPPORTED). How about for command errors, `Failed to <ACTION> command: <ERROR MESSAGE>`, for example:

`Failed to execute command: expected to execute on <PARTITION ID> but partition was not found`
`Failed to execute command: <ValueType#name()> is not a supported command type.`
`Failed to deserialize command: <Throwable#getMessage()>`
`Failed to execute command, client protocol version <CLIENT VERSION> is newer than server protocol version <PROTOCOL VERSION>`

Actually, only marginally better. But they are sort of similar, `Expected <PRECONDITION> but <REASON>` and `Failed to <ACTION> : <REASON>`

So how about `Expected ... but ...` for precondition failures, and `Failed to ... : ...` for execution failures?

**Comment by npepinpe** [comment]
Some ideas: https://github.com/zeebe-io/zeebe/wiki/Error-Guidelines

**Comment by Zelldon** [comment]
I think the best solution would be if we have only one pattern, because then no confusion will exist which one have to be used in which case. But I think it is also a good step forward to have two patterns, much better then the current situation.

I assume all can be covered with `Expected [EXPECTED], but got [ACTUAL] in [CONTEXT]` , because  you always expect an certain state or value. But maybe we can also agree on the `Failed to ...` pattern.

Cool that you collect all these errors :+1: I like also the guide lines wiki page :)

**Comment by npepinpe** [comment]
If everyone's satisfied with https://github.com/zeebe-io/zeebe/wiki/Error-Guidelines then I would close this issue.

**Comment by Zelldon** [comment]
I think this is done with https://github.com/zeebe-io/zeebe/pull/1869
