### ISSUE TITLE
I can deploy multiple resources at once

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#183]
AT:
* a client can add more than one resource to the deployment
* all resources in the deployment are deployed in the broker

**Comment by saig0** [comment]
**Protocol Change:**
* DEPLOYMENT_EVENT: remove properties "resource" and "resourceType"
* DEPLOYMENT_EVENT: add property "resources" which is a list of resources. A resource has the properties "resource", "resourceType" and "resourceName".

**Comment by Zelldon** [comment]
# Review

 ## Code

  ### ArrayValue

  * remove method `markAsModified`

  ### DeploymentCreateProcessor.java

   * add test for deployment with more resources and a workflow definition with more processes (combination of both)
   * What happens if the a duplicate is in the deployment? See https://github.com/zeebe-io/zeebe/issues/546
