### ISSUE TITLE
is there any possible to implements special handler in client for processing broker events?

### ISSUE THREAD

**Issue by aximo** [zeebe-io/zeebe#1880]
i know we should implement exporter and deploy it to broker, but why we don't provider a way to process broker events in client, i think the basic ability for that is ready in zeebe as the process is very similar for job handling.

if that is possible, zeebe broke become more purely and flexable.

just a suggestion~

**Comment by npepinpe** [comment]
Hi aximo, thanks for your suggestion and interest in Zeebe. We have discussed this in the past, but did not come up with interesting use cases where an exporter would not be a better fit.

We're always open to revise our decisions if new interesting use cases arise.

**Comment by Zelldon** [comment]
Due to lack of activity I will close this issue, do not hesitate do reopen it if you have further or remaining questions. You could also use the other community channels like the [forum](https://forum.zeebe.io/) or [slack](https://zeebe-slack-invite.herokuapp.com/) if you want to get in touch with us.
