### ISSUE TITLE
The job payload is set only on activation

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#1885]
Currently, the job payload is set on creation but also on activation. Since the payload is always calculated on activation based on the current workflow instance variables and the requested variables by the worker, it is not necessary to set the payload on creation.

AT:
* the job payload is only set on activation

**Comment by menski** [comment]
Current challenge is to refactor the batch job activation, as we know have to collect the payload before deciding if a job can be added to the job batch, because of the limited record size. But as the job activation is already a prefix iteration over the job state, collecting of the payload does not work as it would require another prefix iteration which is not supported by our RocksDB abstraction at the moment.
