### ISSUE TITLE
Remove key field from DeployWorkflowResponse gRPC message

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#1905]
We return the deployment event key as part of a `DeployWorkflow` call response, which for client users isn't useful at all. I think the consensus was that it's there for testing purposes, but we can grab the key from the `RecordingExporter` anyway, and removing "useless" (insofar as users are concerned) fields means less noise for users.

**Comment by menski** [comment]
The deployment key is the identifier of the deployment and can be used by the user to track the state of the deployment using the exported event stream. In case we would ever implement delete deployment, it would also be used to specify the deployment to delete.

I think it is a common practice to return the unique identifier of a resource the user created in the system, in this case the deployment. So personally I don't see a reason to remove it.

**Comment by menski** [comment]
> And deleting deployments seem strange to me

Our experience is that this is a highly requested feature, for example to tidy your environment. It also prevents you from starting new instances of out-dated definitions. And deleting whole deployments makes sense as you otherwise would have to keep track of the different resources inside a deployment yourself, if we assume that the resources in a deployment have a relationship.

 > I think futureproofing is risky, since you can't easily remove fields, so it's better to have less and add

In general I agree with this, but removing the unique identifier of a deployment seems unlikely to me.

**Comment by npepinpe** [comment]
> if we assume that the resources in a deployment have a relationship

:see_no_evil: 

But I get the point, status quo is fine by me.
