### ISSUE TITLE
A workflow instance can pass a data-based exclusive gateway

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#195]
AT:
* when a sequence flow is taken and the outgoing sequence flow is an exclusive gateway then the gateway is activated
* write an event with type 'ACTIVITY_ACTIVATED' 
* when the gateway is activated then it evaluates the conditions on the outgoing sequence flows and take the first one where the condition is satisfied 
* if no condition is satisfied then the (only) default sequence flow is taken
* a condition must be based on the workflow instance payload and is specified as JSON-Msg Pack path
* the gateway is immediately completed (i.e. pass-throw semantic)

**Comment by ThorbenLindhauer** [comment]
Review:

* YAML workflows
  * make use and absence of `next` attribute more consistent, i.e. whenever `next` is present, it links to the specified task; whenever `next` is not present, it links to the next task in sequence
  * terminology: use `goto` and `switch` instead of `next` and `flows`
* Spec compliance: Gateways should not have the full activity instance lifecycle. For now, let's go with a very simple approach, i.e. a single event `GATEWAY_ACTIVATED`.
