### ISSUE TITLE
List of all registered tasks

### ISSUE THREAD

**Issue by bhowmikdebarshi** [zeebe-io/zeebe#1951]
Hi

Is there any way to list all the avaiable tasks which have been registered in zeebe ? While modeling the workflow, user would need to know what are different tasks (microservices) avaiable and can use them in his/her workflow. 

Thanks

**Comment by Zelldon** [comment]
Due to lack of activity I will close this issue, do not hesitate do reopen it if you have further or remaining questions. You could also use the other community channels like the [forum](https://forum.zeebe.io/) or [slack](https://zeebe-slack-invite.herokuapp.com/) if you want to get in touch with us.
