### ISSUE TITLE
Decouple workflow processing from stream processing

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1980]
Decouple the workflow state machine from stream processing and state, i.e. which events to publish and state modifications. The engine should care about the logical transitions but the abstraction takes care of the resulting event stream etc.

**Comment by menski** [comment]
A first step/iteration could be to abstract the transition rules between states, at the moment it is kind of hidden in the `handleState` method or return type.

**Comment by Zelldon** [comment]
For me it is not really clear how this would look like? Or what do you want to achieve?

Do you want an interface like:

 ```java
public interface Engine {
  public void startEventOccured();
  public void sequenceFlowTakeTo(Element target);
 // ... etc.
}
```
And the implementation does state handling etc? 
And the stream processor will call the corresponding method regarding to the event?

**Comment by npepinpe** [comment]
I think this is still something we would ultimately want - but I don't see us tackling this in a long time, and as such it's unclear what a solution would look like. I would propose to close this and open a new issue when we have some idea of what it is exactly we want to achieve. Feel free to reopen if you feel otherwise.
