### ISSUE TITLE
Replace zb-raft leader election with atomix leader election for stream processor management

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#1996]
Goal decouple stream processing from replication. At the moment stream processors use the raft replication also as leader election for starting and stopping of processing events. We should decouple this as the stream processors can run on every node which has the log locally. This is the first step needed to replace raft replication with atomix.

**Comment by deepthidevaki** [comment]
It is not easy to use Atomix leader election together with zeebe-raft replication as we initialy thought. The main reason is that if Atomix leader is different from Raft leader, the stream processors running on the Atomix leader will write to the local logstream, but will never get replicated because replication is initiated by the raft leader. 
 - One option is instead of writing locally, the stream processor log-appender sends the event to the raft-replica leader. But the logstreamwriters that are running on the streamprocessor uses some information from Raft such as the current term. I think, it will be more work to decouple it and make it work correctly (in case of failures for example).
- Other option is to force Atomix to chose the Raft-leader in the leader-election. It is possible to promote a node as a leader. And it kind of works. But the implementation is a bit hacky and it doesn't help to really isolate our raft from the streamprocessor to  incrementally remove the dependency to our raft.

I think it is better to first replace raft-replication with a new atomix primitive for the logstream. As we did in this [spike branch](https://github.com/zeebe-io/zeebe/commits/spike-integrate-log-primitive) it is possible to use our raft for leader election to start and stop stream-processors, while using the distributed-log primitive for replication.
