### ISSUE TITLE
Do not write job activated record

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2182]
At the moment when a job is activated two records are written, one for `ValueType.JOB + JobIntent.ACTIVATED` and one for `ValueType.JOB_BATCH + JobBatchIntent.ACTIVATED` which contains the job record in a list of activated jobs. The hypothesis is that the job record is not needed anymore. Validate if this is needed for recovery or anything else in the job state. Validate if this record is consumed by operate.

**Comment by npepinpe** [comment]
We should notify Operate of our changes but it's not a problem.

**Comment by Zelldon** [comment]
I assume we can delete the Job.Activate and Activated and also the corresponding JobBatch records, they bring no real value for us. Even on reprocessing it is most likely that the job will be timed out afterwards.
The activation is also no real lock, which means the client can also complete it without having it activated.

**Comment by npepinpe** [comment]
We still write the Job.ACTIVATED record - I don't think this is necessary any more, but it may be a breaking change to remove it. I'm not sure how to best go about deprecating a protocol value - how to ensure users are made aware that this is going to be deprecated? Is it enough to just write it in the changelog?

Re your comment @Zelldon, I'm not sure about this - we never process or reprocess Job.ACTIVATED, so why would it be useful for us? I think it's really only used in our tests, which shouldn't be a reason for us to not do this. Maybe @saig0 you have more insight?

**Comment by Zelldon** [comment]
@npepinpe I think you misinterpreted my comment. My suggestion was to remove all these activation records completely :sweat_smile:

**Comment by npepinpe** [comment]
What would be the alternative here? Instead of the dispatcher writing it to the log, it hands it directly to the stream processor? That means we would need some form of back pressure there as well.

In order to reprioritize, I'd need to know:

1. What are the problems that this would solve?
1. What are the problems that this would solve?
1. What are the potential negative impacts (e.g. bypassing the replication/log to be executed directly by the stream proc)?

**Comment by npepinpe** [comment]
I think this will be removed in the new engine proposal? @korthout or @saig0 can you confirm?

**Comment by Zelldon** [comment]
I started some weeks ago on a branch https://github.com/zeebe-io/zeebe/tree/zell-no-job-activation I just need to fix some tests. I want to finish this in this year.

**Comment by saig0** [comment]
Currently, we didn't mention the job activation explicitly in the ZEP. It is not the primary focus. 

@Zelldon awesome :tada: But we should think about when we merge the PR. This will change the reprocessing behavior of the engine. It will be discovered by the reprocessing issue detection. So, we will need the update procedure.

**Comment by npepinpe** [comment]
The hope is that we have this automated this quarter, so we could release these kind of things with 0.26 - but hard to say, we only have 2 weeks left.

**Comment by TangJiong** [comment]
Since now, there is no ValueType.JOB + JobIntent.ACTIVATED event. The exporter can't guarantee the order of JobIntent.ACTIVATED and  JobIntent.COMPLETED as they belong to different topic. This brings some chaos to our auit program.

I wonder why Zeebe remove ValueType.JOB + JobIntent.ACTIVATED event？And is there any alternative to guarantee the order of the event of a job lifecycle?

**Comment by npepinpe** [comment]
Hi @TangJiong , you should have the same information in JobBatch.ACTIVATED. would that solve your issue? It's a bit more effort to unpack the data, I imagine, but otherwise for us it was writing/exporting a lot of redundant information.

**Comment by TangJiong** [comment]
@npepinpe Thanks for reply. Yes,  I cant have the same information in `JobBatch.ACTIVATED`. But I can't guarantee the order of `JobBatch.ACTIVATED` and `Job.COMPLETED`. `Job.COMPLETED` may reach before `JobBatch.ACTIVATED` as they belong to different topic. Our audit logic may consider a COMPLETED job still running.
