### ISSUE TITLE
Elasticsearch index for exporter that enables more Kibana reporting

### ISSUE THREAD

**Issue by wints** [zeebe-io/zeebe#2196]
In its current state, the Elasticsearch index for the exporter doesn't allow for certain types of Kibana reports that could be interesting for users, including:

• Avg. workflow instance duration
• Avg. job duration for each job type
• List of running workflow instances only
• List of messages that were published but not yet correlated to a workflow instance

The root issue is that carrying out a cross-document "join" in Kibana isn't possible. This issue could potentially be solved by a different approach to indexing--for example, if each workflow instance was stored in a single document.

Adding @menski for feedback.

**Comment by menski** [comment]
Brain dump:
- optional metrics index per value type workflow instance, job, message which already aggregates the interesting metrics and not more, i.e.
  - for every workflow instance: key, workflow key, bpmn process id, version, start time, end time
  - for every job: key, type, workflow instance key, workflow key, bpmn process id, version, start time, end time
  - for every message: key, name, correlation key, published, deleted, (correlation count?)

**Comment by npepinpe** [comment]
By metrics you mean prometheus metrics?

**Comment by menski** [comment]
By metrics we man business metrics, like workflow instance/job duration by workflow etc

**Comment by npepinpe** [comment]
I don't foresee this happening - however, we have had success implementing a metrics exporter, which is typically what I'd propose to users for now - that is, create your own exporter (or extend an existing one) and perform the aggregation there. The other option is to have an aggregation process, which is what Operate does. Furthermore, changing how we index things in Elastic would break compatibility. For now I am closing this, feel free to reopen @menski if you feel otherwise.
