### ISSUE TITLE
Blacklist workflow instance if element instance missing when processing an ELEMENT_* event

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2216]
Currently we simply ignore the event if the element instance is missing, but this is effectively a symptom of a bug, so we should log it and blacklist the instance.

**Comment by Zelldon** [comment]
Since we have the Blacklisting and atomicity we can now make use of exceptions, so for example we could throw IllegalStateException

**Comment by Zelldon** [comment]
One question on this:

Currently we check for the existence of the element instance and ignore it if it not exists.
This is necessary since we want to make sure that it is possible that an cancel can be in between.


For example the following sequence of events could happen:

ELEMENT_ACTIVATE, CANCEL, ELEMENT_ACTIVATED, ELEMENT_TERMINATING, ELEMENT_COMPLETING, ELEMENT_TERMINATED.

I think on terminating the instance is deleted right? If you then process completing it will be gone if you now ignore the instance terminated will not be processed.

**Comment by npepinpe** [comment]
The instance is removed at terminated, so in this case it would still exist, but there are valid cases where we want to skip processing an event anyway. For example, we wouldn't process COMPLETING in your example (e.g. maybe apply output mappings?) if we just processed TERMINATING.

I think the latest state is we always have an element instance until one of the terminal states is reached. The question is then, is it possible to have a sequence where we process, say, `TERMINATED` or `COMPLETED`, and then later `COMPLETING` or `TERMINATING` or something else? Maybe `EVENT_OCCURRED`? I don't think so, so I assume we should always have an instance, but I could be wrong.

**Comment by Zelldon** [comment]
Ah ok thanks.

So in the following scenarion:

ELEMENT_COMPLETING, CANCEL, ELEMENT_COMPLETED, ELEMENT_TERMINATING

we have in ELEMENT_TERMINATING no element instance,

**Comment by npepinpe** [comment]
The only case where I can imagine writing `ELEMENT_TERMINATING` after `CANCEL` is if we're talking about the `PROCESS` element here...in which case after processing its `COMPLETING` event, it would be already in `COMPLETED` state, so the `CANCEL` command would be ignored :sweat_smile:

**Comment by Zelldon** [comment]
I think I'm not totally aware of what is happening on which point, in the processing phases, but anyway I think there exist cases on which the element instance is already deleted because of a cancellation. In that case you can't determine if this was due canceling or it is simply a state inconsistency.

**Comment by npepinpe** [comment]
Let's discuss this f2f, because I also think so but I can't come up with those cases atm :sweat_smile:

**Comment by menski** [comment]
There are valid scenarios where there is no element instance available so we should not generally black list this. Maybe in the future we can distinguish cases where we always expect and element
