### ISSUE TITLE
Recoverable exceptions in event processor as missed by exception handling

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#2251]
Recoverable exceptions thrown in `EventProcessor#processEvent`, will be missed as they are wrapped inside another RuntimeException inside the Zeebe transaction:
https://github.com/zeebe-io/zeebe/blob/26f597a057edd21b26272d99dae879350227e3d7/zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransaction.java#L76-L83

We are missing this as two tests actually mock that a exception is throw in `zeeeDb.transaction()`, which will never happen, instead of the actual code path `EventProcessor#processEvent` where the exception is most likely be thrown.

https://github.com/zeebe-io/zeebe/blob/26f597a057edd21b26272d99dae879350227e3d7/logstreams/src/test/java/io/zeebe/logstreams/processor/StreamProcessorReprocessingTest.java#L233-L264

https://github.com/zeebe-io/zeebe/blob/26f597a057edd21b26272d99dae879350227e3d7/logstreams/src/test/java/io/zeebe/logstreams/processor/StreamProcessorReprocessingTest.java#L233-L264

**Comment by Zelldon** [comment]
I thought about this. Yes it is true that `zeebeDb#transaction()` will not throw this exception, but `transaction#run`, which was in the same block . It was easier to test, but I will adjust the test that the exception is thrown at `transaction#run`. Most of the tests in logstreams are using mocks because they should depend on the API, not on the implementation. It is also hard to simulate these kind of unexpected exceptions without mocking.

So I think it is more problematic that there was not test in the ZeebeDB module for this and maybe an integration test. I will fix this in the ZeebeDb and add an corresponding test.
