### ISSUE TITLE
Investigate how to create snapshots asynchronously

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#2292]

**Comment by saig0** [comment]
We want to create snapshots asynchronously in order to not interrupting workflow processing.

Find out how to:
* get the position when the snapshot is valid
* get the position where to start re-processing when recovering from the snapshot
* write the metadata for the snapshot
* do the same thing at the followers (here we don't write records)

**Comment by Zelldon** [comment]
## Current Idea

### Setup:

Snapshots are taken from a independent actor. Actor is scheduled at a fixed rate. Last successful processed and written positions are updated by the ProcessingStateMachine directly after transaction commit. This means if we see an new position there is already a state change, this is not interferable. Actor registered callback for commit changes.

### Process:

 * get async last successful processed position `X` from ProcessingStateMachine 
* start taking snapshot and write into directory related to this position (folder contains this name)
* get async last sucessful processed position `Y` 
* get async last written position `Z`
* wait until `Z` is committed
* rename snapshot folder to contain `Y-Z-term` , only validated folders will have this format
* ensure only at max. 3 snapshots exist

**Comment by Zelldon** [comment]
Did an experiment with RocksDB checkpoints ( https://gist.github.com/Zelldon/4803e6e5def37b222bae18e3700db85e). It seems that it is not 100% guaranteed how much of the changed data will end in the checkpoint. This conflicts with the current idea/approach. Because if we for example start at `X` it could happen that we already applied some of the later events to the state.

### Alternative Idea

 We have a separate column family, which contains the last successful processed position.
 These position is only updated after the processing is successfully done.
 We will use this position on reprocessing and start at the stored position.  If we had already processed an event later and changed the state the position had to be updated as well, since we use transactions.

 We will still use the `lastWrittenEventPositions` to validate our snapshot, we assume that we will have only one concurrent snapshot that is why we will use a temp directory for this. If the position is committed we will rename the snapshot directory.
