### ISSUE TITLE
Invest how to delete snapshots and free the memory

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#2296]
We want to delete old snapshot in order to free same space.

Find out how to:
* delete all files of a snapshot
* configure RocksDB to delete data which belongs to the snapshot (e.g. setting a memory limit to trigger compaction)

**Comment by MiguelPires** [comment]
There seem to be several ways to limit data usage with RocksDb:

* We can manually trigger a compaction after deleting snapshots ([source](https://github.com/facebook/rocksdb/wiki/Manual-Compaction)). However, CompactFiles doesn't seem to be available in RocksJava, only CompactRange.  We could get around this by changing the compaction priority option to an option that gives higher priority to older files (there seem to be two options that do something similar to this) ([source](https://rocksdb.org/blog/2016/01/29/compaction_pri.html)). CompactionFilters might be useful as well ([source](https://github.com/facebook/rocksdb/wiki/Compaction-Filter))
* We can set a used memory limit in the Db ([source](https://github.com/facebook/rocksdb/wiki/Managing-Disk-Space-Utilization#limiting-the-db-size)). This would require us to write an EventListener that looks for the background error and deal with it by manually compacting. However, I couldn't find eventListeners in RocksJava. EDIT: the API doesn't support it ([source](https://github.com/facebook/rocksdb/issues/1282))
* The ideal approach would be to define a limit that, when exceeded, triggers a compaction. It's possible to define either a limit to the number of SST files or to the total bytes in L0. It's also possible to limit the number of levels and the multiplier applied to determine the size of the subsequent levels. However, this means that this limit only works for a column family. Since Zeebe has about 40 of them and they're used in a very heterogeneous way, this limit isn't very useful. ([source](https://github.com/facebook/rocksdb/wiki/Compaction#options))
* Another interesting approach would be defining a TTL ([source](https://github.com/facebook/rocksdb/wiki/Leveled-Compaction#ttl)) which causes data older than that TTL to be deleted when there is no other background work (which I think only includes flushes and compactions). Unfortunately, this setting doesn't seem to be in RocksJava ([source](https://github.com/facebook/rocksdb/issues/774)) other than in the form of TtlDb ([source](https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/TtlDB.java))

For future reference, the best generic resources that I found on compaction are [this](https://github.com/facebook/rocksdb/wiki/Leveled-Compaction) and [this](https://github.com/facebook/rocksdb/wiki/Compaction).
