### ISSUE TITLE
Distribute zbctl via homebrew

### ISSUE THREAD

**Issue by TimPietrusky** [zeebe-io/zeebe#2314]
Instead of installing the `zbctl` manually, it would be really nice to have a formula for homebrew so it can be installed easily for Mac-Users.

**Comment by menski** [comment]
Sounds like a good idea. We don't have any experience with MacOS or Homebrew in the team. Could explain to me what would be required for this, or are you interested to contribute this to the project?

**Comment by kevingimbel** [comment]
Hello @menski I can help with this and contribute the changes if you want me to. 

Brew works with so called "taps" which are GitHub repositories containing "Formula" files - these formulas describe how a program is installed and what dependencies it needs (if any). As an example, here's a tap I use to make my Go CLI tools easily install-able for MacOS. https://github.com/kevingimbel/homebrew-tap

Each CLI tool has its own Formula which is a Ruby file, see https://github.com/kevingimbel/homebrew-tap/blob/master/license.rb

The Formula file could be generated in the build.sh (https://github.com/zeebe-io/zeebe/blob/develop/clients/zbctl/build.sh) and then pushed to the Repo, however there's a better solution.

Zeebe can use [Goreleaser](https://github.com/goreleaser/goreleaser). Goreleaser can build all the binaries for each of the systems you support (replacing build.sh) and create the files needed for package managers such as Brew (MacOS, Linux), Snapcraft (Ubuntu, etc.), and Scoop (Windows). The brew formula would then live in a repo, e.g. `github.com/zeebe-io/homebrew-tap`.

Users can then install and update `zbctl` with the following commands:

```sh
$ brew tap zeebe-io/tap
$ brew install zbctl
```

Whenever you release a new version with Goreleaser the homebrew tap (or scoop, snapcrat, chocolatey) repos are updated, too.

Supported Package Managers:
- Windows:
  - Chocolatey https://chocolatey.org/
  - Scoop https://scoop.sh/
- MacOS:
  - brew https://brew.sh/
- Linux:
  - brew https://linuxbrew.sh
  - snap* https://snapcraft.io

*snap can be used on the following Linux distributions:

    Arch Linux
    CentOS
    Debian
    Deepin
    Elementary OS
    Fedora
    GalliumOS
    KDE Neon
    Kubuntu
    Linux Mint
    Lubuntu
    Manjaro Linux
    openSUSE
    Parrot Security OS
    Raspbian
    Solus
    Ubuntu
    Xubuntu
    Zorin OS

--- 

So as you can see, adopting brew (and Goreleaser) will make releasing binaries for `zbctl` a lot easier and almost fully automated! I'm not entirely sure how it fits in with your existing release cycles and repo structure because it is a bit weird that `zbctl` is within this main repo but I'd be happy to assist you in either integration goreleaser into this repo or extracting `zbctl` into its own repo and setting the whole build up.

**Comment by salincandela** [comment]
👍

**Comment by npepinpe** [comment]
Goreleaser looks like a more interesting solution here.

**Comment by kevingimbel** [comment]
@npepinpe Agree, Goreleaser is an amazing tool and it really "just works". If you need any help let me know!

**Comment by npepinpe** [comment]
Closing for now - I'd happily welcome a community contribution, but we won't be working on anything like this. Note that zbctl is already distributed via npm.

**Comment by aivinog1** [comment]
Just a little announcement: right now zbctl is available in Homebrew: https://formulae.brew.sh/formula/zbctl#default 🎉
