### ISSUE TITLE
Investigate how to replicate snapshots with Atomix

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#2318]

**Comment by saig0** [comment]
We need to replicate the snapshots from RocksDB. One option could be to replicate them with Atomix. 

Questions to answer:
* Can we use one of the primitives (distributed value, distributed map, ...)?
* Are there any limitations of the size?
* How does it perform?

**Comment by Zelldon** [comment]
### One idea:
We could use an primitive to replicate the snapshots. 

 * As initial phase we put the file count in a primitive - followers know how many files they have to expect 
 * put all snapshot files in a primitive (one by one or maybe in batches)

There are various possible ways do this. We could use a AtomicValue, a DistributedQueue or DistributedMap. If we use one of the first primitives we have to encode the filenames somehow. If we use the DistributedMap we can put the filename as key, so no need for extra encoding.

We have to make sure that the snapshot is replicated only to the same partition. We can archive this by creating for each partition a primitive with unique name, for example use the partition id in the name. We should use the same MultiRaftPartitionGroup.

If we use the DistributedMap, then we would put as key the filename and as value the content of the file.
To make sure that we don't exceed the size of the primitive we only put one or up to 10 entries at a time (depending on the file size - normally it seems that RocksDB `*.sst` files around 65 MB). After putting these entries we wait on the last `put` operation, which means this value is committed in a quorum. After that we can simply remove it again. The followers listen to the primitive events and will get an `ADD` and `REMOVE` event. They can simply react only on the `ADD` event. 

The reason that we can't add all file contents as once is that the primitives state per partition should not exceed `2G` (or probably not `1G`). See extract of an atomix slack conversation:


```
kuujo [11:07 PM]
[...]. Basically, all the snapshots are stored in a single file. So a snapshot file will have a snapshot for primitive A, then primitive B, etc. 

[...]

// some guy gets a OOM exception
kuujo [6:46 PM]
Yeah... it seems like the only place that could conceivably happen is when taking snapshots of a very large set of state machines. The underlying array is dynamically resized, and if the bytes reach 1G + 1 I suspect it will be resized to `Integer.MAX_VALUE`
```

### Alternative 

 We could use direct messaging or Publish-Subscribe, but then we have to take care that the replication works as expected and everything was replicated successfully.

**Comment by Zelldon** [comment]
Snapshot replication https://workflowy.com/s/snapshot-replication/NYUFwTz94zNBmYqO

- We have one multi RAFT with multiple primitives
- Leader election primitive is used to detect which node should start processing for which partition
  - Leader of processing is independent of real RAFT leader
- Snapshot replication via primitives:
  - Idea was to use distributed map and set the chunks as value and as key the file name
  - We simply remove it after putting was successfully done - followers have listeners for events
  - Could independence of processing leader and RAFT leader be problematic for snapshot replication?
    - Scenario:
      - the leader of processing starts snapshot replication (because he is the leader of processing)
      - Snapshots chunks are added to a primitive
      - These are transmitted to the real RAFT leader and replicated
      - Case 1: RAFT leader changes
        - Will we have a leader election change ? Probably not 
        - Follower with longest log will win - hopefully atomix will take care of latest added stuff? I think it is retried
        - Adding to primitive blocks until event is committed
      - Case 2: Leader of processing changes
        - Why this would happen? Idk
        - Snapshot replication on old leader should stop
          - theoretically it would also be ok if we finish the replication, since the snapshot is valid and all the state changes - but if the leader is isolated he can't end this, might be better to stop and throw this away on the followers etc.
        - Follower, which become new Leader, needs to start from snapshot before, if no snapshot then at the begin of the log -> then reprocessing
      - Case 3: Follower is unavailable
        - If we remove the value directly after put was committed this will work for the quorum, but not for the follower which is currently not available
          - In best case he gets the missing events, which will then call the corresponding listeners
          - In worst case he was a long time away and the log was compacted, this means atomix will replicate the snapshot from the primitive - this would mean the follower gets a state of the primitive which does not contain the corresponding value
            - Quroum has the valid snapshot but not he - he can still be come leader since he has a valid state of the log and primitives
            - If he becomes leader he has no snapshot and will start from the latest or beginning of the log, but how we detect then that we can delete from log and the snapshots - this is not ideal
  - Improvement would be to have an extra entry where the consumers increment an count that they received the event - but what happens when we still have only the quroum - when it is time to delete data? How we retry sending chunks, this would mean i would again replicate in the whole cluster - maybe direct communication is the better approach
- Snapshot replication via broadcasting:
  - with atomix ClusterEventService we have the possibility to use pub-sub mechanics
  - The followers could subscribe for the corresponding partition snapshot replication
  - the leader will send broadcasts to the topic to replicate snapshots
  - At the end the leader sends to the topic the count of files he send
  - If a follower receives all files he sends an ack directly to the leader
  - if a follower does not received the same of amount of files he directly sends a message to the leader with the list of filenames and the leader will stream the missing files to the follower - after this is done the follower will send an ack
  - the leader counts the acks - if he successfully sends to all followers, the snapshot replication is done - this is the point where we can delete snapshots and after the exporters also ready delete data from the log
  - Leader of processing does not need to communicate over the real RAFT leader to replicate snapshots - each follower can request independent missing files
  - Follower could also request for snapshot replication if he joins
  - Challenges:
    - message max size is 1 kB
    - Case 1: RAFT leader changes
      - we don't care 
    - Case 2: Leader of processing changes
      - replication should stop and should be thrown away
    - Case 3: Follower unavailable
      - if he comes back he can request for snapshot replication
      - We could periodically send the latest snapshot position (name)
        - if the follower notices that he misses this snapshot he could request it

**Comment by Zelldon** [comment]
### Approach we want to implement:
  - Leader does snapshot
  - Starts with replication (message contains metadata - like sender, filename snapshot pos etc.
    - we need sender to ensure that follower we only accept snapshots from real current leader (might be two, because the old leader does not know yet or the message was delayed)
    - snapshot pos - to know to which snapshot this file belongs to
  - Follower accepts snapshot files when sender is leader
    - counts received messages 
    - if total number of snapshot files is reached sends ack to leader
  - Leader counts acks - if qourum is reached then snapshot is marked as replicated 
    - after this point we can decide to delete data
  - in the first implementation follower of stream processing will not ask for snapshot  (we can add later this functionality as improvement)
    - at some point in the future it will get one

    - we need to make sure that leader of processing has longest log and snapshots
      - we need to control the leader election somehow
