### ISSUE TITLE
Spike: long polling for job workers 

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#2430]
**Goals**
* reducing the load if there are no jobs to work on
* reducing the latency - the time between a job is created and a worker gets the job 

**Idea**

* long polling from client side
* if there are no jobs to poll from the brokers then the request is blocked 
* a broker sends a notification if a job is created
* the gateway polls again and send the response back to the client

**Comment by saig0** [comment]
**Results**

Test environment:
- Single Standalone Broker
- 10 workers (Java) 
- idle for some minutes
- then, creating 100 jobs

Current implementation:
- idle load ~ 10% CPU
![current-job-polling](https://user-images.githubusercontent.com/4305769/57299942-14747700-70d6-11e9-97ce-62158a087309.png)

Long polling:
- idle load ~ 3% CPU
![long-polling](https://user-images.githubusercontent.com/4305769/57299943-150d0d80-70d6-11e9-91a0-222c06737c9d.png)

**Comment by saig0** [comment]
**Implementation**

Spike: ac8ccefe470ad57459fbdf816298a0a2c356b5bc

* client requests jobs from the gateway
* the gateway requests jobs from the broker - round-robin (like the current implementation)
* :new: if there are no jobs then the request is blocked (instead of closed) and it subscribes to an Atomic topic 
* the broker sends a message to this topic when a new job is created (via broadcast)
* the gateway receives the message and the blocked request requests jobs 
* the subscription is closed and other blocked requests are closed
* a blocked request is closed at least after 10 seconds (i.e. long polling timeout)

**Comment by saig0** [comment]
@menski: do you have any questions? How do you want to continue on this topic?

**Comment by menski** [comment]
@deepthidevaki this issue might be interesting for the long polling job worker OKR

**Comment by deepthidevaki** [comment]
We discussed some modification to the previous approach. The basic idea is the same where gateway blocks a request until broker notifies that jobs are available.

Semantics:
* Client requests activateJobs(maxAmount, timeout). 
* return x jobs, 0 < x <= maxAmount, OR when no jobs available wait until a timeout and return 0 jobs.

Gateway 
* keeps track of jobTypes that are not available.
* subscribes to a 'topic'

Broker
* notifies when jobs become available again (available jobCount becomes 1 from 0) via broadcast to 'topic'

When gateway receive a request
* If jobs are available, forward request to the broker(s)
* If jobs are not available block the request
* Blocked requests are completed after a timeout (configured by the client)

When gateway receives a response
* If response (after probing all partitions) contains 0 jobs
  * record it
  * if number of responses with 0 jobs > threshold, mark jobtype as not available
  * update lastUpdatedTime
* if response contains > 0 jobs, mark jobtype as available (and unblock if there are any)

Notifications
* on notification, mark jobtype as available and unblock all requests (unblock => forward request to the broker(s))
Notifications are not reliable. If gateway misses some notifications, it might block the requests for ever. To prevent that, when lastUpdatedTime is old enough, gateway probes the broker by unblocking one request.

Pro:
* when jobWorkers < jobsAvailable, this approach has no overhead
* when jobWorkers >> jobsAvailable, number of spam requests is greatly reduced

Cons:
* There is a small latency when a job is available and job is activated because gateway forwards the request only after getting the notification.
* When a notification is missed, the requests might be blocked (until a timeout) even if jobs are available.
* On notification, all blocked requests are forwarded, even if there is only 1 job available.
