### ISSUE TITLE
Healthcheck endpoint for broker

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#2484]
Provide a healthcheck endpoint such that an external system can observe if a broker is up and ready to process, i.e. the broker is up and running **and** stream processor leader/ready to become stream processor leader, for all its partitions.

NOTE: I'm adding this here as something we need to build eventually, when starting it we should discuss the design and split it into further issues.

**Comment by jwulf** [comment]
This would be good for the Gateway, especially. If you stand up several Gateways and put them behind a single Consul DNS address with round-robin, you need them to be marked critical and removed from the pool if they are not working.

See: 

* [
Checking service health status with Consul](https://codeblog.dotsandbrackets.com/consul-health-check/)
* [Consul - DNS interface](https://www.consul.io/docs/agent/dns.html)

**Comment by npepinpe** [comment]
We unfortunately won't do a health check at this time, but only a ready check to support rolling upgrade with k8s (see https://github.com/zeebe-io/zeebe/issues/2613)

**Comment by Zelldon** [comment]
I might have an idea how we could support an health check. 

### Solution 1:

We add an method to the StreamProcessor like 
```
ActorFuture<boolean> healthy() {
 return actor.call(() -> true);
}
```

On health requests we call all running processors and collect the responses. If some of the processors are not responding in time, then the partition is unhealthy. This might happen because the processor loops in `writeEvent`, `onCommit` or `sideEffects`.

#### Advantage
We directly know that the processor is able to make progress, otherwise had wouldn't be able to complete this future.

#### Disadvantage
We can flood the processor with calls. We interrupt the processor on making progress.

### Solution 2:

We just take a look at the last 10 sec processing metrics, of the running partitions on the current broker.

#### Advantage
 * Will not interrupt the broker. 
 * It is not that problematic like the solution 1 if we get many requests

#### Disadvantage
Could be not 100% up to date.

----

I probably would prefer solution 2. What do you guys think?

**Comment by deepthidevaki** [comment]
In a very high level view, we can say that a zeebe cluster is healthy when it can process workflows and commands on all partitions. One solution would be to send a command to the cluster, and verify if we get a successful response. However, sending one extra command frequently to the broker can flood the broker which is probably already overloaded. Moreover, it cannot indicate other partial failures that can happen. For example, when snapshots are not being taken, we can never compact the logstream, eventually leading to out of disk space. Here is one proposal. 

#### RFC: 

We define different levels of healthiness for a cluster.
3 - Fully functioning
2 - partial failures(non critical)
1 - some leaders not healthy (indicates only some partitions are processing), 
0 - no healthy leaders (nothing processed)

As an example, if we query `zbctl status health`, it returns `Cluster-health: 3` (indicating fully functioning).
Or with more details
```
Node0:
    Partition-1 : Leader: 3
    Partition-2 : Follower: 3
    Partition-3:  Follower: 2 (partial failure)
        Snapshot : 0 (not running)
        Replication : 3
        Processing : 3
Node1:
    Partition-1 : Follower: 3
    Partition-2 : Leader: 3
    Partition-3:  Follower: 3
Node 3:
    Partition-1 : Follower: 3
    Partition-2 : Follower: 3
    Partition-3:  Leader: 3
Cluster-health: 2 
```

#### Determining the health of a partition
First we define what are the critical and non-critical components required for a partition to function properly. For example, StreamProcessor, LogStorageAppender, Raft leader thread are critical. If any of them encountered some errors (eg:- I/O exception), and if we know how to handle them correctly (for eg:- retry) handle them, otherwise stop the component. 

We will then have a `health monitor` that periodically (not too frequently) checks the component and detects that it is not running anymore or caught in a live lock making no progress. See @Zelldon  ‘s solution 1 above. The health monitor or an associated process can take some action such as trigger a leader step down or just report the status so that a human operator can have a look at it. Health monitor for a partition aggregates the health of different components to determine the overall health. The health status can be exposed via prometheus metrics and/or via a query similar to topology request or via a health check endpoint similar to readiness probe.

The main point here is that, when we don’t know how to handle an exception stop moving forward(retry for ever) or better stop the component so that the health monitor can detect it. If you are reminded of erlang/Akka’s supervisors and 'let it crash' philosophy it is purely unintentional :wink: 

Pros: 
It gives overall health of the cluster, also giving a more in-depth view of what is not functioning. It also indicates failures that can eventually lead to catastrophic failures in future.  

Cons: 
It probably cannot detect liveness issues that can happen due to bugs in the code.
We should use a combination of metrics and health check status to get a complete picture of the zeebe cluster. 

@afirth @salaboy What do you think about such a health check?

**Comment by afirth** [comment]
hell yes. crashlooping triggers alarms for us and we can figure out how to fix it if possible after that, even if the restart doesn't fix

**Comment by Klaus-Nji-sp** [comment]
I fully support the idea of a health check or the ability to query Zeebe for its health status.  I also think @Zelldon's second proposal will be less taxing on Zeebe given all the potential performance problems we may be encountering.  Even though what we get may not be 100% accurate, it will be good enough to meet most use cases.  

I also like @deepthidevaki's idea on identifying critical components to limit the scope of health checking.  While you can have these components expose a way for one to query their true state of health (which I imagine may not be cheap), it may be better to simply let each component report some sort of approximate state of health during normal operation, which can be used to approximate overall cluster health state.  These components can still report this even if they have nothing to do.  Such a mechanism can be used to power some sort of indicator in Operate or similar and will also solve the problem of getting health status with no workflows to process.

If an operator is still suspecting that the cluster is really not healthy, then maybe they can invoke the more expensive health check which then calls all these critical components to report in their true health state.

**Comment by npepinpe** [comment]
@deepthidevaki I like it. I'm all for moving forward with the let it crash philosophy - if a partition's critical component fails, instead of retrying forever we could simply restart the partition to a known good state, and if impossible mark as unhealthy and shut it down (at which point a manual action is required).

**Comment by salaboy** [comment]
@deepthidevaki and all, I really like the RFC, the only thing that I would like to add is some kind of hook points to enable a pluggable way to solve problems. It might be that we just trigger an event and then another component takes care of killing the wrong behaving component. 

Also, the more information the better in `zbctl status` or `zbctl status health`

**Comment by deepthidevaki** [comment]
@salaboy Yes. Reacting to failures is the next step. We can already handle crash failures because of Raft. So some failures would be fixed by just restarting the component or broker. Having a health check will enable us to do that.

**Comment by salaboy** [comment]
@deepthidevaki 👍 I was thinking more hooks for when failure happens so we can let the infrastructure knows about the failure and that leader election is happening. That is something that the StatefulSet today is not handling.

**Comment by npepinpe** [comment]
We have added a health check already :+1:
