### ISSUE TITLE
Remove deployed workflows

### ISSUE THREAD

**Issue by ankita-p17** [zeebe-io/zeebe#2506]
I have deployed two workflows using BPMN in zeebe - `order-process` and `test-process`.

Below are the two: 

```
{ workflows:
   [ { bpmnProcessId: 'order-process',
       version: 1,
       workflowKey: '1',
       resourceName: 'order-process.bpmn' },
     { bpmnProcessId: 'order-process',
       version: 2,
       workflowKey: '3932',
       resourceName: 'order-process.bpmn' },
     { bpmnProcessId: 'test-process',
       version: 1,
       workflowKey: '24423',
       resourceName: 'test.bpmn' } ] }
```

How can I delete one of them??

**Comment by jwulf** [comment]
Hi @ankita-p17 - there is currently no way to remove a deployed workflow definition.

**Comment by jwulf** [comment]
It could be possible to mark it a workflow as "undeployed", but not delete it. This would allow running instances to continue, but no new instances to be started, and it would be hidden from the list of deployed workflows.

**Comment by menski** [comment]
For now we do not plan to implement this in the near future.

**Comment by vbratitsa** [comment]
Is it possible to set status : Active=false?

**Comment by aleksander-dytko** [comment]
Hi there, in Q3 we'll be working on #9576 

Currently, we started to work on exploring and designing the process definition deletion topic. We are running a research project to understand end-users approach to the matter, context and needs so that the UI will be friendly and supportive.
For this we are looking for participants among community members - those who have relevant experience, demand for the feature.
We will appreciate your help by:
- having a 30min Zoom call with us

@vbratitsa-plana @ankita-p17 would you be interested to give us a bit of a context from your side during the quick session?

Thanks in advance:handshake:
CC: @EvgeniyaUX
