### ISSUE TITLE
Inconsistency in RecordValue API

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#2616]
During the refactoring I noticed some inconsistency in the RecordValue API. I will collect here everything I find.

-------

### JobRecord

JobBatchRecordValue
* in Java API  `getTimeout`, which returns a **Duration**
* in JSON it is called `timeout` and is a **long**

JobRecordValue

 * in Java API `getDeadline`, which returns a **Instant**
 * in JSON it is called `deadline` and is a **long**

#### Suggestion

 * Rename it to deadline. Always return as type long. I see no use case in having these complex objects. 
 * `MessageRecordValue#getTimeToLive` returns a **long**
 * `TimerRecordValue#getDueDate` returns a **long**

#### Result

* consolidate everything to `long` and document the unit, i.e. duration in ms or timestamp since unix epoch
* no renaming 

-----

### Variables vs Custom Headers in JSON

 * Why are the custom headers a normal object (map) and the Variables JSON in a string property

Example:

```
{
   'headers':{
      'bpmnProcessId':'test-process',
      'workflowKey':13,
      'workflowDefinitionVersion':12,
      'workflowInstanceKey':1234,
      'elementId':'activity',
      'elementInstanceKey':123
   },
   'worker':'myWorker',
   'type':'myType',
   'variables':'{\"foo\":\"bar\"}',
   'retries':12,
   'errorMessage':'failed message',
   'customHeaders':{
      'workerVersion':42
   },
   'deadline':13
}
```

This is BTW only the case if the `RecordValueWithVariables` interface is implemented. All records which only have a method that returns a map do not have this kind of problem. Currently this is controlled in `RecordValueWithVariablesImpl`, that the string method is serialized instead of the `asMap`.

#### Result

- to make `asMap` default we have to investigate how to solve the problem of ES indexing all variables, after that we can always return a map and remove the `String` method

------

### IncidentRecordValue

 * Has the method `getVariableScopeKey`and `getElementInstanceKey`, where is the difference?
 * The doc states that there is no. Doc for `getVariableScopeKey` says `the key of the element instance to use in order to update the correct variables before`

#### Suggestion

Remove one of them.

#### Result

- improve documentation to clarify difference

### IncidentRecordValue#getErrorType

 * returns String instead of the ErrorType enum
 * `WorkflowInstanceRecordValue#getBpmnElementType` returns the enum 
 * `DeploymentResource#getResourceType` returns the enum
 * `VariableDocumentRecordValue` returns the enum

#### Result

- return enum

-----

### VariableDocumentRecordValue

* Does not extend RecordValueWithVariables
 * Has only the method `getDocument`, which returns the Variables as Map

#### Suggestion

 Why we have both? Variables as Map and JSON, might be enough to have `asMap`. If the user wants a JSON he can call `toJSON` of the record OR serialize by himself.

#### Result

- should extend
- rename getDocument to getVariables, also check the ES exporter please

-----

### WorkflowInstanceCreationRecordValue

 * does not extend RecordValueWithVariables and only supports getVariablesAsMap
 * `getKey` and `getInstanceKey` is called everywhere else `getWorfklowKey` and `getWorkflowInstanceKey`

#### Suggestion

 * Rename it to be consistent and extend the interface

#### Result

- extend the interface 
- rename getters

----

### TimerRecordValue

 * What is the `getHandlerFlowNodeId`? 

#### Suggestion

It sounds really strange and as far I understand the doc it is the `elementId` ?

#### Result

- rename to `targetElementId`, and also adjust the `handlerNodeId` in the workflow instance subscription state as it is the same concept and should therefore be called the same

### RecordMetadata

* Why the getPartitionId is in the metadata not in the Record?
 I had this problem on migrating the UnpackedObjects to the interfaces. I had to add the partition Id to the RecordMetadata, see https://github.com/zeebe-io/zeebe/commit/1778006431b5646b258e77e5afa49cc4707782a7#diff-42752f066b34f22ce735dbe23ec3aedb . Would be easier, if we had this in the Record, since it can be derived from the key.

#### Result

- flatten everything into the record and get rid of metadata

**Comment by npepinpe** [comment]
I can answer some of them.

IncidentRecordValue has both `variableScopeKey` and `elementInstanceKey`, which can be different; one example is when an activity is in `ELEMENT_ACTIVATING` and it fails to extract a boundary event message correlation key; the variable scope key in this case is not the activity's but the parent scope (since a boundary event should not see the local variables of an activity), yet the element instance key is the activity's instance key (where the incident will be).

> Variables vs Custom Headers in JSON

Not sure, we should probably treat all message pack maps the same  (i.e. either always just provide `Map` or normally a string and also a `asMap` method).

> VariableDocumentRecordValue

Should probably implement the `RecordWithVariables` at this point, didn't exist when it was created I think (was still `RecordWithPayload`). 

Regarding the string + map for variables and other maps, is it a strict requirement that we always return JSON encoded strings? What would be so horrible in having the raw value return the message pack encoded bytes (i.e. what we actually have on the log) and a `asMap` method if a user wants to read that as a normal Java map? That way if you really want to avoid parsing it you can defer that to some later time, or we also provide the tools to do it easily (but only when required).

> WorkflowInstanceCreationRecordValue

:+1: 

> TimerRecordValue

`getHandlerFlowNodeId` is the element ID of the element which is the target of the event; so an activity might create a timer (so the instance key points to the activity), but the element ID will be that of the boundary event that will be triggered by it (since, for example, an activity may have several timer boundary events). Feel free to rename it to anything that makes more sense, but I think `getElementId` in this case will be confusing if its not the ID of the element with instance key `== getElementInstanceKey()`

> RecordMetadata

In general it's unclear to me the separation between `Record` and `RecordMetadata` :sweat_smile: I guess everything that we always write for every record should be in `Record`, and things that maybe are written (but are not part of the value) go in the metadata? Then partition Id should be part of `Record`, but probably some other stuff as well :sweat_smile:

**Comment by Zelldon** [comment]
Hey @npepinpe thanks for answering some of the things.

Regarding to the JSON part. Yes I already suggested this several times. I don't know why we need this exactly. I think with that we restrict our self with that.

**Comment by Zelldon** [comment]
@menski any opinion on this?

**Comment by menski** [comment]
We broke this down in separate issues
