### ISSUE TITLE
Add detailed examples for IO Mapping to the docs

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#264]
Examples should explain in more detail what is possible with the current IO Mappings.

One or more input and output mappings.
Adding and replacing of attributes, objects and arrays via mapping.

Also we should say what is not possible and why. For example $.* or $.[foo,bar] etc.

**Comment by ThorbenLindhauer** [comment]
* Can use more the language and concepts that our users know, e.g.
  * Introdcution: Motivate why and when to use mappings (=> task handler expects different JSON structure than workflow payload is in)
  * Introduction: Have a complete example consisting of workflow payload, mappings and task payload. That way, users can quickly get an intuitive understanding of the feature.
  * Output mappings: instead of talking about source and target document, write about task and workflow instance document/payload
  * Examples: Try to make JSON payloads more real-world-like, e.g. use an `order` object with attributes like `customerId`, etc.
* Input/Output Examples: Add the purpose of the example in natural language (e.g. "Rename value", "Push value down in hierarchy"). That makes it easier for people to find the example that is closest to what they want to achieve.
* JSON Path: Which subset of JSON path do we support?
* What is the behavior when I use multiple mappings?

**Comment by ThorbenLindhauer** [comment]
Review:

* the example BPMN image is missing
* in the example, state explicitly that the mapping is JSON-Path-based
* Input/Output mapping: The textual description is redundant with the table. Maybe we can shorten the text.
* JSON path expression: I don't think we need to explain why the root object is identified via `$`. Also, make the JSON-path spec link more visible
* Mapping examples: Make the description the first column, so that the tables can be read like a glossary.
