### ISSUE TITLE
publishMessage/publishStartMessage behaviours

### ISSUE THREAD

**Issue by OlivierAlbertini** [zeebe-io/zeebe#2795]
## Current behaviour

If message has not been correlated, it's a success. We use the publishStartMessage method but publishMessage has the same behaviour.

## Expected behaviour

If message has not been correlated, it should throw an exception because the message should be correlated at least to one instance.

## How to replicate

https://github.com/OlivierAlbertini/zeebe-issues

## Versions

zeebe_broker: 0.18.0
zeebe_node: 2.3.0

**Comment by saig0** [comment]
Hi @OlivierAlbertini, thank you for your input.

I think that the expected behavior doesn't match to the current system. It is designed that messages and workflow instances are not tightly coupled. For example, a message can be published before or after the workflow instance enters a proper message catch event. This makes it easy to build workflows that communicate asynchronously with other systems/services. 

If messages can be published only when a proper message catch event is entered then the message buffering doesn't make sense.  

What is the underlying problem you have with the current behavior?
Why do you want to reject the message publishing?

**Comment by OlivierAlbertini** [comment]
Hi,
> If messages can be published only when a proper message catch event is entered then the message buffering doesn't make sense.

Having the capacity to TTL message in order to trigger after it has been sent, it's good for some use cases, I imagine. 

Here a common use case for us. 
We create a workflow:
![workflow](https://docs.zeebe.io/bpmn-workflows/message-catch-event-example.png)
then a process instance is created, but we have an activity (collect money) that triggers a call to a REST API. 
When the process instance goes to the activity, the worker calls this API and complete (acknowledge) the activity, but at this moment there is a network outage and we can't complete the activity...
Since API has successfully execute his part, it executes "money collected" but the workflow instance is not there yet, because of the acknowledgement issue. The api doesn't know that the message is not correlated.

Rejecting the message publishing is useful when another system (that doesn't use Zeebe or Camunda BPM) triggers the message event. It should know that this message didn't work for X reason. In this way, It can retry or do something else.

> This makes it easy to build workflows that communicate asynchronously with other systems/services

In my opinion, we should at least keep track of that message event. We should have a way to get the state of that message event and know if it has correlated something or not.
For asynchronous operation, HTTP REST API return 202 status code with an endpoint (Operation-Location header) in order to keep track. 
https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#132-stepwise-long-running-operations

**Comment by saig0** [comment]
Thank you for the insides! Ok, let's discuss the example (in order to find a proper solution for the problem).

The worker for the task "Collect Money" calls a REST API asynchronously and completes the job - but the command is not sent successfully. The REST call completes and it publishes a message to "Money collected". This message is not correlated because the message catch event is not entered yet. 

You propose to reject the message to indicate that something is wrong. But how to continue in this situation? Who should handle this failure and how?

Currently, two things could happen:
a) the client may send a failed command for the job - because the complete command throws an exception
b) the job would timeout because no complete command is sent

In both cases, the job would be processed again by the worker. So, it would call the REST API again and the process continues eventually. Even without rejecting the publish message command.

Why do you model the asynchronous communication with a message? Instead, you could also complete the job when the REST call completes. This can lead always to situations when the message catch event is not entered yet. For example, if the message is published before the complete command is sent.

BTW: you can track the message correlation via Zeebe exporter API.

**Comment by OlivierAlbertini** [comment]
> You propose to reject the message to indicate that something is wrong. But how to continue in this situation? Who should handle this failure and how?

The system that calls "publishMessage" retry until it's a success. Since he makes the call, it has the responsability to successfully sends the event. Once the worker can acknowledge (no more network outage), everything will be fine.

> In both cases, the job would be processed again by the worker. So, it would call the REST API again and the process continues eventually. Even without rejecting the publish message command.

You make an assumption that the REST API will call publishMessage again. But often, in external system we see that the first time, he collect the money and since the first time it worked and he got no exception when he calls publishMessage, next time, when the worker will call the REST API, it will say to the worker that it already collected the money and won't call publishMessage again because for the system, everything is ok.

As you say for message event:
> This makes it easy to build workflows that communicate asynchronously with other systems/services
Very often in our case, we don't have full control on those systems and I don't think that's uncommon.

> BTW: you can track the message correlation via Zeebe exporter API.

Indeed, we could wrap publishMessage into a REST API and return a 202 to the client with Operation-Location header in order to check the result in the exporter API but it's a lot more work.
If publishMessage/publishStartMessage could return something that says "no correlation" or "3 correlations"... It will be useful. Or having something like publishMessageSync (return something) publishMessageAsync (current behaviour, fire and forget pattern).

Besides, It will be easier to transitioning between Camunda BPM and Zeebe if the publishMessage would have more in common. Indeed, /message in Camunda BPM throws a 400 if no correlation is made.

What do you think ? 
Thanks for the discussion and your help to resolve the issue.

**Comment by saig0** [comment]
That's for your input!

I see that your current approach works well for you. IMO: it's not ideal that the external system need's to retry publishing the message until the worker can complete the job successfully. 

In Zeebe, you could solve this problem by publishing the message with a TTL. So the message will be correlated eventually. No retrying is necessary. 

Or, you could complete the job in the external system instead of publishing a message. It's like the external tasks in Camunda BPM 7.

Does one of these solutions work for you? Why not?

> Besides, It will be easier to transitioning between Camunda BPM and Zeebe if the publishMessage would have more in common. Indeed, /message in Camunda BPM throws a 400 if no correlation is made.

Zeebe and Camunda BPM 7 have some overlaps. But Zeebe is built with [different ideas](https://zeebe.io/faq/#how-is-zeebe-different-from-camunda-bpm) in mind (scalable microservice orchestration). So, some problems need to be solved differently.

**Comment by OlivierAlbertini** [comment]
Yes I think that I can use TTL and a background check on elasticsearch (exporter data) in order to know if the message has been correlated.

Do you confirm that I can retrieve those info in the exporter ? So I can query elasticsearch in order to know which correlation has not worked ?

Thanks!

**Comment by saig0** [comment]
> Do you confirm that I can retrieve those info in the exporter ? So I can query elasticsearch in order to know which correlation has not worked ?

Yes. Make sure that you enable the index for `messageSubscription` (https://github.com/zeebe-io/zeebe/tree/develop/exporters/elasticsearch-exporter#index). When the message is correlated, it writes an event of value type `MessageSubscription` and intent `CORRELATED` which contains the key of the message.

Does this help you?

**Comment by OlivierAlbertini** [comment]
yes thanks @saig0!
