### ISSUE TITLE
Implement long polling for job workers

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#2828]
When no jobs are available, job workers will send job activation requests in a busy loop. Broker will then end up processing many requests with no useful results effectively slowing down other processing. As described in spike #2430, to optimize the resource usage when no jobs are available, we will implement "long polling" on the gateway.

* Gateway block requests if it thinks there are no jobs available for a type #2825
* Broker notifies gateway when job are available #2824 
* To prevent gateway from blocking requests indefinitely, it should also probe the broker periodically when it doesn't receive any notification for a specific duration #2826
* Clients should be able to configure a long polling timeout. #2827

**Comment by StephenOTT** [comment]
Any plans to add a event bus / sockets to allow polling?  What is the benefit of the long poll vs the socket based event bus?

**Comment by menski** [comment]
@StephenOTT 

> Any plans to add a event bus / sockets to allow polling? 

No we don't plan to add this in the near future

> What is the benefit of the long poll vs the socket based event bus?

Long polling is more reliable and less complex then having a persistent connection. Also with the clustered nature of Zeebe and our current approach of running Zeebe in a fault tolerate way streaming jobs from brokers through multiple layers of gateways/proxies is fragile and complex. That's why we choose to implement long polling as a more robust alternative.

**Comment by StephenOTT** [comment]
Great explanation. Thank you!

**Comment by Zelldon** [comment]
@deepthidevaki I assume this can be closed?

**Comment by deepthidevaki** [comment]
Yes :+1:
