### ISSUE TITLE
Reduce the default logSementSize

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3014]
**Is your feature request related to a problem? Please describe.**

I would propose to reduce the default logSegmentSize to a smaller number like 128 or 256 MB instead of 512 MB. 

**Benefits** of having smaller logSegmentSize:

 * more data can be deleted
 * finding of last position is faster

### More data can be deleted:

 We can only delete segments, which do not contain the last exported and processed position. For example say we have 3 segments, with our current default size (512 MB) and the last processed and exported position is located in segment 1. Then we are only able to delete segment 0.

If we have smaller segments then it depends where the position have been located before.
If it was on the top of the segment then there is no difference, but is it in the later half for example then we could delete more data if the log segment size is for example 256 MB.

### Last position can be found faster

Since https://github.com/zeebe-io/zeebe/issues/3006, we iterate only over the existing block in the last segment to find the last position. If the segments size is smaller then we have less data to read to find the last entry.

### Downsides

 We would have more metadata (for each file).
 Currently I'm unsure what else the downsides are.

**Describe the solution you'd like**
Change the default log segment size.

**Comment by saig0** [comment]
Note that a Atomix raft partition group has a default log segment size of 32 MB.

**Comment by Zelldon** [comment]
@npepinpe should we reduce the raft segment size again to the default?

**Comment by Zelldon** [comment]
@npepinpe ping

**Comment by npepinpe** [comment]
Sorry, seems I miss this comment before :sweat_smile: 

After the refactoring, the situation is a bit different. Scanning for the last event is done in a "reverse" manner (I say reverse because Atomix doesn't actually support moving backwards easily, but we essentially do `reset(index - 1)` until we find the latest entry). So I imagine the performance there is a little bit better as we don't scan everything? On the other hand, it's probably not optimal at all - but we shouldn't have many entries at the end of the log that aren't `ZeebeEntry` entries, so typically we shouldn't be seeking back too much.

What I see with the Atomix journal is, having smaller segments:

1. More in-memory `JournalSegment` references, which as we know take quite a bit of memory =/
1. However faster to find entries inside a segment as you pointed out - this might be something we can offset with the index density however, so we could probably find a trade-off in terms of memory usage somewhere
1. Your point about data deletion still stands, we can delete more data

My take on this is we need to define how we would measure an improvement here: throughput? Disk usage? Fail over average time/worst time?

I think we have all these metrics but fail over time (correct me if I'm wrong)?
