### ISSUE TITLE
Revise priority of client configuration for zbctl

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3066]
**Description**

At the moment, the configuration overwrite priority goes: environment > cli > code

That means that if I run:

```sh
zbctl --address localhost:26500 --clientID myClient
```

With an environment containing `ZEEBE_CLIENT_ID=test`, then effectively it will use `test` as the client ID.

In my opinion anything specified on the CLI has priority over the environment. Could be I'm in the minority here though, so if no one agrees we can close this :sweat_smile:

**Comment by jwulf** [comment]
I agree with this. Explicitly specified options should over-rule inherited ones.

**Comment by menski** [comment]
@MiguelPires please figure out what is the current state and then sync with me

**Comment by MiguelPires** [comment]
The reason why environment variables supersede CLI parameters is because the env vars are checked in the Go client and, if set, overwrite code parameters. Since zbctl uses the those parameters, they get overwritten by env vars in the Go client. The priority is env var > code, from the Go client's perspective there is no CLI. One solution would be to merge zbctl and the go client (there's even an issue for that https://github.com/zeebe-io/zeebe/issues/1740). Another would be to read the env vars in zbctl, configure the Go client to ignore them and have zbctl pass the correct values if they're not overwritten by CLI parameters (although this will almost certainly require a lot of duplication).
