### ISSUE TITLE
zeebe-test int 0.21.x release not compatible with java 8

### ISSUE THREAD

**Issue by castx1981** [zeebe-io/zeebe#3167]
In the latest 0.21.x release, zeebe support java 11 and remains compatible with java 8, however the zeebe-test module does not.

```bash
 ~  javap -verbose io/zeebe/test/ZeebeTestRule.class
Classfile /Users/xluan/io/zeebe/test/ZeebeTestRule.class
  Last modified 2019-10-4; size 5178 bytes
  MD5 checksum 2482c7df4e7b4e324ff0346239d1012e
  Compiled from "ZeebeTestRule.java"
public class io.zeebe.test.ZeebeTestRule extends org.junit.rules.ExternalResource
  minor version: 0
  major version: 55
```

**Comment by saig0** [comment]
Hi @castx1981,

the Zeebe Java client is compatible with Java 8 but the broker requires Java 11. Since the `ZeebeTestRule` uses the (embedded) broker, it also requires Java 11. It also uses some internal classes for the verifications (e.g. `assertThat(workflowInstance).isEnded()`).

If Java 11 is a problem for you and you don't need the verification then you can have a look at the Zeebe test-container integration: https://github.com/zeebe-io/zeebe-test-container

Does this help you?

**Comment by castx1981** [comment]
Thanks!
