### ISSUE TITLE
Decouple LogStream from FsLogStorage

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#3310]
**Description**

In preparation for switching log storage implementations as part of #3169, it will help the migration if we can decouple the `LogStream` implementation from the `FsLogStorage` implementation. In order to do so, a few changes will be introduced:

1. Rewrite tests which rely on `FsLogStorage` but are not testing it directly (e.g. `CompleteInBlockProcessorTest`)
1. Refactor LogStreamBuilder to accept a pre-built `LogStorage` implementation instead of building the log storage itself
1. Refactor tests that use the `LogStreamRule` to be completely `LogStorage` implementation agnostic

At the same time, it will be useful to trim down the amount of services currently used by the `LogStream`. We currently have a root service, a log stream service, a write buffer service, a log storage appender service, a log storage service, a log write buffer subscription service, and a log storage appender root service.

I think we can redesign the whole to be essentially two logical components: the log stream, and the appender. By making the `LogStream` an actor itself, we can then have it manage its whole lifecycle without the need for all of these services.

If something needs to perform any operation but writing to the log stream (reading, compaction, etc.), it can depend on the log stream service. If something needs to write to the log stream, it can depend on the appender service. I don't see much need for any other service.

**Comment by Zelldon** [comment]
1 . Do we need the `CompleteInBlockProcessor` for other implementations ? I assume not I think it is tightly coupled with the FsLogStorage. Probably it will go away if we remove the impl?
  2. Not sure here. in an ideal world I would expected the following Interface of the LogStream.

   LogStream:
       // opens the log and set up everything internally
       Future<Void> open();
       // creates a new reader which is able to read the Log
       LogReader createNewReader();
      // creates a new writer - you can have multiple writers 
      // the implementation have to take care of multiple writes (ring buffer for example)
       LogWriter createNewWriter();

     // delete up to given abstract position/ index what ever
     delete(int index);


Then If I use the LogStream interface  I dont care whether it is a Logstream which is replicated via raft or not I just want to write and want to read new records. As a LogStream consumer I dont care about the implementation.

In the implementation we would hide the "Appender", because it is still necessary to handle multiple writers.  Yes I think it makes sense that the LogStream is then the only service and probably an Actor.

**Comment by npepinpe** [comment]
Regarding the block processor, I was thinking about it, and apart from reprocessing, our normal usage is to read sequentially, so it might pay off to have read-ahead once normal processing kicks in, at which point the read-ahead buffer may be smaller than X entries and would need to cut them. That said, maybe we can remove it and implement a simpler read-ahead, or fetch it back from the history I guess, hard to say when we'll want to revisit read-ahead.

As for two, yes, that's also my ideal implementation, and I'd like to discuss that, but that's more changes that need to be done before we integrate the log. The interface you describe would be the finished product, but I'd like to have something in between where we're already using the Atomix log directly. So already cutting down how many services we have would move us in that direction.
