### ISSUE TITLE
Out of Disk space and elastic full index recovery

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3378]
**Description**

It might happen that we going out of disk space because we are not able to delete the log. 
The reason why we cant delete, can for example be an full index at elastic. If we clean up the elastic index or create new one etc. we are currently not able to recover.

Since we do not process due to atomix out of disk space handling, we are creating no new snapshots (process position hasn't changed). Even if we now exported everything we will not make any snapshots. We should do snapshots when processing Or export position has changed.

**Comment by deepthidevaki** [comment]
I had a quick look in to this issue. We can make `AsyncSnapshotDirector` to take snapshots when the exporter position has changed. But we are using the last processed position as the unique id for snapshot. This is a problem because in the new snapshot last processed position is not changed.
Log restore, for example, uses the snapshot id to find the processed position without opening the snapshots. If we get rid for log restore, with the upcoming changes to raft, then this wouldn't be an issue. Otherwise, we need a new naming scheme for snapshots and a way to get the last processed position efficiently.

**Comment by npepinpe** [comment]
In this case, wouldn't the combination be `lastProcessed` + `lastExported`? I mean, if we imagine that we actually have two state machines processing the log, then both positions form the unique ID.

**Comment by Zelldon** [comment]
This is the reason why we postpone it for now until we get the new log and snapshot format :smile:

**Comment by deepthidevaki** [comment]
The first solution we discussed is to take snapshots also when exported position is changed even if processed position doesn't change. This won't work because of following.

##### In leader:
Assume we have the following state:
Logstream: e1,e2,e3,e4,e5,e6,e7,e8,e9
Exported position: e1
Snapshot: s2,s5,s8 (consisting of last processed position 2,5 and 8, and exported position 1)
Broker went out of disk space after event e9.

After some time, exporter resumes and exports until event e9. But broker cannot take new snapshots because there is no space to write new ones. So it cannot delete events. To address this, we could try to ensure that there is enough space for snapshots always. For eg:- stop writing to logstream before it is actually out of space.  Then we have another problem that it should take 3 (default configuration) new snapshots before it can delete until the new exported position, because we always use the oldest snapshot to find the position to delete. If there are no changes to processed or exporter position, we never take new snapshots. So log stream can never get compacted.

##### In follower:
Assume the same state in follower. It cannot delete any events until it gets a new snapshot with new exported position. But it cannot receive new snapshots because its disk is full.

### Alternative approach:
We can provide exported position to `LogStreamDeleteionService` instead of it reading from the snapshot. But, this fails the recovery when `ExporterDirector` tries to seek to exporter position present in the snapshot. It violates our assumption that we can recover from any of the available snapshots. Also followers should be informed about the new exported position with out sending the snapshot. So this is also not an ideal solution.

**Comment by npepinpe** [comment]
Hm, if we use the RocksDB checkpoint mechanism, on the leader, then when writing a new snapshot with the only difference being the exported position, we would need very little space, since most files will be hard links as nothing can be processed until we have more disk space. Admittedly this doesn't help on the follower side - unless we decide to implement ourselves replicated hard links (do-able but let's not go there yet :sweat_smile:). So it might be a lot easier to estimate the required disk space to perform a snapshot and ensure that we always have that.

I'm OK with possibly running into an out of space error every once in a while and having to provision more disk space to recover - the important part is that we recover once we have more disk space. Our goal then is to minimize how often we run into these errors by cleaning up as aggressively as possible. 

Just a thought for the follower - assuming total disk space is the same on every node, is it possible to run out of disk space before the leaders? I would expect only in the case of a partition imbalance - i.e. some nodes have 4, 5, or 6 partitions, and if one is follower of 6 partitions then possibly it runs out of disk space before its leaders, at which point it can't ever delete anything until more disk space is provisioned? That seems like a different issue however, unrelated to exporters.

> Side note: I would propose we wait until #3447 is done before we add new functionality touching snapshots (unless we find a solution here which doesn't touch snapshots then let's go for it). I'd like to test compression on snapshots and other things, but without metrics all these things are kind of pointless.

**Comment by Zelldon** [comment]
Might be interesting for the discussion how large are snapshots are

```
root@zeebe-0:/usr/local/zeebe# du -h data/raft-partition/partitions/1/
2.9M	data/raft-partition/partitions/1/snapshots/146006579-12-1578586661498-329651632284256
168K	data/raft-partition/partitions/1/snapshots/146006559-12-1578586020334-329651632280096
560K	data/raft-partition/partitions/1/snapshots/146006529-12-1578585120297-329651632273856
3.6M	data/raft-partition/partitions/1/snapshots
4.0K	data/raft-partition/partitions/1/pending
11M	data/raft-partition/partitions/1/runtime
290M	data/raft-partition/partitions/1/
```

**Comment by Zelldon** [comment]
I think we can now recover from this situation much better. We now have only one snapshot at a time https://github.com/zeebe-io/zeebe/pull/4063 and we take snapshots always without any restrictions https://github.com/zeebe-io/zeebe/pull/4066.  Since atomix stops on reaching a watermark we will still have disk space left to take a snapshot, furthermore as @npepinpe  wrote snapshots are not expected to be too large. Even if we have no space anymore. Then the user still can give the system more space and then eventually the system should recover, since snapshots now taken always etc.
