### ISSUE TITLE
Partition drops requests with no loading

### ISSUE THREAD

**Issue by IcyEagle** [zeebe-io/zeebe#3453]
Hi there!

I must confess Zeebe-0.22 (yes, SNAPSHOT) works much better because of the latest fixes! Nevertheless, I have some sudden delays during job processing. In other words, if I have a flow with several processes connected sequentially, the workers receive a job every 20 seconds, but they have to be processed without such huge delays (instantly). I suppose it happens when a particular partition is engaged. I checked logs and found it:

![image](https://user-images.githubusercontent.com/803284/69879434-7c8be400-12d8-11ea-92c3-d6cd7fe84fe3.png)

For some reason, the partition rejects requests on different nodes.

Are there any ideas about why it happens?

**Comment by IcyEagle** [comment]
Any news?

**Comment by npepinpe** [comment]
Are your clients receiving many `RESOURCE_EXHAUSTED` errors? The logs you see refer to the adaptable flow-control that's built into the command API (i.e. where user commands are received in the broker). The limit is adaptative (we use [Netflix/concurrency-limits](https://github.com/Netflix/concurrency-limits) if you want to know how it works under the hood) - very simplified, it keeps track of a sampling window and recalculates the limit based on the min, max, and average latency of the requests sampled in the window.

What the logs you have imply is that it takes too long for your broker to process requests and 8 is about all it can manage to maintain its baseline (which is admittedly quite little). We have an issue to tackle this #3137, but I have to admit in practice we rarely see such low numbers. It's a bit difficult for me to diagnose what the real issue here is without access to more information. If you need more help we can discuss it on Slack as well.

**Comment by Zelldon** [comment]
Due to inactivity and missing information I will close this. Feel free to reopen it with further information, which might help us here.
