### ISSUE TITLE
Can we move go build and tests into parallel stage

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3511]
**Description**
We currently running `java build -> go build -> go tests -> other tests in parallel stage`. Could we move the go build and tests in the parallel stage?

**Comment by MiguelPires** [comment]
Reopening this issue because the PR moving the go build and test was reverted since it was causing one `zbctl` test to fail on the CI. I'm not sure why it was failing so I don't know if this issue is still possible or not. I couldn't reproduce it locally with a Docker image built from develop but moving the Go stages back to before the Java tests fixed the problem.
