### ISSUE TITLE
Test Distro StandaloneBroker

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3516]
**Description**

Currently we have no tests for the StandaloneBroker that is able to start and process.
With https://github.com/zeebe-io/zeebe/pull/3513 I broke the start up, which means the Broker was created but not started. I was wondering why in k8s nothing happens until I checked the logs and I saw nothing was logged, besides that the config was initialized.

I think we should add a test to verify that our distro is working.

**Comment by npepinpe** [comment]
Generally we should aim to have a solid E2E suite which tests standalone gateway, broker, and our elastic exporter.

**Comment by npepinpe** [comment]
I would propose to close this issue for the following reasons:

1. The issue was rather broad in scope (from my POV, no clear acceptance criterias)
1. We're actively working on improving quality assurance with things like the Zeebe-tests-Zeebe topic
1. We now have more and more tests which use the distribution (e.g. `RollingUpdateTest`, `UpgradeTest`, etc.)

We should keep working on this, but having more concrete issues makes more sense to me than keeping this one around. Let me know if you think otherwise :+1:
