### ISSUE TITLE
Improve Client API

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#357]
* Make events a first-level API concept for request-response commands, i.e.
  * The result of a command is an event, i.e. the event that was written as the command's effect
  * The event exposes its properties and metadata such as topic-partition-key identification
  * I can instantiate a command based on a given event, so that I do not have to re-instantiate all properties
* Streamline client command implementation
* Throw `ClientCommandRejectedException` on *every* rejected command
* Hide partition id from user; for context-less commands (e.g. create task), the partition id should be determined by a certain strategy (=> constant value 0 for now); for context-based commands (e.g. complete task), should automatically address the partition the task exists in

**Comment by saig0** [comment]
**Review Hints:**
* ZeebeClient: TODO expose impl class  --> issue
* ClientCommandRejectedException: TODO expose request + response --> issue
* MsgPackField: TODO lazy init --> remove
* WorkflowDefinition: JSON annotation --> try to use it on impl getter 
* TopicSubscriptionBuilderImpl: commented code for raft event --> remove / issue 
* CommandRequestHandler: generic violation + serialize -> why do you write the position at the end --> add command for understanding
* WorkflowInstanceEvent: PROP_EVENT_TYPE -> rename to state
* CompleteTaskCommand: clearPayload is misleading (standalone task, task with out mapping) -> withoutPayload
* TaskController: prefer a combination with task event instead of two objects

**Comment by ThorbenLindhauer** [comment]
Re 
> TaskController: prefer a combination with task event instead of two objects

We decided to remove the auto-complete feature, as it causes duplicate APIs and is not trivial to maintain (e.g. in the previous state, auto-complete only works correctly if you use the provided task controller object for completing the task).
