### ISSUE TITLE
Does transaction creation support

### ISSUE THREAD

**Issue by 2259289435** [zeebe-io/zeebe#3587]
**Description**

A clear and concise description of what this issue is about.
like this
@transaction
public void m(){
     abc.savedb()
     zeebeclient.createinstance()
}
but spring commit fail

**Comment by Zelldon** [comment]
Could you elaborate on that, please?

**Comment by 2259289435** [comment]
ok ,thanks.
1. begin transaction
2. execute sql
3. createZeebeWorkflowInstance
4.commit transaction
between 3 and 4 os crash, but instance is create, the follow on business begin exection

**Comment by 2259289435** [comment]
> Could you elaborate on that, please?

ok ,thanks.

1.begin transaction
2.execute sql
3.createZeebeWorkflowInstance
4.commit transaction
between 3 and 4 os crash, but instance is create, the follow on business begin exection

**Comment by saig0** [comment]
Hi @2259289435,

it is an interesting idea to support transactions in the Zeebe Java/Spring client. 

Currently, this is not on your roadmap. However, if you have an idea of how this could look like implementation-wise then feel free to share your thoughts.

**Comment by 2259289435** [comment]
> Hi @2259289435,
> 
> it is an interesting idea to support transactions in the Zeebe Java/Spring client.
> 
> Currently, this is not on your roadmap. However, if you have an idea of how this could look like implementation-wise then feel free to share your thoughts.

thanks, so we can set unikey for createinstance? same unikey Multiple submit also create only one

**Comment by saig0** [comment]
Yes, kind of. If you are using a message start event then you have different options to ensure that only one workflow instance is created.

1) Setting the same message id when publishing a message. The message is rejected when there is already a buffered message (i.e. TTL > 0) with the same id.
2) Setting the same correlation key when publishing the messages. No workflow instance is created if a workflow instance with the same correlation key is currently active. (Available since version 0.22.0-alpha2)

Please have a look at https://stage.docs.zeebe.io/bpmn-workflows/message-events/message-events.html#message-start-events

**Comment by 2259289435** [comment]
> Yes, kind of. If you are using a message start event then you have different options to ensure that only one workflow instance is created.
> 
> 1. Setting the same message id when publishing a message. The message is rejected when there is already a buffered message (i.e. TTL > 0) with the same id.
> 2. Setting the same correlation key when publishing the messages. No workflow instance is created if a workflow instance with the same correlation key is currently active. (Available since version 0.22.0-alpha2)
> 
> Please have a look at https://stage.docs.zeebe.io/bpmn-workflows/message-events/message-events.html#message-start-events

great，thank you

**Comment by Zelldon** [comment]
I assume this is solved for you? If you disagree feel free to reopen this issue.
