### ISSUE TITLE
Reduce number of snapshot and snapshot duration 

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#3622]
**Description**

- Max Snapshot should be 1
- Snapshot duration 5min
- Log Segment Size back to atomix default
- please update zeebe.cfg.toml accordingly 

Reason for this: #3573

**Comment by Zelldon** [comment]
related https://github.com/zeebe-io/zeebe/issues/3014

**Comment by Zelldon** [comment]
I run over night several benchmarks and will report here the results and my observations/thoughts.

To compare them and to know the steady state I also run a benchmark without any configuration changes, see below.


| Processing | Resources|
|----------------|----------------|
| ![normal-10-01-2019](https://user-images.githubusercontent.com/2758593/72141308-e77a1180-3392-11ea-80b1-e6e984fe8dc4.png) | ![normal-res-10-01-2019](https://user-images.githubusercontent.com/2758593/72141258-ca454300-3392-11ea-98a1-81f2821d3dc3.png) |




## Log segment size

 As I wrote in #3014 there are some benefits with having a smaller segment size, like more data can be deleted and finding of last position is faster. But there are also some downs to that as @npepinpe wrote https://github.com/zeebe-io/zeebe/issues/3014#issuecomment-566625388 like having more memory usage, because we have more segments in heap. 

To verify that I run a benchmark with 128 MB segment size and an benchmark with 32 MB segment size.


| Segment size | Processing | Resources| 
|----------------|----------------|----------------|
| 128 MB | ![log-128mb](https://user-images.githubusercontent.com/2758593/72141105-7cc8d600-3392-11ea-8877-2ddd460969fc.png) | ![log-128mb-res](https://user-images.githubusercontent.com/2758593/72140973-35dae080-3392-11ea-8e38-1fe5ab87dfd2.png) |
| 32 MB | ![log-32-size](https://user-images.githubusercontent.com/2758593/72141047-573bcc80-3392-11ea-8bcc-d764e19c9b7f.png) | ![log-32-size-res](https://user-images.githubusercontent.com/2758593/72141049-573bcc80-3392-11ea-9221-a873022a7ca2.png) |


As we can see 128 MB works quite well, but 32 MB not because of the high memory consumption, but 128 MB also scratches at the limits.

**Comment by Zelldon** [comment]
## Snapshot configuration 

| Configuration | Processing | Resources |
|--------------------|----------------|----------------|
| Max count 1 | ![max-snap-one](https://user-images.githubusercontent.com/2758593/72141571-67a07700-3393-11ea-9fee-072ade876dbf.png) | ![max-snap-one-res](https://user-images.githubusercontent.com/2758593/72141865-e85f7300-3393-11ea-806a-ed57b088d552.png) |
| Interval 5 | ![snapshot-int-5](https://user-images.githubusercontent.com/2758593/72141609-79821a00-3393-11ea-9abe-d04ab93e3641.png) | ![snapshot-int-5-res](https://user-images.githubusercontent.com/2758593/72141883-f3b29e80-3393-11ea-866d-6a1eafb04745.png) |
| Both | ![snap-int-5-max-1](https://user-images.githubusercontent.com/2758593/72141962-0b8a2280-3394-11ea-899f-039afc73d179.png) | ![snap-int-5-max-1-res](https://user-images.githubusercontent.com/2758593/72141964-0b8a2280-3394-11ea-8f75-546c3a934c9a.png) |

As we can see with a smaller snapshot interval it is more likely to run out of memory. Current assumption is that the replication takes a while and we still reference old snapshot chunks, which are not collected before we start the next replication. With a single snapshot the throughput looks quite stable but is much lower then the usual throughput, instead of avg 150 events/s we only reach 100.

**Comment by npepinpe** [comment]
Just a note, I discussed snapshots with Alastair, and it's very unlikely on GKE that a snapshot can get corrupted except during creation/replication - meaning we don't have to worry much about bit rot or failing sectors or anything like that, unless the user is using physical disks. So having a single snapshot as default should be fine if we can guarantee that committing a snapshot to the store tests that it's readable.

**Comment by npepinpe** [comment]
This is done, correct?

**Comment by Zelldon** [comment]
We havent reduced snapshot interval nor segment size

**Comment by Zelldon** [comment]
@npepinpe I removed my assignment here since I think we need to prioritize it first and I think everyone else can also do it.

**Comment by npepinpe** [comment]
We've been running with this for a long time in the cloud with good success - I would propose to lower the default interval to 5 minutes.

**Comment by Zelldon** [comment]
@npepinpe lets shortly summarize here what we want to do before I create a PR. 

 * We set the default interval to 5 min
 *  We set the log segment size to 128 MB

anything else?

**Comment by npepinpe** [comment]
One small thing, setting the log segment size to 128mb is backwards compatible right? It would just affect new segments? Can we verify this? This is more so if we do break I'm aware of it and not ah yes, this breaks (in case we ever want to backport this for some reason).

**Comment by Zelldon** [comment]
Hm didn't we anyway break compatibility with 1.0? I wouldn't backport this. If the user needs it, he can also set it on there own. I tried to start a broker with normal defaults and then I restarted with 128 MB and saw no errors. Then I did the same with publishing messages before and saw also no error. For me this was a bit unexpected tbh. How deep I need to test this? Feels unnecessary, since we break it anyway.
