### ISSUE TITLE
Nginx gateway (Load Balance for Cluster)

### ISSUE THREAD

**Issue by mirecl** [zeebe-io/zeebe#3628]
Hi guy.
**Question1**:
Answer pls, i can use nginx how gateway for zeebe cluster for load balance. 
For example a part of config nginx (upstream):
```
upstream zeebe_cluster  {
        least_conn;
        server node0:26500;
        server node1:26500;
        server node2:26500;
}
```
For example a part of config nginx (proxy):
```
location / {
        grpc_pass grpc://zeebe_cluster;
}
```
**Question2**:
How i can change type load balancing for zeebe gateway?

**Comment by saig0** [comment]
Hi @mirecl, please describe more about your use case. 
What do you want to use Nginx for? To replace the gateway?
Why do you mean with changing the type of load balancing?

The gateway is required for a Zeebe environment. It routes the client requests to the brokers. So, it is also kind of a load balancer since it balances the client requests to different brokers (currently round-robin). There can be multiple gateways if necessary.

**Comment by dmkost** [comment]
Hi @saig0!
As an example, I’ll give an example of architecture from the Zeebe documentation, which lists 3 brokers and 2 gateways . So, if there are two gateways, then for workers(ZeebeClient) how to balance out? After all, we need a high availability gateway.

![](https://docs.zeebe.io/basics/zeebe-architecture.png)

**Comment by saig0** [comment]
I think it depends on your use case. If one gateway is enough to handle the incoming requests then you just need a failback gateway for high availability.   

If you need multiple active gateways to handle the requests then the load balancer needs to assign the clients to the different workers. If possible, one client should communicate always with the same gateway - especially as a worker. So, only one gateway requests the jobs from the cluster.  

However, I can not provide any Nginx configuration.

**Comment by Zelldon** [comment]
I will close this for now. If you need more help feel free to ask questions in the [forum](https://forum.zeebe.io/) or in the [slack](https://zeebe-slack-invite.herokuapp.com/).
