### ISSUE TITLE
State from ELEMENT_ACTIVATED to ELEMENT_COMPLETING takes about 100 milliseconds

### ISSUE THREAD

**Issue by power522** [zeebe-io/zeebe#3815]
If a process has 10 service nodes, it will take about a second to complete without considering the business process time。This is very scary！
I used version 0.2.0, but I used the latest 0.22 test and the results were the same。
This is my running log, I'm just testing one piece of data, there's no concurrency
![image](https://user-images.githubusercontent.com/38269154/74136426-f7eb0980-4c28-11ea-8b93-da587390c9b5.png)

**Comment by npepinpe** [comment]
Hi @power522 

Can I ask what set up you were using? Running Zeebe in clustered mode introduces some necessary latency, as before processing any event, that even has to be replicated to at least a majority of the nodes. That said, even in single-node mode, there is added latency due to the fact that all service tasks as external tasks - a worker has to poll for the job, process it, complete it, and only then does the service task transition to `ELEMENT_COMPLETING`. This means that between `ELEMENT_ACTIVATED` and `ELEMENT_COMPLETING`, the following events must be replicated and processed by Zeebe:

1. ELEMENT_ACTIVATED
1. Job.CREATE
1. Job.CREATED
1. JobBatch.ACTIVATE (triggered by a worker/client ActivateJobsBatchRequest)
1. JobBatch.ACTIVATED (returned as response to the request)
1. Job.COMPLETE (triggered by the worker once it has completed job)
1. Job.COMPLETED
1. ELEMENT_COMPLETING

In single node mode, this means we have at least 2 requests/responses cycle, which necessarily add some overhead. In cluster mode, we'd have even more due to replication - until an event has been replicated to a majority of the nodes in the cluster, it will not be processed anywhere.

That said, performance is a long term goal, and achieving low latency would be great - I'm not trying to excuse the performance, I just wanted to explain how and where it is spread. Currently the focus is on stability and usability, but I hope we can devote some time in the future for optimization.

**Comment by power522** [comment]
@npepinpe
Thanks for your reply！
So that's a real problem right now, right? I thought I had a problem with the Settings

**Comment by npepinpe** [comment]
Well, this depends on your setup - in development if I run everything locally on the same machine I get much lower latency, but in a production setup where you have at least 3 Zeebe nodes, a gateway, perhaps an ingress, and your workers in different machines, 100ms between getting a job and completing it sounds plausible. It's hard for me to tell without knowing the whole setup and how latency is spread across it.

**Comment by power522** [comment]
Thanks! @npepinpe
I was running all the programs on the same machine, except for one borker that didn't start gateway

**Comment by npepinpe** [comment]
When running everything over localhost then the number of hops between the different services should be minimal - it will still add up a little but shouldn't be much. Most likely then it depends on your machine itself. Zeebe is I/O heavy and we often find ourselves running into saturated I/O capacity when benchmarking it, which naturally would translate as increased latency between events. 

One thing that might be interesting if you're benchmarking Zeebe - we export metrics to Prometheus, and there is also a Grafana dashboard in the project (https://github.com/zeebe-io/zeebe/tree/develop/monitor) which will let you visualize things such as wfi/s throughput, client request latencies distribution, and much more.

Thanks for reporting it, but unfortunately it's at the moment not a priority - I hope I explained well enough how the performance is distributed and why it's currently like this :) I'll leave this a open a little bit if you have anything to add, but I don't see anything actionable here at the moment. That said, we're always interested to hear about what you do with Zeebe (even if it is breaking it!), so for things like this come join us in our slack channel or on the forums!
