### ISSUE TITLE
Make zeebe repositories in Camunda nexus public

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#388]
At the moment the zeebe-io and zeebe-io-snapshots repositories in the private and can only accessed internally by Camunda. These repositories should be available to the public.

**Comment by menski** [comment]
@meyerdan, @hawky-4s- any input on this why we shouldn't do this?

**Comment by meyerdan** [comment]
No, we can make them public from my side

**Comment by hawky-4s-** [comment]
+1

Am 09.08.2017 04:44 schrieb "Daniel Meyer" <notifications@github.com>:

No, we can make them public from my side

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/zeebe-io/zeebe/issues/388#issuecomment-321136895>, or mute
the thread
