### ISSUE TITLE
Client can send Create Topic request to system partition

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#404]
* There is a system partition that does not perform task, workflow, etc. stream processing
* I can send a create topic request (topic name, number of partitions) to that partition
* The request is always rejected

**Comment by Zelldon** [comment]
# Review

## Code

 ### SystemPartitionManager 

  *  Are you sure that we do not need to stop/release the Processors in the `stop` method.

 ### NewTopicEventImpl

 * todo to rename TopicEvent

 ## Test
  *  What happens if partitions is zero?
  * Is there a limit for creating partitions?
  As discussed tackle the validation of the partitions value in a separate feature issue.

**Comment by ThorbenLindhauer** [comment]
See https://github.com/zeebe-io/zeebe/issues/424 for the upper limit on number of partitions.

**Comment by ThorbenLindhauer** [comment]
> Are you sure that we do not need to stop/release the Processors in the stop method.

This should not be an issue. On broker shutdown, the service container is stopped which makes sure all services are stopped in proper order. Furthermore, the system partition manager does not hold any other resources that need cleanup.
