### ISSUE TITLE
System topic orchestrates partition creation

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#406]
When creating a new topic with a number of partitions, the leaders of these partitions should be somewhat equally distributed among the cluster nodes

* There must be a management API endpoint for creating partitions
* There must be a strategy that selects the target brokers based on the number of topics they currently lead

**Comment by ThorbenLindhauer** [comment]
I'll implement round-robin as the broker selection strategy. Implementing a strategy that always selects the broker with the least partitions it leads is not trivial since partition creation is concurrent. E.g. imagine a situation with three brokers a/b/c that lead the following numbers of partitions 0/2/2. Now, create a new topic with 9 partitions. Naively selecting the broker with the least number of partitions results in 9/2/2. Round-robing results in 3/5/5 which is better. Of course, the first approach can be improved by counting any pending partitions, but this appears overly complicated to me right now. 

Applying round-robin to an already unbalanced cluster leaves the cluster unbalanced, but we are probably solving this problem on a lower level (e.g. we need a rebalancing mechanism anyway when brokers leave or join the cluster).

**Comment by menski** [comment]
- implement error response in [ClusterManagerFragmentHandler](https://github.com/zeebe-io/zeebe/blob/951426b0884742c551a341e74daef9effaa6c534/broker-core/src/main/java/io/zeebe/broker/clustering/management/handler/ClusterManagerFragmentHandler.java#L92)
- why has `onCreatePartitionMessage` a return type if it [always returns true](https://github.com/zeebe-io/zeebe/blob/951426b0884742c551a341e74daef9effaa6c534/broker-core/src/main/java/io/zeebe/broker/clustering/management/ClusterManager.java#L374)? Is there a case where this create partition call can fail?
- please use a logger instead of [system out](https://github.com/zeebe-io/zeebe/blob/951426b0884742c551a341e74daef9effaa6c534/broker-core/src/main/java/io/zeebe/broker/clustering/management/PartitionManagerImpl.java#L68)

**Comment by ThorbenLindhauer** [comment]
> implement error response in ClusterManagerFragmentHandler

I'll remove the TODO, it does not make sense for single message interaction

> why has onCreatePartitionMessage a return type if it always returns true? Is there a case where this create partition call can fail?

The return type can be `void`. There is no case for backpressure here.
