### ISSUE TITLE
WORKFLOW_INSTANCE_REJECTED

### ISSUE THREAD

**Issue by jsam** [zeebe-io/zeebe#418]
On the CLI user can execute create workflow instance with the following command

```./zbctl create instance --topic default-topic ../../examples/create-workflow-instance.yaml```

This command will try to do the magic behind the scenes and the possible results of this command is WORKFLOW_INSTANCE_CREATED or WORKFLOW_INSTANCE_REJECTED.

Now if he forgot to deploy the workflow with deploy command he will always get error WORKFLOW_INSTANCE_REJECTED.

Now what I'm wondering is that if there are more cases which can trigger this error or can I safely assume that he always just forgot to deploy? If there are multiple cases which can trigger this error it would be nice to have some kind of error code or reason description why creation of new workflow instance has failed.

Currently in the response I have no such thing so I just naively print out 
```
./zbctl create instance --topic default-topic ../../examples/create-workflow-instance.yaml
WORKFLOW_INSTANCE_REJECTED

Did you deploy the workflow?
```

Any input on this would be helpful. Thanks

**Comment by Zelldon** [comment]
Hey Sam,

the creation of the workflow instance can also be rejected if the payload is not valid.

Not valid payload means the JSON document is not a JSON Object on root level.
This could be the case if the user tries to create a workflow instance with an JSON Array on root level as payload. I think this can also easily checked by the client before the request is send. Since we have only this two cases I'm not sure if it makes sense to introduce error codes in that case. 

Greets
Chris

**Comment by menski** [comment]
I think in general we should provide error reasons to clients for all error responses as otherwise it is hard for users to understand why something does not work. And without a reason the client can only guess what was wrong. I would rename or replace this is issue with a feature request for an error reason on all responses.

**Comment by jsam** [comment]
I agree. I close this ticket and create a new one.
