### ISSUE TITLE
Go client should send the client type and version with his auth request

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4264]
**Is your feature request related to a problem? Please describe.**

On camunda cloud we have sometimes bug reports / incidents which might be already fixed with the latest version of the client, but the user uses a old client version.

**Describe the solution you'd like**

We would like to detect the client type and version, on requesting the auth token. This would make incident investigation much easier, since we then don't need to ask the user for this kind of information if there went something wrong. It would also make it possible to correlate failures with know bugs.

We thought about adding this kind of information in the user agent header on the client HTTP request. 

**Describe alternatives you've considered**
The alternative would be to ask the user for this kind of information.

**Additional context**

The content of the user agent should at least contain:

 * client type, e.g. GO client
 * client version, e.g. 0.22.2

**Comment by MiguelPires** [comment]
This issue is a bit more complicated then its Java counterpart so I'll add here a small breakdown. This would be easy to solve for `zbctl` since we're already using ldflags there to get the version. For the Go client, however, it's not as simple, since it's distributed as code instead of as a binary. A hacky alternative would be to read the version from a file but raises several issues. First, `go mod` doesn't distribute directories that don't contain `.go` files, so we need to either keep this file among the go code or add a dummy `.go` file to its directory. Another concern is that users can target a specific revision when specifying the go client as a dependency, so we also need to account for that. We need to bump the version for the release commit and then change the version immediately after. Finally, we also need to pass the version into the client when building `zbctl`. Otherwise, the client will fail to find the version file, since `zbctl` is a binary. Other alternatives include embedding the static file in the binary or passing it as a parameter, but these are either more complicated or messier than just using `ldflags` to set it in the Go client as well as `zbctl`.

**Comment by npepinpe** [comment]
What if version.go was a fallback when the ldflags property is missing? That way zbctl can set whatever it wants, and if it's not there (e.g. someone else's binary) it can be overridden. That implies users can also set whatever they want in their binaries, but to be fair, they already can if the vendor and modify it, so... :man_shrugging:

**Comment by MiguelPires** [comment]
Sorry, that's what I meant by my previous comment but it probably didn't come out very well. To summarize: if we don't build a binary, we can't use ldflags and we need to read it from file. If we do build a binary, then there won't be a file and we must use ldflags. They're mutually exclusive.

**Comment by npepinpe** [comment]
I mean, what if we do include a dummy `version.go` that first checks for build flags, and falls back to a hardcoded version? That would file would be present in someone else's binary, wouldn't it?

**Comment by MiguelPires** [comment]
AFAIK, no. There are ways around it but there's no out-of-the-box way of embedding the file in the binary. I think the solution is to look at the variable set by ldflags, if it's not set, then we're in "library" mode and we have the file next to the code (if not, them we use "development" or whatever, but that shouldn't happen). My only point was that I think these two modes are exclusive

**Comment by MiguelPires** [comment]
I looked into embedding static content using `go-bindata` and it solves our problem quite well. Essentially, it generates a Go file for the static content and we use that to load the asset. Unlike the other solution, this works regardless of how the code is distributed (e.g., we compile it into `zbctl`, it's distributed as code and compile into a user's binary).
