### ISSUE TITLE
I can define a condition for Msgpack JSON

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#430]
Use Case:
* conditions on an exclusive gateway

Examples:
```
$.a == 'foo'
$.a != 'foo'
$.b > 5
$.b <= 10
$.c == 'foo' or $.d == 'bar'
$.a == $.b
```

AT:
* I can compare a JSON value to string, number or boolean literal
* I can compare two JSON values
* I can combine conditions

**Comment by ThorbenLindhauer** [comment]
Review:

* Optimization: We can avoid comparing json-path expressions in the cache at workflow runtime, as it is already known at workflow compile time which json-path expressions are equal
* Parsing: 
  * Test the case where a json path expression is not valid (i.e. after compilation, the query is not valid)
  *  We currently have three points where we check if a JSON-path expression is supported (broker when validating a workflow; el parser; msgpack-json-path). Let's try to have this in one place (only msgpack-json-path and then check validity after query compilation). This makes it easier to maintain. Maybe we need to keep the validation in the broker for target mappings of an IO mapping (because there we don't use json-path for querying).
  * the regex for String literals is not trivial => please add comment of what the regex catches
* Formatting: Changes in `zb-parent` and `json-el` should use spaces instead of tabs
* `io.zeebe.msgpack.el.JsonConditionInterpreter.readToken(JsonPathQuery, DirectBuffer)` not garbage-free; instead of having a dynamic number of `MsgPackToken` instances in the cache, have a compact list where you copy each json-path result into and use two `MsgPackReader` instances as cursors for the list
* `JsonConditionInterpreter` uses `cache.reset()` which is not garbage-free
* Test cases where the input exceeds `Long.MAX_VALUE` and `Double.MAX_VALUE`
