### ISSUE TITLE
Improve current JournalTests

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4407]
**Description**

The atomix journal is our core component. In the past we have seen that there where some problems, which haven't be detected with the current tests. Most of these tests do not test different configurations of the journal more different entry size's. It happens that when we change a configuration that these test fail because we have a bug, related https://github.com/zeebe-io/zeebe/pull/4372#discussion_r417072513

In order to refactor the journal we should spent some time to make the tests more reliable and increase the test coverage.

**Comment by npepinpe** [comment]
First step is to investigate what coverage is currently missing, and how much effort it would be to add it. We can then re-prioritize this issue accordingly. Please rename the issue as well.

**Comment by npepinpe** [comment]
I would instead propose to refactor the journal to a simpler, stripped down version, instead of spending more time on the current one. But whether we close this issue or not will depend on whether or not we commit to the refactoring of the journal, which I can't yet say until I have a better idea of what Q4 will look like. For now though, I would lower the priority.

**Comment by npepinpe** [comment]
Please make sure our tests are good this time :)

**Comment by npepinpe** [comment]
On second thought, let's close this - writing good tests should not be an issue in itself, but part of normal issues.
