### ISSUE TITLE
elasticsearch mapper_parsing_exception - object mapping for [value.customHeaders.payload]

### ISSUE THREAD

**Issue by eetay** [zeebe-io/zeebe#4640]
Zeebe broker 0.23.1, elasticsearch 6.7.1

Error I get in zeebe broker:
```
2020-05-30 06:27:53.874 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] WARN  io.zeebe.broker.exporter.elasticsearch - Failed to flush at least one bulk request ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=object mapping for [value.customHeaders.payload] tried to parse field [payload] as object, but found a concrete value]]
zeebe            | 2020-05-30 06:27:53.874 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] WARN  io.zeebe.broker.exporter.elasticsearch - Failed to flush bulk completely
zeebe            | 2020-05-30 06:27:54.295 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] 
```

Reference: https://forum.zeebe.io/t/elastic-exported-tried-to-parse-field-payload-as-object-but-found-a-concrete-value/1296

**Comment by eetay** [comment]
I have custom headers, where in some tasks it's "payload"<->"something" (header-key <-> value) and some places it's "payload.whatever" <-> "someOtherString" (same task type)

Note:
My guess is the elasticsearch is not handling this, as it is applying parsing on what should really be a simple string. This decision is left to elastic, which creates the mapping by guessing the types; second time around, the mapping does not match document. It's a known thing for elastic

**Comment by eetay** [comment]
Please consider this elasticsearch feature as a "hotfix" solution proposal: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/ignore-malformed.html
@salaboy

**Comment by saig0** [comment]
Steps to reproduce:
* deploy a workflow with a service task that has following custom headers:
  * `x.y` = `foo`
  * `x` = `bar`
* create a new instance of the workflow
* verify that the job event is not exported to ES

Currently, the custom-headers property in the ES template for job/job-batch is defined as:
```
"customHeaders": {
  "dynamic": true,
  "type": "object"
},
```

So, the custom headers are indexed as objects. If a header key contains a dot (e.g. `x.y`) then ES creates a nested object for it. This works in general but breaks when the type of the value is changed (e.g. `x` instead of `x.y`).

Possible solutions:
* disable index of custom headers 
```
"customHeaders": {
  "enabled": false
},
```
* replace any dot in the header key `.` by something else, for example, `_`
