### ISSUE TITLE
Loops are not supported with self links

### ISSUE THREAD

**Issue by arpitagarwal78** [zeebe-io/zeebe#4645]
**Describe the bug**
adding self link to Service task result in deployment failure in Zeebe. (`blah service task`)
Note::
link can be of any type - conditional link / normal link.

**To Reproduce**
![image](https://user-images.githubusercontent.com/37263155/83473337-edd66a80-a4a6-11ea-91cd-f54ded21f5ad.png)
On upload of above bpmn file.

**Expected behavior**
Deployment should not fail.

**Log/Stacktrace**
Error: Command rejected with code 'CREATE': Expected to deploy new resources, but encountered the following errors: 'BoundaryEvent.bpmn': - Element: Task_1fitjp5 - ERROR: Conditional sequence flows are only supported at exclusive gateway 

**Environment:**
 - OS: Mac
 - Zeebe Version: 0.21.0
 - Configuration: NA

PFA - Sample.bpmn
[Sample.bpmn.txt](https://github.com/zeebe-io/zeebe/files/4714412/Sample.bpmn.txt)

**Comment by saig0** [comment]
@arpitagarwal78, thank you for reporting.

The deployment is rejected because conditional sequence flows are not supported yet.

Loops should be okay. If I remove the conditions from the sequence flow then I can deploy the workflow. 

A conditional sequence flow can be replaced by an exclusive gateway after the activity. 

Is there a reason why do you need to use a conditional sequence flow instead of an exclusive gateway?

**Comment by arpitagarwal78** [comment]
Since it was available we gave it a shot! Maybe we can fallback to exclusive gateway.

Appreciate all your help @saig0 

On the contrary w.r.t execution of above workflow with sequence links

Reference:
<img width="1119" alt="Screenshot 2020-06-02 at 2 18 55 PM" src="https://user-images.githubusercontent.com/37263155/83500264-2a708900-a4dc-11ea-9592-96399d82db93.png">

Loops were working fine :)

I had posted message two times to interpolate identical `BoundaryEvent` message.
But I was surprise to see parallel workflows are not ending and workflow is stuck in `Active` state.

Please feel free to correct me.
PFA: Sample.bpmn.file
[Sample.bpmn.txt](https://github.com/zeebe-io/zeebe/files/4715994/Sample.bpmn.txt)

**Comment by korthout** [comment]
@arpitagarwal78 If I'm not mistaken, it looks like you have an implicit parallel gateway after your service task (i.e. the service task has 2 outgoing unconditional sequence flows). If so, there is a token spawned for each of the outgoing sequence flows. 

The workflow is stuck because there is still an active token flowing from your service task to the end event **and** to the service task again.

**Comment by arpitagarwal78** [comment]
@korthout 
On posting of `IntermediateThrowEvent`(BoundaryEvent) the internal subprocess workflow(`blah`) should stop executing and should never loop.

On the other hand why is the second sequence flow (`2nd parallel branch`) not reaches end which don't have a loop logic and the message have been interpolated

**Comment by saig0** [comment]
@arpitagarwal78, thanks for your input! 
I'm closing this issue because it seems that we solved the issue with the conditional sequence flow and loops.

I like to continue the other issue related to the messages in the issue #4644
