### ISSUE TITLE
Elasticsearch exporter bulk is not limited

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#4668]
**Describe the bug**
The Elasticsearch exporter inserts all records in a bulk and flushes the bulk when the size/time limit is reached. If a failure occurs while flushing the bulk then the exporter try to flush the bulk again.

If a new record is passed to the exporter then the record is added to the bulk. 

If the failure persists for a longer period then the bulk is growing and may lead to an out-of-memory exception. 

**To Reproduce**
Stop ES while exporting records. 

**Expected behavior**
The exporter stops adding new records to the bulk after some limit is reached. 

**Log/Stacktrace**
Nope.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.23.0, 0.24.0-alpha2
 - Configuration: elasticsearch exporter

**Comment by MiguelPires** [comment]
The bug is caused by the fact that, after a failure, when we retry exporting a record, we append it to the bulk request again even though it has already been inserted in the first attempt. This causes the bulkRequest to grow with each retry until we get an OOM exception. To fix this, we can simply check if we're retrying (by looking at the last appended record) and not append the record again.

**Comment by strawhat5** [comment]
@saig0 @MiguelPires I have come across a similar issue in our Zeebe cluster, where the exporter is not pushing records to Elasticsearch. I am not able to find any error/warning logs, so not sure if it is the same issue. But, I am sure that the Elastic exporter is opened as I could verify in the logs:
```
2020-07-08 17:27:56.788 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] [36mDEBUG[m io.zeebe.broker.exporter - Open exporter with id 'elasticsearch'
2020-07-08 17:27:56.807 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] [32mINFO [m io.zeebe.broker.exporter.elasticsearch - Exporter opened
```

Post this initialisation, I do not see any error/warning logs in the broker. I have also verified that my Elasticsearch cluster is working fine, as I could push the logs to it from a local Zeebe instance.

Is there any way to verify that this is the same issue as #4668 or a different one? Also, if it is the same issue, how can I make the exporter to start exporting to Elasticsearch again? Any help is highly appreciated.

Zeebe version: `0.23.2`

**Comment by MiguelPires** [comment]
Hi @strawhat5, it doesn't sound like that this is the same issue. The issue here was that, if the exporter was continuously retrying to export the same record, it would eventually get an OOM. This issue would be triggered by repeated failures to export but it wouldn't be the cause of the failures themselves. @saig0 do you have an idea about what could be preventing the exporter from exporting?

**Comment by saig0** [comment]
I agree with @MiguelPires that this sounds like a different issue. 

@strawhat5 , please try to root cause the issue by looking at the metrics. In the metrics, you can see how many records are processed and exported.

**Comment by strawhat5** [comment]
Thanks for the replies. I have created a new issue #4921 . I will try to upload more observations there.
