### ISSUE TITLE
Why the monitored value of 'process_resident_memory_bytes' keeps increasing

### ISSUE THREAD

**Issue by wenminglei** [zeebe-io/zeebe#4769]
I followed 15 threads to create instances and tested for 40 minutes. Found that the value of this monitoring has been rising. After stopping the test, the value did not decrease.
version:0.23.3

![image](https://user-images.githubusercontent.com/9846114/85062603-56c61e00-b1db-11ea-8eed-35573b24f91b.png)
![image](https://user-images.githubusercontent.com/9846114/85089073-3d8d9380-b214-11ea-99fb-5897a467b0aa.png)

In addition, it is puzzling that I have stopped testing, no workflow instance is running, and the memory usage of jvm is still increasing.
![image](https://user-images.githubusercontent.com/9846114/85092537-6dd93000-b21c-11ea-8f7d-c4bf68955141.png)

It's so strange, I haven't run any instances during this time.
![image](https://user-images.githubusercontent.com/9846114/85095068-f4910b80-b222-11ea-890f-3adb639a3959.png)

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Paste the failure here
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by wenminglei** [comment]
The memory usage of my linux machine has also been increasing. I tested it with the back pressure mechanism turned off.

**Comment by npepinpe** [comment]
Hi wenminglei! Just a few questions:

1. You say you create instances, are you completing them?
1. You say you run this on your local machine, what JDK are you running with?
1. Following up, what garbage collector and options are you using?

Anyhow, from what I understand (though I can always be wrong :sweat_smile:) it's normal for the RSS to grow if there is no memory pressure on the system, as memory will not be immediately released back to the operating system - rather the pages are marked as freed, and the OS may reclaim them at any time. Remember that while in the end calling `free()` is typically a library call, and not a syscall, meaning it doesn't free the memory immediately. You can test that with a  small C program for example. 

But like I said, if there's no memory pressure, it's typical for the OS to not reclaim them immediately - I've tested this myself with Zeebe, and more specifically RocksDB, which is usually the biggest memory consumer as we store our in-flight state there. If you keep putting data into RocksDB, even when limiting its memory consumption, you will see the RSS grow and grow past the limit you set - however, if you run with a cgroup, for example, generating some memory pressure by artificially lowering the total memory available, you will see it will grow up to right below the cgroup limit and stay there.

That said, it doesn't explain why your Java heap grows so much - but that can again be related to how you configure your GC, since again without memory pressure there's little incentive to garbage collect/free memory.

Anyway, I'm not saying there's nothing wrong with Zeebe - for example we don't (yet) set proper memory limits to RocksDB, but this is coming soon as soon as #4756 is merged.

**Comment by wenminglei** [comment]
Hi @npepinpe 
1. You say you create instances, are you completing them?
    I create instances and complete them.

2. You say you run this on your local machine, what JDK are you running with?
     JDK11

3. Following up, what garbage collector and options are you using?
I am using G1GC. Below is my configuration.
```
exec "$JAVACMD" $JAVA_OPTS -Xms128m -verbose:gc -Xlog:gc:/apps/gate/gc.log -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:+UseStringDeduplication --illegal-access=deny \
  -classpath "$CLASSPATH" \
  -Dapp.name="broker" \
  -Dapp.pid="$$" \
  -Dapp.repo="$REPO" \
  -Dapp.home="$BASEDIR" \
  -Dbasedir="$BASEDIR" \
  io.zeebe.broker.StandaloneBroker \
  "$@"
```

**Comment by npepinpe** [comment]
I'm closing this for now, as we've made good progress in this area - see primarily https://github.com/zeebe-io/zeebe/issues/5736 and https://github.com/zeebe-io/zeebe/issues/4002 (especially comments after this one https://github.com/zeebe-io/zeebe/issues/4002#issuecomment-753307551).

I hope these other issues answer your questions - if not, please comment there :slightly_smiling_face:
