### ISSUE TITLE
Failed to install snapshot on follower on crash loop

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#4784]
Opened from #4088 as a cloud incident.

Hey @deepthidevaki, thanks for the input! As discussed here the snapshots and logs, going to prepare the `disc snapshots` and provide them as soon as I get them :)

[incident report](https://docs.google.com/document/d/1_Tdo9dH0ZrFbS3zEHnbm4gmc5oYYkw2yoeGXKWb6zW0/edit?ts=5edfd66e#)

## What we know so far
Since `2020-06-05 02:29 PM` broker-2 of an e2e-test cluster on int, `type: production S`, is frequently restarting. The cool thing is, that the cluster has 3 brokers and could still serve all requests with a monthly yield of 99.98% - even if  availability since then is is only 66% ([dashboard][db-zeebe]):
![image](https://user-images.githubusercontent.com/55736962/85135891-1bf5d180-b23f-11ea-9dc1-081f60932f3e.png)

Crash looping started after node was becoming unready and broker-2 restarted (dashboard):
![image](https://user-images.githubusercontent.com/55736962/85136100-69723e80-b23f-11ea-96a8-66f5c6402664.png)

Since then, broker-2 is not stable anymore and keeps restarting. Before it goes down, the following [error message][errmsg] appears:
```
RaftServer{system-partition-1} - AppendRequest{term=240, leader=1, prevLogIndex=263314, prevLogTerm=240, entries=0, commitIndex=263314} to 2 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.439e397a-b932-430a-8594-dac13c26b1c0-zeebe.svc.cluster.local/10.28.5.20:26502
```

Seeing the connection seemd to be refused from the broker-service, we had a look on the logs and found the following error you saw as well:
```
"RaftServer{raft-partition-partition-1} - Failed to send InstallRequest{currentTerm=284, leader=0, index=304599, term=284, timestamp=1592567415960, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1865337458}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1665856922}, data=HeapByteBuffer{position=0, remaining=825, limit=825, capacity=825, mark=java.nio.HeapByteBuffer[pos=0 lim=825 cap=825], hash=-2065033342}, initial=false, complete=false} to member 2, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot."
```

The "cool" thing is, that this [error][errnew] seemed to have shown up the first time when the pod stared to crash loop:
![image](https://user-images.githubusercontent.com/55736962/85136799-77748f00-b240-11ea-87e6-e1400a08e110.png)

## Provided data
**Logs**
- zeebe [439e397a-b932-430a-8594-dac13c26b1c0-zeebe][logslink]
      - filtered for [ILLEGAL_MEMBER_STATE][ims]

Snapshots from the [zeebe dashboard][lzd], when the error started (2020-06-05 ~02:29 PM CEST) 

**snapshots**
![image](https://user-images.githubusercontent.com/55736962/85135669-c28da280-b23e-11ea-86fc-ef522ace80cd.png)

**atomix**
![image](https://user-images.githubusercontent.com/55736962/85137080-e94cd880-b240-11ea-950b-1764e1f1505b.png)

[ims]:https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.message:%22ILLEGAL_MEMBER_STATE%22;timeRange=2020-05-26T22:22:00.000Z%2F2020-06-20T00:00:00.000Z;summaryFields=:true:32:beginning?project=camunda-cloud-240911

[logslink]:https://console.cloud.google.com/logs/viewer?project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-06-05T00:29:00.000000000Z&customFacets=&limitCustomFacetWidth=true&interval=JUMP_TO_TIME&resource=k8s_container%2Fcluster_name%2Fultratest%2Fnamespace_name%2F439e397a-b932-430a-8594-dac13c26b1c0-zeebe%2Fcontainer_name%2Fzeebe&scrollTimestamp=2020-06-05T00:30:45.306000000Z&advancedFilter=(%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0A)%0A

[lzd]:https://grafana.internal.ultrawombat.com/d/I4lo7_EZk/zeebe?orgId=1&from=1591340988339&to=1591390089363&var-DS_PROMETHEUS=Prometheus&var-namespace=439e397a-b932-430a-8594-dac13c26b1c0-zeebe&var-pod=zeebe-0&var-pod=zeebe-1&var-pod=zeebe-2&var-partition=All

[errnew]:https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.message:%22ILLEGAL_MEMBER_STATE%22;timeRange=2020-05-26T22:22:00.000Z%2F2020-06-20T00:00:00.000Z;summaryFields=:true:32:beginning?project=camunda-cloud-240911
[errmsg]:https://console.cloud.google.com/logs/viewer?project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-06-05T12%3A48%3A00.000000000Z&customFacets&limitCustomFacetWidth=true&interval=JUMP_TO_TIME&resource=k8s_container%2Fcluster_name%2Fultratest%2Fnamespace_name%2F439e397a-b932-430a-8594-dac13c26b1c0-zeebe%2Fcontainer_name%2Fzeebe&scrollTimestamp=2020-06-05T12%3A48%3A55.593000000Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%22439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Atimestamp%3D%222020-06-05T12%3A48%3A55.593000000Z%22%0AinsertId%3D%22q5voyfhaxt7vpxnvw%22

[db-zeebe]:https://grafana.internal.ultrawombat.com/d/Fsa_ief2/zeebe-per-namespace?orgId=1&from=1591221883660&to=1592572235944&var-ingress=zeebe-ingress&var-namespace=439e397a-b932-430a-8594-dac13c26b1c0-zeebe

_Originally posted by @hisImminence in https://github.com/zeebe-io/zeebe/issues/4088#issuecomment-646639381_

**Comment by hisImminence** [comment]
ssh access: `gcloud beta compute ssh --zone <zone> "instance-name-2020-06-22" --project <projectID>`

_zone_, _instance-name_ and _projectID_ shared privately.

**Comment by deepthidevaki** [comment]
@hisImminence Do you force restart pods when it is not ready with in a fixed time? I'm trying to understand why it restarts at a regular interval.

![image](https://user-images.githubusercontent.com/1997478/86441986-58c8ca80-bd0d-11ea-8a0e-af5ef894c370.png)

**Comment by Zelldon** [comment]
@deepthidevaki maybe due to Exit on OOM ?

**Comment by deepthidevaki** [comment]
There is no OOM.

**Comment by Zelldon** [comment]
ok sorry :+1:

**Comment by deepthidevaki** [comment]
![image](https://user-images.githubusercontent.com/1997478/86442236-c1b04280-bd0d-11ea-9e9a-714729229a3e.png)

**Comment by Zelldon** [comment]
Is this java heap or real memory usage?

**Comment by deepthidevaki** [comment]
It's real memory usage. The metrics is from pod metrics not Zeebe. We don't see any zeebe metrics since the broker is not ready yet. See #4872

**Comment by deepthidevaki** [comment]
I created a local cluster with the data from the above cluster. I observed zeebe-2 cannot become ready as it is stuck in a loop trying to receive a snapshot. 

#### Issue 1
 Zeebe-2 cannot receive snapshot from the leader. Before restart zeebe-2 has partially received a snapshot. It is in the directory `pending/`. On restart, the leader resends the snapshot. It goes all fine until the last chunk that is already in `pending/`. When the next chunk arrives, zeebe-2 is expecting a chunk that it has already received (which is wrong). So the snapshot replication restarts from the beginning. 

First attempt in replication
```
12:49:41.625 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 008572.sst chunk from 1
12:49:41.680 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 008573.sst chunk from 1
12:49:41.680 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Request chunk received out of order. Received 008573.sst  expected 000097.sst
12:49:41.782 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 000094.sst chunk from 1
```
Second attempt
```
12:52:34.721 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 008572.sst chunk from 1
12:52:34.780 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 008573.sst chunk from 1
12:52:34.780 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Request chunk received out of order. Received 008573.sst  expected 000097.sst
12:52:35.033 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 000094.sst chunk from 1
12:52:35.086 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 000097.sst chunk from 1
```
Third attempt
```
12:55:17.459 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 008572.sst chunk from 1
12:55:17.516 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 008573.sst chunk from 1
12:55:17.516 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Request chunk received out of order. Received 008573.sst  expected 000097.sst
12:55:17.580 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 000094.sst chunk from 1
12:55:17.643 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Received snapshot 313699 000097.sst chunk from 1
```
And it continues. (Note that following logs were added in my local cluster for debugging. You don't see it in the cloud console.)

On the leader we can see the following logs:
```
12:49:41.681 [] [raft-server-1-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - Failed to send InstallRequest{currentTerm=319, leader=1, index=313699, term=313, timestamp=1592808460016, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1721156706}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1749785857}, data=HeapByteBuffer{position=0, remaining=889, limit=889, capacity=889, mark=java.nio.HeapByteBuffer[pos=0 lim=889 cap=889], hash=-318386773}, initial=false, complete=false} to member 2, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
12:52:34.784 [] [raft-server-1-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - Failed to send InstallRequest{currentTerm=319, leader=1, index=313699, term=313, timestamp=1592808460016, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1721156706}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1749785857}, data=HeapByteBuffer{position=0, remaining=889, limit=889, capacity=889, mark=java.nio.HeapByteBuffer[pos=0 lim=889 cap=889], hash=-318386773}, initial=false, complete=false} to member 2, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
12:55:17.518 [] [raft-server-1-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - Failed to send InstallRequest{currentTerm=319, leader=1, index=313699, term=313, timestamp=1592808460016, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1721156706}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1749785857}, data=HeapByteBuffer{position=0, remaining=889, limit=889, capacity=889, mark=java.nio.HeapByteBuffer[pos=0 lim=889 cap=889], hash=-318386773}, initial=false, complete=false} to member 2, with RaftError{type=ILLEGAL_MEMBER_STATE, message=Request chunk is was received out of order}. Restart sending snapshot.
```

#### Issue 2
I tried a hot fix for issue 1. Then it did not end up in the infinite loop. Instead it was able to complete the snapshot replication. But the snapshot contains > 20000 chunks. So it took very long to complete the replication and mark the broker as ready. `cluster services started in 1384303 ms`

```
11:44:18.308 [] [raft-server-2-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/home/deepthi/work/src/github.com/zeebe-io/zeebe/data-zeebe-2/raft-partition/partitions/1/snapshots/313699-313-1592808460016, metadata=DbSnapshotMetadata{index=313699, term=313, timestamp=2020-06-22 08:47:40,016}}
11:44:18.549 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [7/11]: cluster services started in 1384303 ms
```

If you end up in issue 1, it is recoverable if the leader takes a new snapshot. Here, from the stackdriver logs, we can see that there were new snapshots. And zeebe-2 is receiving new snapshots, but never able to complete the replication. My current hypothesis is that it is a combination of the two issues that leads to this problem. On restart, zeebe-2 always have non-empty `pending/` so that leads to issue 1. After some time, leader takes a new snapshot and starts replication it. But it take too long to complete and to mark the broker is ready. Current assumption is that pod is restarted because it is not ready with in specified time. If this is not the case, we have to investigate further what caused the restart.

**Comment by hisImminence** [comment]
> @hisImminence Do you force restart pods when it is not ready with in a fixed time? I'm trying to understand why it restarts at a regular interval.
> 

Hey @deepthidevaki, interesting findings! We have the following settings that restart the zeebe container if Liveness probe failes:
```
Liveness:   http-get http://:9600/ready delay=900s timeout=1s period=15s #success=1 #failure=3
```

* `delay` specifies the time to wait after container got created before probing starts. 
* `period` specifies the time to wait before retry if first request was no success. 

So as the `delay` is 900s (15 mins) and adding 3x 15s of the `period`-time, it seems to fit to the restart cycle!

Also just checked the [node logs](https://console.cloud.google.com/logs/viewer?project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-07-06T08:41:48.030153000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-07-06T07:44:00.373Z&dateRangeEnd=2020-07-06T08:44:00.373Z&interval=PT1H&resource=k8s_node%2Flocation%2Feurope-west1-d%2Fcluster_name%2Fultratest&scrollTimestamp=2020-07-06T08:42:51.755566000Z&advancedFilter=resource.type%3D%22k8s_node%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0AjsonPayload.MESSAGE:%22Liveness%20probe%20for%20%5C%22zeebe-2_439e397a-b932-430a-8594-dac13c26b1c0-zeebe%22) and there we see as well a `liveness-probe` failures ~every 15 min!
![image](https://user-images.githubusercontent.com/55736962/86574370-05a58080-bf76-11ea-9033-a0dce3d355c7.png)

`Liveness probe for "zeebe-2_439e397a-b932-430a-8594-dac13c26b1c0-zeebe(6a1f1147-4a9f-44aa-b1d3-9e52c1ba6994):zeebe" failed (failure):`
 
So the restarts are triggered due to failed livenessprobes.

**Comment by hisImminence** [comment]
Would it help to increase the `delay` parameter for the liveness probe to not get restarted after 15 min?

**Comment by Zelldon** [comment]
Oh really :eyes:

**Comment by deepthidevaki** [comment]
Thanks. That's really helpful. :+1:

We know that there are cases where restart takes too long https://github.com/zeebe-io/zeebe/issues/3028 . So it would make sense to increase the delay until we resolve this issue.

**Comment by deepthidevaki** [comment]
@hisImminence It would also help us if you report and provide with data/logs etc. whenever you encounter such a situation where restart takes longer. That way we might be able to debug it faster.

**Comment by hisImminence** [comment]
Do u have any guess to how many seconds I should increase it?

**Comment by Zelldon** [comment]
I think removing would be better :sweat_smile:

**Comment by afirth** [comment]
Removing the delay will set it to 0 [the default](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes). Reading these tickets, my suggestion would be to debug the clusters which are currently crashlooping, rather than increasing it. Personally I would see a cluster which takes more than 15 mins to restart as "borked" from a customer perspective.

Currently, we can only edit this setting globally for all clusters from a configuration perspective, and I would like to see it go down, not up.

@hisImminence it's possible to disable the probe if needed for debugging by setting [`spec.controller.reconcileDisabled: true`](https://github.com/camunda-cloud/zeebe-controller-k8s/blob/master/README.md#turn-it-off), then editing the statefulset directly (probably to delete the probe altogether).

**Comment by hisImminence** [comment]
`12:03:00` removing liveness probe
`12:03:30` container created and `Running`

**Comment by deepthidevaki** [comment]
Closing as we found the reasons and created follow up issues.

**Comment by afirth** [comment]
#4876 
#4877 
#4887 
:100: thanks all!

**Comment by hisImminence** [comment]
@deepthidevaki or @Zelldon, I just rechecked the broker-2 and it is still not getting `Ready` with just disabling the `liveness-probe`. Do you have any other ideas to bring it back :hospital: ?

And as the follow up issues are created, I also have no feelings in deleting this cluster and create a new one if its not needed anymore for further investigations...

**Comment by hisImminence** [comment]
And do you want to keep the snapshots and the vm or can we remove them?

**Comment by deepthidevaki** [comment]
@hisImminence I will take a look at the cluster now. After that I can tell if you should keep it running.

**Comment by hisImminence** [comment]
> @hisImminence I will take a look at the cluster now. After that I can tell if you should keep it running.

awesome, thanks!

**Comment by deepthidevaki** [comment]
It seems the pod is still restarting every 15 minutes. Due to #4877 it takes > 15 minutes for the pod to be ready. So it can be ready only if it is left running longer. Is there anything else in your setup that force restart the pods? With the data you provided, my cluster was able to start when it was left running for > 20 min.

**Comment by hisImminence** [comment]
Okay cool! Thanks for the quick response. I will see what I can do!

**Comment by deepthidevaki** [comment]
Thanks. If you think it is still an issue with in zeebe brokers, I can take a look at again. Otherwise you can delete the snapshot and cluster.

**Comment by hisImminence** [comment]
@deepthidevaki, sry it took so long but just want to let you know that it worked and the cluster is up again :tada:!! Thx!
