### ISSUE TITLE
Distribute a deployment to all partitions of a topic

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#482]
AT:
* the deploy command is sent to the system topic 
* the command has a reference to the topic where it should be deployed
* if the command is valid the workflow command is distributed to all partitions of the given topic
* if the workflow is distributed to all partitions then the response is sent

**Comment by saig0** [comment]
**Protocol Change:**
* DEPLOYMENT_EVENT: add required property _topicName_ which specifies the topic to deploy to
* DEPLOYMENT_EVENT must be sent to SYSTEM_TOPIC

**Comment by menski** [comment]
*Note*: currently there are tests missing with multiple partitions. On review either add these test cases or create a followup issue.

**Comment by ThorbenLindhauer** [comment]
Review:

* `DeploymentState`: We can remove `DEPLOYMENT_` from the states to save some bytes on the log.
* A workflow `CREATE` request is always answered with created. This may be confusing for users, when the system broker sends `CREATE` twice due to backpressure. Then, the target partition contains `CREATE` and `CREATED` twice for the same workflow. Also, the second `CREATED` response can lead to a memory leak on the system broker (entry in pending workflows index). => The target partition should reject a workflow when it was already created before.
* `DeploymentCreateProcessor#readAndValidateWorkflows`: It should not be possible that the methods returns `true` (success) and sets an error message => improve the try-catch usage
* `ClusterManagerFragmentHandler`: Document the TODO on the protocol version check or remove it if it does not apply (we can have mixed-version brokers in an update scenario)
* `WorkflowVersions`: Must zero the unused portions of the key buffer when accessing the index, or else two index access interfere
* `WorkflowRequestMessageHandler`: Can use `DeferredCommandContext`

**Comment by ThorbenLindhauer** [comment]
I noticed one more thing: Since the system broker determines the workflow key and this becomes the event key on all the partitions this workflow is deployed to, keys are no longer uniquely identify an entity on a log. For example, there could now be a task that has the same key as a workflow. I think we should discuss this case, @saig0.

**Comment by saig0** [comment]
We discussed the topic but didn't decide something yet. There are arguments for both sides. We can open this topic later again when we are more confident about one way.
