### ISSUE TITLE
Reduce gossip timeouts to an appropriate value

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#4827]
**Description**

In our current swim implementation we send every second an ping requests to a random node. For each request we have a two second timeout configured. This means we will send already two new requests until the first one time out. This should be fixed with #4781 , but there we had the discussion whether we should reduce the swim timeouts. When we merge the referenced PR we will send only new pings when the timeout appears or we get an response, which might not ideal for long timeouts.

_More Context:_

[Comment by](https://github.com/zeebe-io/zeebe/pull/4781#discussion_r445354885) @deepthidevaki 
> The current impl is not ideal because it is scheduled at fixed rate. Doesn't sending the probe and immediately scheduling the next one already reduce that problem? I don't know clearly what will be the impact of both approaches (Any comments @saig0 ). If we wait for the timeout, I am afraid we increase the failure detection latency. Decreasing the timeout would probably help, but it might unnecessarily detect slow nodes as failed. That said, 2s timeout is too much. This timeout should be based on expected RTT in the network.
I'm ok with accepting this implementation and revisit this if we find any problem in future.

[Reply to that](https://github.com/zeebe-io/zeebe/pull/4781#discussion_r445365496)

![swim](https://user-images.githubusercontent.com/2758593/85676118-981c6900-b6c6-11ea-9c04-b231113ebcbf.png)
Extract from http://www.cs.cornell.edu/info/projects/spinglass/public_pdfs/swim.pdf page 4. So yes it should be smaller then the ping interval.

Example how it is done on other implementations 

* Hashicorp uses 500 ms timeout https://github.com/hashicorp/memberlist/blob/master/config.go#L288 
* scalecube uses 100ms https://github.com/scalecube/scalecube-cluster

**Comment by npepinpe** [comment]
It's unclear to me what the gain here is, so it's unclear how to prioritize this. Can we calculate the following for the current defaults and the proposed values:

1. Upper bound for failure detection in a 3 node cluster
1. Length of network partition we can tolerate 

And any other pros/cons to help me understand how to prioritize this :sweat_smile:

**Comment by npepinpe** [comment]
As discussed, time box it to one afternoon, and let's provide recommended defaults which make sense (i.e. timeout is not greater than probe interval, assumed RTT is ~100ms), and also let's provide values for our own production environment (you can open an issue on the controller side, and if you have time a PR as well).

**Comment by deepthidevaki** [comment]
Measuring probe latency on our benchmark clusters shows the probe latency is under 50ms.
![image](https://user-images.githubusercontent.com/1997478/101486287-b4525080-395c-11eb-93e8-aeb7e482f026.png)

Hence for probe timeouts, I would recommend 100ms which I think is large enough for any LAN deployments. Probe interval is recommended to be at least as big as 3 times probe timeout. Hence the current default of 1s looks good.

ZEEBE_BROKER_CLUSTER_MEMBERSHIP_PROBEINTERVAL=1s
ZEEBE_BROKER_CLUSTER_MEMBERSHIP_PROBETIMEOUT=100ms

With these values now, after a probe request is send to dead node, the node can be marked as suspect after 2*100ms. 
After a node is marked as suspect, the node is marked as dead after ZEEBE_BROKER_CLUSTER_MEMBERSHIP_FAILURETIMEOUT. The default value for failure timeout is currently 10s. We can discuss if we want to reduce this value as well. Note that raft leader elections are not affected by swim failure detection because raft heartbeat time and election timeouts are generally lower than expected failure detection time via swim.

Faster failure detection may be important for gateway. If gateway can detect that the leader is dead faster before a new leader is elected, it can redirect (some) requests to other partitions which have leaders. For that reason, it might also make sense to tune the probeInterval, probeTimeout and failureTimeout differently on the standalone gateway.

#### Summary
We can update the following default values. while keeping others.
ZEEBE_BROKER_CLUSTER_MEMBERSHIP_PROBETIMEOUT=100ms
ZEEBE_GATEWAY_CLUSTER_MEMBERSHIP_PROBETIMEOUT=100ms

@npepinpe ptal

**Comment by npepinpe** [comment]
Great work! Is this a metric we already have, and if not, can we add it? :smiley: 

How does the gateway behave at the moment w.r.t. suspect vs dead? As far as I know, it routes requests based on the topology, so it's still indirectly mostly affected by Raft elections. If a node is suspect (but not dead), then it will still take 10 seconds for it to stop routing requests to it. What would block us from recommending a failure timeout as well?

Regarding Raft timers - I understand that right now Raft is unaffected because our failure timeout is so high. But if it were lower, it would be, correct? Very naively, why would we not set a lower failure timeout than the Raft heartbeat timeout? Or is our gossip implementation completely decoupled from the Raft part?

**Comment by deepthidevaki** [comment]
> Great work! Is this a metric we already have, and if not, can we add it? smiley 

No. It is a new metric. Do you think it is useful to add it permanently?

> Also, how large was the cluster with which you tested? Would cluster size have an impact on this (assuming we don't run into network saturation)?

Cluster size 3 + 1 gateway. Cluster size should not impact probe timeout as it is just influenced by how fast the other node responds.

> How does the gateway behave at the moment w.r.t. suspect vs dead? 


At the moment, gateway (as well as broker) does not react to nodes detected as suspect. 

> As far as I know, it routes requests based on the topology, so it's still indirectly mostly affected by Raft elections. If a node is suspect (but not dead), then it will still take 10 seconds for it to stop routing requests to it.

Yes. Gateway routes request based on the topology. But if there is no leader for a partition, gateway has the logic to re-route the request to a different partition. So requests such as ActivateJobs are then immediately send to the next partition instead of waiting for a timeout. So if the gateway can detect that the leader is dead faster than the election time, it would be good. That's why I said while faster failure detection may not be beneficial for brokers, it may be useful for gateway. So it might be good to set a smaller failure timeout and small probe intervals.

>  What would block us from recommending a failure timeout as well?

We don't have any metrics right now to evaluate if the new recommended values have any observable impact.

> 
> Regarding Raft timers - I understand that right now Raft is unaffected because our failure timeout is so high. But if it were lower, it would be, correct? Very naively, why would we not set a lower failure timeout than the Raft heartbeat timeout? Or is our gossip implementation completely decoupled from the Raft part?

That is something that I have thought about too. But then I ask myself why not just tune raft timeouts? I don't know if it is better to use swim failure detection in raft (we already react to membership changes in raft).

> Very naively, why would we not set a lower failure timeout than the Raft heartbeat timeout?

One reason for higher failure timeouts is to avoid false positives. So we have to be careful when lowering it.
Also failure detection time is affected not just by the failure timeout. 
According to the paper 

![image](https://user-images.githubusercontent.com/1997478/101498100-02228500-396c-11eb-8c8a-cbd5d43df739.png)

the expected time until the failure of a member is detected by some other member = ~ probeInterval * 2 (a naive approximation)
This is the expected time when a node is detected as suspect. This is the expected time, not upper bound. So to mark a node as dead it would take probeInterval * 2 + failure timeout. Then it needs additional time to get propagated to other nodes which is influenced by other gossip parameters. It would be interesting to see if we can find values for all these which results in a failure detection time faster than the raft election time out in most cases, even if we can't upper bound it.

**Comment by npepinpe** [comment]
> No. It is a new metric. Do you think it is useful to add it permanently?

I think it's a useful metric if anyone wants to tune their gossip. We can create a new issue to add gossip metrics in general, no need to do this now. Although it could be useful to have in production so we can make sure the value we set is correct. I'm fine with either - you can create a PR with what you have and assign it to me for review, or create an issue to add gossip metrics and put it for triage.

> We don't have any metrics right now to evaluate if the new recommended values have any observable impact.

True, however 10 seconds seems high enough we could probably comfortably recommend a lower value, no? So we mark a node as suspect in about 200ms, but take an additional 10 second to mark it as dead? :sweat_smile: Seems disproportionate. At any rate, all this makes it sound like we first need to add metrics so we can later tune these values.

> But then I ask myself why not just tune raft timeouts? I don't know if it is better to use swim failure detection in raft (we already react to membership changes in raft).

Good point. I see we already having metrics on the heartbeart - do you think we need others, and if so, which?

Anyway, regarding the issue itself - I would propose to open a new issue to add gossip metrics (if possible please list the useful ones, but it's OK to do that when we start it), and to set the values you proposed here as the new defaults.
