### ISSUE TITLE
zbctl status should show health status

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#4853]
**Is your feature request related to a problem? Please describe.**
I think it makes sense when zbctl status actually shows the health status of each of the partitions. When there is some problem with zeebe, zbctl status could be a quick check for a developer to make sure its up and running.

**Describe the solution you'd like**
`zbctl status` prints something like:
```
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 0.23.3
Brokers:
  Broker 0 - 0.0.0.0:26501
    Version: 0.23.3
    Partition 1 : Leader, Healthy
```

or
```
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 0.23.3
Brokers:
  Broker 0 - 0.0.0.0:26501
    Version: 0.23.3
    Partition 1 : Leader, Unhealthy (reason: we could even add the context discussed in #4845)
```

**Describe alternatives you've considered**
The current way to find out that zeebe is operating correctly is checking logs, the metrics or the grafana dashboard. All of these have their own pros/cons. I still think it makes sense, from a user's perspective, to add the health status of partitions to zbctl.

**Additional context**
Currently `zbctl status` prints something like:
```
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 0.23.3
Brokers:
  Broker 0 - 0.0.0.0:26501
    Version: 0.23.3
    Partition 1 : Leader
```

**Comment by aivinog1** [comment]
@korthout @npepinpe Hi! I think I can take this issue, what do you think?

**Comment by korthout** [comment]
@aivinog1 This is a bit more difficult than I initially thought. `zbctl status` asks the gateway for this info, but it does not pass this request to each of the brokers. Instead, the gateway already knows the answer for this request. However, the partition health is currently only known in the broker and not in the gateway. Which means that either the broker needs to inform the gateway of changes to the health of its partitions (adding complexity to the health system), or the gateway needs to pass along this part of the request to all brokers (which adds time to the request). 

@npepinpe have you thought about this problem before? Do you see any other solutions or do you perhaps have a preferred solution?

**Comment by npepinpe** [comment]
We could always propagate the partition health as part of the broker info which is gossiped to all nodes. I think that's what we do with the version, for example, that you see in the status. I also expect health to not be changed too often so gossip should be OK to propagate this kind of information. wdyt?

**Comment by korthout** [comment]
Agreed. This is the more elegant solution. In the future the gateway might actually use that info for more advanced routing behaviour, right?

**Comment by aivinog1** [comment]
@npepinpe @korthout Hi! So should brokers propagate a health status to gateways? This solution is approved? :)

**Comment by korthout** [comment]
@aivinog1 Yes! This solution seems good to us. 👍 

I'd like to note that this is a relatively large change, in which changes to the broker, the gateway and the client(s) are needed. Please keep PRs small and changes to these parts separated if possible. Also note that, we're here to help so please feel free to ask all the questions you have. It might be useful to join our [Slack](https://zeebe-slack-invite.herokuapp.com/) which should get you some quicker replies. 

Please let me know if you're still interested in taking this issue.

**Comment by aivinog1** [comment]
@korthout Sure, I'm in :) There is a separate channel where I can ask questions about this issue or I can just use `#general`?

**Comment by korthout** [comment]
@aivinog1 Most people just use `#general` to ask there questions, but also feel free to DM me or @npepinpe 👍

**Comment by Zelldon** [comment]
@deepthidevaki had some concerns about overloading gossip or sending to much stuff over gossip maybe you can discuss it with her before starting.

**Comment by aivinog1** [comment]
@Zelldon Thanks :) I'll discuss it with @deepthidevaki. For now, I'll do other tasks and want to leave this task for last :)

**Comment by deepthidevaki** [comment]
Our current gossip implementation is intended for small state. It sends the entire properties with each gossip message, even if nothing has changed. So that's why I think we should think before adding any new property to it. However, I think the current properties are still only a few bytes. I haven't measured it though (Has any one measured it?) So we probably don't need to worry about it now. Also adding health status to the gossip properties make sense to me, because it is only a small data.

**Comment by aivinog1** [comment]
@deepthidevaki Thanks!

**Comment by aivinog1** [comment]
@korthout @npepinpe To keep you informed about this one: unfortunately, the next two weeks will be harsh for me (my teammate on my work goes to the vacation), so I can't promise that this issue will be done (or even I will touch some code). So if this issue expects to be done with some due date - fill free to assign it to someone else ✌️

**Comment by korthout** [comment]
@aivinog1 The issue has been marked as `Prio: Low`, which means that at the moment it is not tied to a specific future release. So, please don't worry about it. We're very happy to receive your contributions on it whenever you see fit. ❤️

**Comment by aivinog1** [comment]
@korthout Hi, can you help me with how to split this task into small pieces that? I'm thinking about several approaches:
1. Start with the client (`zbctl`). Set a mock of the health value from the gateway, then mocking the health from the broker in the gateway after that implements logic about passing health from a broker. So there will be 3 PRs to implement this.
Advantages: 
- for me is very clear what shape of the data needs to be passing in every step
- if `zbctl` users don't satisfy the output of the command it's much easier to reimplement this before doing the logic in the gateway and the broker.
Disadvantages:
- In earlier steps, it will show mock data that probably isn't the best solution for Zeebe end users, if you are okay with it - this is could not be a disadvantage. If you are not okay there be some pitfalls or too overcomplicated solutions to me 😅.
2. Start with the broker. So, after the first PRs will be merged users don't get this feature. Then I will implement a gateway's part, after that, I will implement a client's part. So there will be 3 PR's to implement this.
Advantages:
- users don't get mocked data at all
Disadvantages:
- for me, it is complicated to design from bottom-up because I don't know all the possible pitfalls and traits of the project
- If I will fail to right implement this and we found out that in the client part - it will be not good at all 😔
3. Start with the gateway. In the first, I'll design a gateway API, then will implement a broker with gateway internals then will implement a client. So there still will be 3 PR's to implement this.
Advantages:
- users don't get mocked data via `zbctl`
- it will be much easier for me to start with API.
Disadvantages:
- Less chances, but there still may be situation where I need to redesign API to improve a client part.

So what do I need to choose or what can you provide additionally? :) Maybe we need to decompose this issue into the small issues?

**Comment by korthout** [comment]
Hi @aivinog1, great to see you've started on this topic (and welcome back of course).

It would actually be possible in a single PR (Zeebe is a mono repo after all), but I don't prefer that because large PRs are difficult for both the author and the reviewer. So, I totally agree that we should split up the issue into smaller chunks and it would be great to have separate issues for each. 

Having said that, my personal preference goes out to the second option that you described. I see value in the setting the pieces in place before adding the final touches to make them available to users. I'd like to add that the gateway should then log a small message when it receives from the broker the health of 1 of the partitions. This way, when we merge just that PR we already add value: we can now find in the logs what the gateway knows about the health of the partitions on each of the brokers. Even if no-ones comes around to implement the other PRs in this issue, we might be able to make use of that information in other ways.

To implement this, you'll need to use gossip to inform the gateway of the partition health. Start by adding additional info to the membership gossip protocol. Add an additional map from partition to health here: https://github.com/zeebe-io/zeebe/blob/develop/protocol-impl/src/main/java/io/zeebe/protocol/impl/encoding/BrokerInfo.java#L67 and make sure it get's wrapped and written correctly. Just have a look at how this class deals with its `partitionRoles` field. This will need to be updated in the sb definition of the gossip protocol: https://github.com/zeebe-io/zeebe/blob/develop/protocol/src/main/resources/protocol.xml#L112. Remember to add a `sinceVersion` attribute and update the protocol version in the pom here: https://github.com/zeebe-io/zeebe/blob/develop/protocol/pom.xml#L28. And where the gateway receives it: https://github.com/zeebe-io/zeebe/blob/develop/gateway/src/main/java/io/zeebe/gateway/impl/broker/cluster/BrokerTopologyManagerImpl.java#L120.

The next step is changing how the gateway the responds to a Topology command (RPC). This starts with changing what the response can be, but also requires an implementation change. The response definition can be found here: https://github.com/zeebe-io/zeebe/blob/develop/gateway-protocol/src/main/proto/gateway.proto#L244. You'll likely need to make your change in https://github.com/zeebe-io/zeebe/blob/develop/gateway-protocol/src/main/proto/gateway.proto#L270.
The implementation is found in https://github.com/zeebe-io/zeebe/blob/develop/gateway/src/main/java/io/zeebe/gateway/EndpointManager.java#L245. You'll probably need to change it in https://github.com/zeebe-io/zeebe/blob/develop/gateway/src/main/java/io/zeebe/gateway/EndpointManager.java#L93.

As a last step, you need to change the client's implementation of what to do with the Topology response. For the go client see: https://github.com/zeebe-io/zeebe/blob/develop/clients/go/cmd/zbctl/internal/commands/status.go#L47 and https://github.com/zeebe-io/zeebe/blob/develop/clients/go/cmd/zbctl/internal/commands/status.go#L83. And for the java client see: https://github.com/zeebe-io/zeebe/blob/develop/clients/java/src/main/java/io/zeebe/client/impl/response/BrokerInfoImpl.java#L93.

I believe this is a difficult issue to work on with many changes, but it will provide an overview of how the client gateway and broker communicate to each other. Please split the issue in the 3 parts discussed above. Likely the most difficult change is the first part (using gossip to inform the gateway of the partition health). If you have any questions, don't hesitate to ask and I hope you have fun implementing these changes.

**Comment by aivinog1** [comment]
@korthout Hi, many thanks for such a detailed explanation! :)
