### ISSUE TITLE
Remove ZeebeRaftStateMachine

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe#4914]
**Description**

A state machine in a raft is generally used to build the state by applying committed events. We built the state differently via stream processors. So it is not necessary to have a different state machine. The current state machine reads and applies every entry that is committed. Here applying is only used to notify commit listeners.

**Problems with current approach**

- On restart, it has to apply all events in the log. This leads to
   - Longer restart time (#4158)
   - Out of memory when log is too large (#4871) (We can fix OOM due to this independently of this issue)
- On normal run, it might have an impact on performance as it has to re-read the entries (on followers).

**Proposal**

We can remove the state machine and the need for "apply"ing the entries. The commit listener is only used by the logstream to update the commit position. Commit notification can be done by the `LeaderRole` when an entry is committed. No need to wait for applying. 

**Cons**
On follower it cannot get notified for each entry individually. As a consequence, it is not possible to update the commit position in logstream reliable. We, currently,  do not update and use the commit position on followers. So this is not an issue now. But it can cause problems in future, if we ever want to use this on the followers.

**Comment by npepinpe** [comment]
Is the log already scanned before applying?

Also, I'm not sure if this is even a problem on the followers, except if we want to do something like described [here](https://github.com/zeebe-io/zeebe/issues/4694), where the commit listener passes on the event and it's used directly to build state instead of reading it from the log.

But I wouldn't consider it a blocker - it makes 100% sense for me to do the reading only once (in the stream proc), and if we want a way to hand over events as they are replicated directly to the follower I think we can still find a way to achieve that.

**Comment by deepthidevaki** [comment]
> Is the log already scanned before applying?

The log is scanned multiple times during restart:
 1. During raft partition start, by the journal to build index.
 2. During the apply phase, each entry is read (again) and applied, one after the other.
 3. If it is the leader, it will be read again for reprocessing.

During normal run, when commit index is updated the entry is read from the log before applying.

**Comment by npepinpe** [comment]
Sorry, I guess I wasn't clear enough - I asked to know if removing this would remove building the index, but I see it doesn't :+1:
