### ISSUE TITLE
Release candidate load test fails after 2 days

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#5136]
**Describe the bug**

The 0.23.5 RC1 load test failed over the weekend as one broker ran out of disk space - it's unclear why since the others have very low disk space usage, and needs to be investigated to know if this is a pre-existing bug (which should be fixed for 0.23.6) or one introduced in this version (which shouldn't be released until fixed), or an environmental factor (e.g. misconfiguration).

**Expected behavior**

Disk usage should be roughly similar on all brokers assuming things are going smoothly.

**Environment:**
 - OS: Docker distribution
 - Zeebe Version: 0.23.5 RC1
 - Configuration: benchmark config

**Comment by deepthidevaki** [comment]
This is what we observed:
1. Zeebe-2 was leader for partition 1
2. Due to a heartbeat miss, there was a leader election, Zeebe-2 transition to follower
3. Due to asynchronous closing of leader services in raft and Zeebe, LogStorageAppender append fails because LeaderRole is already closed. 
4. LogStorageAppender detects it as a failure and as a result logStream closes.
5. AsyncSnapshotDirector tries to take a snapshot while closing, but it fails because logStream is closed
6. On ZeebePartition transitionToFollower fails, because closing of AsyncSnapshotDirector failed.
7.  As a result Follower services are never installed and zeebe-2 never receives snapshots for partition 1

cc @MiguelPires

**Comment by npepinpe** [comment]
Ah, so this is actually a duplicate of https://github.com/zeebe-io/zeebe/issues/5117 ?

**Comment by deepthidevaki** [comment]
Yes

**Comment by deepthidevaki** [comment]
Also I think it does not happen in 0.24 because we removed taking snaphot during close.

**Comment by npepinpe** [comment]
So essentially this isn't an issue introduced by 0.23.5? :+1:

**Comment by deepthidevaki** [comment]
Ya. It was already there.

**Comment by deepthidevaki** [comment]
We can fix this either by
1. Not taking snapshot during close (backport PR from 0.24)
2. It is also arguable if we should close LogStream when there are failures detected by LogStorageAppender. This affects the order of closing dependencies. Normally Logstream is closed last. But in this case LogStream is closed before others causing AsyncSnapshotDirector to fail. So when LogStorageAppender detects failures we should close logStorageAppender. LogStream only marks itself as unhealthy, but don't close itself.

**Comment by npepinpe** [comment]
Does it make sense to fail to install the follower services because we failed to uninstall the leader services?

**Comment by deepthidevaki** [comment]
It is safe to not install follower services. Otherwise there might be both leader services and follower services running side-by-side.

**Comment by npepinpe** [comment]
I would close this in favor of the other issue then :+1:
