### ISSUE TITLE
Support preventing duplicate deployment of workflow by introducing a digest value

### ISSUE THREAD

**Issue by cameronbraid** [zeebe-io/zeebe#5144]
**Is your feature request related to a problem? Please describe.**

Currently when using spring-zeebe whenever my application restarts a new version of my workflow is deployed even if the bpmn file has not changed.

The same thing happens from zbcli with repeated calls with the same file.

**Describe the solution you'd like**

The zeebe broker can introduce a new digest value to be stored internally alongside deployed workflows.
The GRPC api can add a new optional field to provide this value within the deploy workflow call.
When the digest is provided -  the broker first checks if there is an existing deployed workflow that has the same digest value and avoids creating a new version.

API clients can use a hash function based on what they consider to be a changed bpmn file.  A simplistic version may just do a sha1 of the bytes. 

**Describe alternatives you've considered**

Us an exporter to maintain a database of deployed workflow digests and do a digest lookup API call prior to the deploy workflow call.  This requires a much more complex environment when setting up zeebe, and would then require any client that deploys a workflow to use this new API when deploying.

**Comment by MiguelPires** [comment]
Hi @cameronbraid, thanks for opening this issue. This feature has already been implemented (#1159), so the broker shouldn't be deploying a new workflow every time. I have a few questions that would help clarify why it's not working for you. Are you always using the same resource name between deployments or does it change? After you deploy the workflow, is the version in the response always the same or does it increment with each deployment?

**Comment by cameronbraid** [comment]
A new duplicate deployment can happen when deploying with zbctl first, then deploying the same bpmn file using spring-zeebe (or vice versa)

**Comment by cameronbraid** [comment]
zbctl 0.24.1 (commit: e3a39d28)

**Comment by cameronbraid** [comment]
<dependency>
      <groupId>io.zeebe</groupId>
      <artifactId>zeebe-client-java</artifactId>
      <version>0.24.1</version>
    </dependency>
    <dependency>
      <groupId>io.zeebe</groupId>
      <artifactId>zeebe-test</artifactId>
      <version>0.24.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.zeebe</groupId>
      <artifactId>zeebe-test-container</artifactId>
      <version>0.33.0</version>
      <scope>test</scope>
		</dependency>
		
		
		<dependency>
			<groupId>io.zeebe.spring</groupId>
			<artifactId>spring-zeebe-starter</artifactId>
			<version>0.23.0</version>
		</dependency>

**Comment by MiguelPires** [comment]
So the issue occurs when alternating calls between the Java client and `zbctl`. I think this is probably because `zbctl` uses the workflow path as the resource name, while the Java client supports different ways of passing a workflow and the resource name depends on it. This is probably why it differs between calls. A possible workaround would to run `zbctl` from a different directory to match the resource name (e.g., if you're using `.addResourceFromClasspath`, running `zbctl` from the directory where the bpmn is). Can you confirm this workaround works for you @cameronbraid? 
@npepinpe a better way of dealing with this would be adding an optional `--resourceName` parameter to `zbctl deploy` which would set it explictly, wdyt?

**Comment by npepinpe** [comment]
Sounds good to me :+1:
