### ISSUE TITLE
Add quick start guide using zbctl to docs

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#526]
Add a quick start to the [introduction section](https://docs.zeebe.io/introduction/README.html), which explains some simple operations using zbctl. It could be similar to the [kafka quick start guide](https://kafka.apache.org/quickstart).

**Comment by menski** [comment]
Hi @ThorbenLindhauer, I would like to get some feedback from you about the guide. Also it would be interesting how much we have to change to make it work under Windows. Currently you need a patched version of `zbctl` for this guide, which you can find on the branch https://github.com/zeebe-io/zbctl/tree/quickstart. Let me know if you need help to build it locally.

**Comment by menski** [comment]
@ThorbenLindhauer I build the latest snapshot with the patched zbctl for you to test the quickstart guide
[zeebe-distribution-0.8.0-SNAPSHOT.zip](https://github.com/zeebe-io/zeebe/files/1870939/zeebe-distribution-0.8.0-SNAPSHOT.zip)

**Comment by ThorbenLindhauer** [comment]
Review hints:

* I like the contents, structure and brevity of the guide
* Sooner or later the guide should work on Windows. See findings below.

I tried the guide with both cmd and Powershell 2 on Windows 7. 

`./bin/zbctl --topic quickstart create task step4 --payload '{"zeebe": 2018}'`: Does not work on either cmd or powershell due to the payload quoting syntax. On cmd, the payload must be written as `"{\"zeebe\": 2018}"`. On powershell, the payload must be written as `'{"\"zeebe"\": 2018}'` (see https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments on the powershell issue).

`./bin/zbctl --topic quickstart subscribe task --taskType step4 cat` does not work on `cmd` because of no `cat`. Works fine in Powershell.

Maybe the solution is to ask people to use git bash or cygwin where the above problems do probably not exist.
