### ISSUE TITLE
Metrics exposing the state of exporters

### ISSUE THREAD

**Issue by strawhat5** [zeebe-io/zeebe#5359]
**Is your feature request related to a problem? Please describe.**
We do not have a way (other than browsing through the broker logs) to identify whether an exporter inside Zeebe is in an OPEN state or CLOSED state.

**Describe the solution you'd like**
It would be good to have a metric which exposes the current state of all exporters, and also when did the state change.

**Describe alternatives you've considered**
We have a "_Stream processor vs Exporter_" metric, but it does not provide sufficient info about all configured exporters.

**Comment by strawhat5** [comment]
As @Zelldon suggested #5256 mostly covers our use-case. So this issue remains more like a health check for all the exporters. I would leave it upto the maintainers to implement a health check metric or close it in favor of #5256.

**Comment by npepinpe** [comment]
Yeah, I thought a bit more about it, and I think the best would be for exporters to be able to add their own metrics, actually. In the Kafka example you posted, the exporter goes into a internal closed state, but from the Zeebe point of view it's still "open", so it wouldn't help - however it'd still be good for the exporter to report its status. EIther way, yeah, this issue is probably not the right one for it. If you're fine, then I'll close it. Let me know otherwise.
