### ISSUE TITLE
Node is no longer leader for partition ...

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe#5543]
**Describe the bug**
Observed as errors in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CN72pr-lkObnSQ?service=zeebe&time=P7D&project=camunda-cloud-240911

Report location lambda$sendResponse$5 (AtomixServerTransport.java:139)   

**Environment:**
Camunda Cloud / Prod / 0.23.4, 0.24.2, 0.24.3

**Comment by pihme** [comment]
- Happened during broker restart
- It looks like the broker was able to restart despite the error

https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22excitingdev%22%0Aresource.labels.namespace_name%3D%2259d17aad-3cb7-4c0e-8ce2-73f5d188e147-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aseverity!%3DDEBUG%0Aresource.labels.pod_name%3D%22zeebe-0%22;timeRange=2020-11-10T21:52:42.745Z%2F2020-11-10T22:52:42.745Z;summaryFields=labels%252F%2522k8s-pod%252Fstatefulset_kubernetes_io%252Fpod-name%2522:false:32:beginning?project=camunda-cloud-240911

**Comment by Zelldon** [comment]
I think @pihme your comment should be on a different issue? Because the log you have posted shows 

```
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: `
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804) ~[kryo-4.0.2.jar:?]
	at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:267) ~[atomix-utils-0.24.3.jar:0.24.3]
	at io.atomix.storage.journal.FileChannelJournalSegmentWriter.reset(FileChannelJournalSegmentWriter.java:209) ~[atomix-storage-0.24.3.jar:0.24.3]
	at io.atomix.storage.journal.FileChannelJournalSegmentWriter.<init>(FileChannelJournalSegmentWriter.java:7
```

**Comment by Zelldon** [comment]
I checked the log and I think this is a potential race condition. This error can happen in two cases, either the partition was shutdown again during reprocessing and on processing the processor wanted to send a response, when he is no longer leader. Not 100% sure whether this can happen, because I think the actor is closed on shutting down the partition.

What I saw in the [logs](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-10T22:22:42.745000000Z&dateRangeStart=2020-11-10T21:22:42.745Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22excitingdev%22%0Aresource.labels.namespace_name%3D%2259d17aad-3cb7-4c0e-8ce2-73f5d188e147-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.context.loggerName!%3D%22io.zeebe.logstreams.snapshot%22&interval=JUMP_TO_TIME&pinnedLogId=jz8kzkg2f4c5rk&pinnedLogTimestamp=2020-11-10T22:22:12.745704Z&scrollTimestamp=2020-11-10T22:22:12.762112000Z) what can happen is that if the reprocessing is really fast that it is faster then subscribing to the partition topic, which means I is not able to send the response back.

In the `CommandApiService` we register for the partition topic `onBecomingLeader`, this call back is called if the partition installation is done.

**Comment by npepinpe** [comment]
Please verify if we are losing responses that would make it to the client, or if these responses were already written by another leader and therefore couldn't be sent anyway.

**Comment by npepinpe** [comment]
@Zelldon verified that we are not writing new commands until the subscription takes place, so we aren't losing responses - we fail to respond for commands which were written before the new leader was elected, which is the expected case.

**Comment by npepinpe** [comment]
So this is mostly about lowering the log level since this is expected and not an error, and this was already done in https://github.com/zeebe-io/zeebe/pull/5448
