### ISSUE TITLE
OAuth Token Refreshment in Go Client

### ISSUE THREAD

**Issue by zeromberto** [zeebe-io/zeebe#5625]
**Describe the bug**
The go client does not automatically refresh the oauth2 token when it expires. The token refreshment is currently triggered in `OAuthCredentialsProvider.ShouldRetryRequest`. Since this method never gets executed during the client usage in the job poller the client never gets a refrehed token and all subsequent requests fail.

**To Reproduce**
- Create new client with OAuth
- Create a new JobWorker
- Run JobWorker until initially provided token expires

**Expected behavior**
The token shall be refreshed regardless of any checks for request retry.

**Environment:**
 - Zeebe Version: 0.24.4

**Comment by MiguelPires** [comment]
@npepinpe we can leave it as it's already closed but https://github.com/zeebe-io/zeebe/pull/5630 didn't address the source of this bug. The issue is here https://github.com/zeebe-io/zeebe/blob/460fe55c83c5120d42763bff260f063afcef40a2/clients/go/pkg/worker/jobPoller.go#L80 and here https://github.com/zeebe-io/zeebe/blob/460fe55c83c5120d42763bff260f063afcef40a2/clients/go/pkg/worker/jobPoller.go#L87 the errors aren't checked for an UNAUTHENTICATED code and there's no retry based on it. 

It's fine to check the validity of the token before the call since it probably prevents a round-trip if the token expired. However, the correct fix would be to have the worker react to the error code just like the other operations do. If this was any operation other than the worker, the bug would still be here since the token could expire in-transit and we wouldn't retry. However, the worker already retries by design so the user will just see the UNAUTHENTICATED error being logged and the token will be refreshed whenever it tries to activate jobs again

**Comment by amuino** [comment]
By @MiguelPires comments, should this issue be reopened?
