### ISSUE TITLE
Storing Positions as Key has terrible distribution in ZbMap  as consequence

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#576]
Situation: 

Currently we align each logged event with a number, which can be divided by 8. This means the position of the logged event is also dividable by 8. In the most StreamProcessor we use the logged event positions as key to store some specific data. 

Problem:

This means when we put an new entry it will happen very often that the bucket is already full and an overflow appears (which means split is executed and also the hash table is increased if the bucket id reaches the limit OR we use bucket overflow). This is a problem since only a part (1/ 8) of all possible buckets are filled/used. 

Example:
We put 0, 8, 16, 24 in a Map which as maxBlockCount 1, we will end in a Map which has as HashTable size 32. If we put as next key 32 we have to increase the hashtable. As you can see we could store 32 entries, but since our keys are dividable by 8 we can only store 4 key-value pairs.

*Update Note*: I know that the position consist of two integers (segment id and segment offset), but it shows the same pattern.

**Comment by Zelldon** [comment]
Tried some hash functions and wrote a test case which checks the hash table growing behavior  after adding 10_000_000 entries (https://github.com/zeebe-io/zb-util/commit/66bbf749fd2ccbb1bb6bb0f61dd62abf4d07660e).  

Depending on the position characteristics and with help of a bit testing, I found a calculation which seems OK for now. We should keep in mind that we can possibly improve the hash function.

I disable also the overflow buckets before the max hash table size is reached. This means we will as first tried to split buckets and increase the hash table and distribute the entries in the buckets. If we reach the maximum we will use overflow buckets. Before that the overflow buckets slowed down the system.

Tested the hash function with the LargeWorkflowTest case the entries distribute muuch better. The hash table of the activityInstanceMap for example has in the end only a size of 
262144 and no overflows. Improves the performance also quite a lot (on workflow throughput test seems to be 30% more throughput). 
Test for https://github.com/zeebe-io/zeebe/issues/447 with 1 million workflow instances runs in ca 4 min.

**Comment by meyerdan** [comment]
1 million synchronous, one after the other, in 4 min? That's 200 microseconds (or 0.2 milliseconds) per workflow instance. 🥇

**Comment by Zelldon** [comment]
Yeah right :) Had rerun the test in 3 min's :smile:

**Comment by ThorbenLindhauer** [comment]
Review:

* I didn't review the quality of the hash function with respect to the data.
* Adapt the sites where `KeyHandler#keyHashCode` is called. They still work with `long` instead of `int`.
* `LongKeyHandler#positionAsKeyProducer` does a lot of things that are not used in the test (e.g. computing hash code, incrementing the segment id). Try to reduce the test case as much as possible.
* It would be nice to have a test/benchmark kind of thing that runs a large volume of workflow instances and then plots the hash code distribution for all involved zb maps. That would allow us to understand the impact of the hash function even better and allows use to easily compare different hash functions. If you find this useful as well, feel free to raise a follow-up issue.

**Comment by Zelldon** [comment]
Yeah had the same thing in mind but was not sure how.

**Comment by Zelldon** [comment]
Ran today some tests with creation of 100_000 workflow instances and printing all generated hash codes into a file. I show the file content in a diagram. It seems the current ''new'' hash function does not have so good distribution, but in the Test it works well for the hash table growing.
I had some other choices, as hash functions, which behaves really good in the distribution and also in the large Test I made before. 

### Old function:

```java
Long.hashCode(theKey); //  return (int)(value ^ (value >>> 32));
```
![hasholdfunction](https://user-images.githubusercontent.com/2758593/33772137-e016aad8-dc33-11e7-9aab-c7293b53305d.png)

### The current (new) function:

```java
(int) (theKey ^ ((theKey >>> 32) ^ ((theKey >>> 8) ^ ((theKey >> 3)))));
```
![hashwithnewfunc](https://user-images.githubusercontent.com/2758593/33772170-0cb6a304-dc34-11e7-82b9-8a5a2d4de5db.png)

### Other good hash function
```java
        long x = theKey;
        x = ((x >>> 16) ^ x) * 0x45d9f3b; // 4 mio
        x = ((x >>> 16) ^ x) * 0x45d9f3b;
        x = (x >>> 16) ^ x;
       return (int) x;
```
![hashcode1func](https://user-images.githubusercontent.com/2758593/33772215-33357fd2-dc34-11e7-924e-a7f12ab6feb5.png)

### Second other good hash function
```java
       x = (x ^ (x >>> 30)) * (0xbf58476d1ce4e5b9L); // 4 mio
       x = (x ^ (x >>> 27)) * (0x94d049bb133111ebL);
       x = x ^ (x >>> 31);
        return (int) x;
```
![hashcode2func](https://user-images.githubusercontent.com/2758593/33772275-6201db62-dc34-11e7-8095-0be7c42b5ee6.png)



@ThorbenLindhauer perhaps we can talk about your benchmark idea?

**Comment by meyerdan** [comment]
My thoughts on this:

* The keys of the events are generated from the positions in the zeebe-io/dispatcher (log buffer). The position is a long such that the first 32 bits represent the patition id and the next 32 bits the offset withing the partition. This results in a strong characteristic in the values generated, paticulary when a benchmark creates events of the same size over and over again.
* When looking for a hash function, we need to select something which works against this characteristic and "spreads" the values out. 
* We should not only look into the hash function itself but also into alternatives for generating the keys. I have some thougts on this which we can discuss F2F

@menski you need let us know whether we should pursue this further right now or postpone and focus on other topics

**Comment by menski** [comment]
@Zelldon for now I think it is enough to finish the following review hints from Thorben:
- Adapt the sites where KeyHandler#keyHashCode is called. They still work with long instead of int.
- LongKeyHandler#positionAsKeyProducer does a lot of things that are not used in the test (e.g. computing hash code, incrementing the segment id). Try to reduce the test case as much as possible.

Other than that if we have evidence from kind of real world data that our hash function is suboptimal we should takle that issue focused. At the moment I think we can stick we the current implementation or the old one, that's up to you. But I would not invest more time into writing benchmarks or testing until we see an issue. Please approach me if you want to discuss this.
