### ISSUE TITLE
Do not retry on rejection during job activation

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5812]
**Describe the bug**

_Was part of a [chaos day](https://github.com/zeebe-io/zeebe-chaos/tree/master/chaos-days/2020-11-11)_

First I missed the `.WorkerName` in the activation command and this broke somehow the activation.
In the client I got either timeouts or resource exhausted responses, but in the gateway I saw that the worker name is missing.

**Gateway output:**

```
io.zeebe.gateway.cmd.BrokerRejectionException: Command (ACTIVATE) rejected (INVALID_ARGUMENT): Expected to activate job batch with worker to be present, but it was blank
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse(BrokerRequestManager.java:185) ~[zeebe-gateway-0.25.0.jar:0.25.0]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:137) ~[zeebe-gateway-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.0.jar:0.25.0]
```

**Client output:**

```
Failed to activate job, because of Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1605092309.325960242","description":"Error received from peer ipv4:35.205.156.246:443","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Deadline Exceeded","grpc_status":4}")
```

After adding the worker name it works, but begins with lot of resource exhausted.

**To Reproduce**

```
 await client
                        .NewActivateJobsCommand()
                        .JobType("benchmark-task")
                        .MaxJobsToActivate(100)
                        .Timeout(TimeSpan.FromMilliseconds(totalMilli))
                        .Send(TimeSpan.FromSeconds(30));
```

**Expected behavior**

Clear error response if the worker name is required! 

**Environment:**
 - OS: k8
 - Zeebe Version: 0.24.4
 - Configuration: prod s

**Comment by npepinpe** [comment]
Expected behaviour would be that when activating a job, if it is rejected, we should not try again and return the rejection to the client.

Then as a follow up, I understood the worker name should be optional and mostly used for debugging purposes; please also make sure it is optional. Feel free to split this into two issues as well.

**Comment by MiguelPires** [comment]
A few thoughts on this issue that I wanted to leave documented: 
Currently, the gateway has no special behavior for rejections, it just tries again with the next partition. If the error is not transient then it just keeps failing until the gateway returns a response with zero jobs. At least some rejection types are definitely not transient (e.g., an INVALID_ARGUMENT rejection isn't going to be solved by retrying) and shouldn't be retried. This seems to be true for most rejection types although it's hard to say because we don't document their meaning (could we retry an INVALID_STATE rejection in a different partition?). For now, we're considering all rejections as permanent errors. The solution for this issue is to build treat rejections as permanent errors and return them to the client instead of always retrying requests until we run out of partitions. 

Similarly, both the Java and the Go clients also just log errors and, after the polling interval, retry. However, if the error is due to a permanent rejection, retrying won't solve anything. So to fully fix this problem, we also need to deal with rejections/non-transient errors at the clients. Since we are currently building back-off in the clients, the effect of this issue is going to be mitigated. However, ideally the worker should be stopped and the user is informed of the error. Some options are having an additional method to the Handler interface to inform users of errors before stopping or storing the error in the worker and letting the user get it. 

I'll create separate issues for the gateway and clients so we can fix the gateway now and the clients later (to avoid conflicts with the back-off feature and etc)
