### ISSUE TITLE
ZeebeStyle.xml for IDEA respects Go fmt rules

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe#5849]
**Description**

Right now [ZeebeStyle.xml](https://github.com/zeebe-io/zeebe/blob/develop/build-tools/src/main/resources/intellij/ZeebeStyle.xml) doesn't respect formating that does Go fmt tool. Needs to improve that file.

**Comment by npepinpe** [comment]
@MiguelPires I thought Goland by default just used go fmt? Is our style guide really messing it up?

**Comment by MiguelPires** [comment]
Yes, it does. I think our style guide doesn't define rules for Go so I don't think there's any reason to use it in Goland. @aivinog1 are you using Goland? If so, what version?

**Comment by aivinog1** [comment]
@MiguelPires I'm actually using the Go plugin for IDEA by Jetbrains, version: `202.7660.3`.

**Comment by MiguelPires** [comment]
@npepinpe I would assume that we can't add rules for Go since it's not supported by the editor, just by a plugin. In my style settings, I see tabs for Java, Kotlin, etc but not for Go, so I don't think it's possible 
@aivinog1 You could probably add a file watcher for `.go` files that runs `gofmt`, like this https://stackoverflow.com/questions/33774950/execute-gofmt-on-file-save-in-intellij 
Would that help your workflow?

**Comment by aivinog1** [comment]
@MiguelPires Many thanks, this works for me :)

**Comment by npepinpe** [comment]
If that's fine then I would close this for now :slightly_smiling_face:

**Comment by aivinog1** [comment]
@MiguelPires By the way: I can see the Go style settings
![image](https://user-images.githubusercontent.com/25925932/100212271-bae5ce80-2f3f-11eb-9eee-b3d32dfb46ea.png)
