### ISSUE TITLE
 Replace ActorTaskQueue

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#5906]
**Describe the bug**
First I thought due to our several reformatting actions we have broken the padding which is used in `ActorTaskQueue`. This class padding is used to be cache aligned, but we moved several fields and classes around.  After looking longer on it I think it is still ok, but I think we should really replace it, because it is quite complex and actually feels like just a copy of agronas data structure.

Look for example in similar implementations by agrona: 

- https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/AbstractConcurrentArrayQueue.java
- https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/ManyToOneConcurrentLinkedQueue.java

Our implementation (btw agrona has migrated his padding to bytes instead of longs)
Before
https://github.com/zeebe-io/zeebe/blob/5fd110b8618d44e1f8610f2823a67000fe39a22e/util/src/main/java/io/zeebe/util/sched/ActorTaskQueue.java

Now:

https://github.com/zeebe-io/zeebe/blob/develop/util/src/main/java/io/zeebe/util/sched/ActorTaskQueue.java

**Comment by npepinpe** [comment]
I think the biggest issue with this is that it's unbounded, and we never dealt with what happens when we want to set bounds. I understand that it being complex is bad, but I would postpone refactoring it until we have to deal with it - for example, to add a bound so we don't run out of memory (as we've seen happen). I'd rather have an issue which is focused on the problem (e.g. OOM) and whose solution is to refactor (or have an issue break down) than just a refactoring issue. Does that make sense? Or did I misunderstand the purpose of this issue?

**Comment by Zelldon** [comment]
The problem in this case would be for me hard to maintain/understand - solution refactoring :)

**Comment by npepinpe** [comment]
Closing as while this is completely valid, I don't see when we'll get around to doing this in the near future. If there's a bug or an issue which requires us to modify it, then we should refactor it as you mentioned.
