### ISSUE TITLE
Remove YAML workflows

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#6022]
**Description**

~YAML workflows will become officially deprecated in the next version. This will be part of the the new documentation shortly, and should be reflected accordingly in the code base via deprecation notices.~

As we missed the last release for this, please remove it entirely for the next release.

**Comment by npepinpe** [comment]
Prioritized as high as I'd like to just get this done so we can forget about it - the assumption is we'd deprecate it for one version, then remove it in 2, but I will get a clear green light from product beforehand.

**Comment by Zelldon** [comment]
@npepinpe did we got green light here? And how you want to deprecate it ? via warning log?

**Comment by npepinpe** [comment]
Well they were supposed to be deprecated for 0.26.0, but it seems it slipped through the cracks.  It will be shown as deprecated in the docs, and we should simply remove it for the next release.

**Comment by Zelldon** [comment]
@saig0 would like to have you as a sparring partner. I check the code and we have multiple places where we decided whether BPMN or YAML. In the end we make out of the yaml a `BpmnModelInstance`, so I think it is probably quite easy to remove it.

One question came to in my mind whether we want to remove the resource types completely, since we only will support one type then. Do we need to check the file endings, is this really necessary?

\cc @npepinpe happy about your input as well.

**Comment by saig0** [comment]
We can remove the resource type for now since we support only one. :heavy_check_mark: 

I'm not sure about the check of the file ending. It may produce better error messages if a client deploys something else than a BPMN file.

**Comment by Zelldon** [comment]
But I would expect that i can use a .txt file as well if the content is the same 😅
