### ISSUE TITLE
Investigate whether we can disable RocksDB WAL

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#6161]
**Description**

Assumption is that we don't need the write-ahead-log (WAL) because we anyway throw the runtime folder away on restart/leader changes. If we not use the WAL we can skip writing it, which would gives use some perf. improvements we assume.

See related comment https://github.com/zeebe-io/zeebe/issues/4002#issuecomment-753307551

**Open questions:**

  * Verify that we don’t lose updates on snapshotting, Are memtable’s flushed on checkpointing?

**Comment by npepinpe** [comment]
If we cannot, please tune the settings of the WAL, e.g. size, reusing files, how many to reuse/keep around, etc.

But of course first let's see if we can disable it :slightly_smiling_face:

**Comment by npepinpe** [comment]
From the documentation:

```c
class Checkpoint {
 public:
  // Creates a Checkpoint object to be used for creating openable snapshots
  static Status Create(DB* db, Checkpoint** checkpoint_ptr);

  // Builds an openable snapshot of RocksDB on the same disk, which
  // accepts an output directory on the same disk, and under the directory
  // (1) hard-linked SST files pointing to existing live SST files
  // SST files will be copied if output directory is on a different filesystem
  // (2) a copied manifest files and other files
  // The directory should not already exist and will be created by this API.
  // The directory will be an absolute path
  // log_size_for_flush: if the total log file size is equal or larger than
  // this value, then a flush is triggered for all the column families. The
  // default value is 0, which means flush is always triggered. If you move
  // away from the default, the checkpoint may not contain up-to-date data
  // if WAL writing is not always enabled.
  // Flush will always trigger if it is 2PC.
  // sequence_number_ptr: if it is not nullptr, the value it points to will be
  // set to the DB's sequence number. The default value of this parameter is
  // nullptr.
  virtual Status CreateCheckpoint(const std::string& checkpoint_dir,
                                  uint64_t log_size_for_flush = 0,
                                  uint64_t* sequence_number_ptr = nullptr);
```

My understanding is, if we set `log_size_for_flush` to 0, then it always flushes everything to SST files - from `// The default value is 0, which means flush is always triggered`.

So if we combine this with `If you move away from the default` (i.e. set it to anything but 0), then if WAL is disabled you may be missing data. But if we stick with 0, it should be fine.

Looking into the [implementation](https://github.com/facebook/rocksdb/blob/21218316dabca5ffd02e5d10793fb1894e3870ae/utilities/checkpoint/checkpoint_impl.cc#L76), we can see that `CreateCheckpoint` will call `CreateCustomCheckpoint` with the `log_size_for_flush` argument. In [there](https://github.com/facebook/rocksdb/blob/21218316dabca5ffd02e5d10793fb1894e3870ae/utilities/checkpoint/checkpoint_impl.cc#L183), we can see that if the `log_size_for_flush` is is the max uint, or if it's greater than 0, then it's possible we won't flush the memtables (based on the log size). 

The interesting part is right after, it will do a call to `GetLiveFiles` - this takes a boolean parameter which if true will flush the memtables to L-0 so that they're part of the live files (note: it also exists on the Java side, which you can find [here](https://github.com/facebook/rocksdb/blob/99a0305bb8fe4e77a7621725ac0d5921f105d84d/java/src/main/java/org/rocksdb/RocksDB.java#L4038)).

From this, you can see that the only case where you might lose data is if you have multiple column families, i.e. 

> In case you have multiple column families, even if {@code flushMemtable} is true, you still need to call {@link #getSortedWalFiles()} after {@link #getLiveFiles(boolean)} to compensate for new data that arrived to already-flushed column families while other column families were flushing.

(note that this is also found in the C side, [here](https://github.com/facebook/rocksdb/blob/21218316dabca5ffd02e5d10793fb1894e3870ae/utilities/checkpoint/checkpoint_impl.cc#L238-L248)).

However, we don't have multiple column families. After this, `CreateCustomCheckpoint` copies any WAL files (which would essentially do nothing if we disabled it), and then copies the live files.

From all of this, I think it's very likely that we can disable the WAL - I'd like to figure out a way to prove this other than read the code, but I don't really have any ideas yet.

**Comment by Zelldon** [comment]
@npepinpe sounds good we can add a test in our zb db that it contains keys after checkpointing (I think we already have ) For me it sounds good and the document seems to imply that you can turn the wal off without any problems on checkpointing.

We can discuss it tomorrow
