### ISSUE TITLE
Apply event-sourcing to the deployment processors

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe#6173]
**Description**

* apply the event-sourcing concept to the deployment processors

Open question:
* How do we keep track if a deployment is distributed or needs to be distributed again? (pending deployments in state)

Reference:
* [ZEP: Deployment](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#deploy-workflow)

**Comment by Zelldon** [comment]
We (@saig0 and me) did several pair programming sessions yesterday. We covered several things which have discussed and decided some stuff which I would like to document here.

During investigating the code and migrating it we found out that keys are generated for each Workflow by the Deployment partition. In order to do this correctly and restore the key generator on replay we decided to write a new record (event) to the stream. The WorfklowRecord, which was previous only part of the Deployment is now written to the stream. It contains all necessary information, like resource, resource name, version, checksum etc. which then is added by the EventApplier to the state. This change is done as a first step to further continue with applying the event sourcing to the deployment processors.

**To note** here is that the workflow records are only written on the deployment partition. On the other partitions it is not necessary, since the keys are already generated and the _Deployment.Created_ event can be applied to the state with all necessary information's (put the deployment with the workflows into the state).


We discussed the following lifecycle:

  * CREATE DEPLOYMENT COMMAND on partition 1
      * Transforms deployment - creates Workflows
      * Follow up events for the workflows are written
      * Deployment is distributed to other partitions (follow up event distributing? to put pendings in state)
  * CREATED DEPLOYMENT EVENT on partition 1
    * EVENT APPLIER: put deployment record into state (for re-distributing)
  * CREATED WORKFLOW EVENT on partition 1
    * EVENT APPLIER: put workflow with all information to the state
  * DISTRIBUTE DEPLOYMENT on other Partitions
    * write follow up deployment  DISTRIBUTE event
    * send response to deployment partition - causes FINISH_DISTRIBUTING command on partition 1
  * DISTRIBUTED DEPLOYMENT on other partitions
    *  put deployment with workflows in state
  * FINISH_DISTRIBUTING command on partition 1
    * write follow up event DISTRIBUTING FINISHED
    * if last partition - cause another follow up event DEPLOYMENT_DISTRIBUTED which marks the distribution completed on all partitions
  * DISTRIBUTING FINISHED event on partition 1
    * EVENT APPLIER: remove pending for specific partition, if no more pending then remove deployment record from state 
We will have listener which is called after recovery to go over the pending deployments which then sends deployments again to remaining partitions.

**Comment by Zelldon** [comment]
May planned next steps:

1. Introduce WorkflowRecord.CREATED and write it for each workflow in a deployment https://github.com/zeebe-io/zeebe/pull/6289
2. Introduce DISTRIBUTING EVENT (which allows to put pending deployments per partition in state)
3. Introduce but not write FINISH, FINISHED and DISTRIBUTING_FINISHED events and maybe new record which is used for that (or we reuse the DistributingDeployment record which only contains partition id)
4. Use intents and maybe record from 3 to distribute and send response back from other partitions
5. Think about how to solve subscriptions

Any thoughts @saig0 ?

**Comment by Zelldon** [comment]
Discussed with @saig0: We will name the last intent `FULLY_DISTRIBUTED` and the intents for the distribution response `COMPLETE` and `COMPLETED`. 

The `COMPLETE` and `COMPLETED` will be part of the `DeploymentDistributionIntent` , which is added via https://github.com/zeebe-io/zeebe/pull/6295 The `FULLY_DISTRIBUTED` is part of the `DeploymentIntent`. The DeploymentDistribution `COMPLETE` command processor will cause `COMPLETED` and if all partitions are complete `FULLY_DISTRIBUTED` as follow up event. The event appliers for `COMPLETED` will remove the pending partition and for `FULLY_DISTRIBUTED` will remove the related deployment record from the state.

**Comment by Zelldon** [comment]
@MiguelPires any reason why you closed this ? :sweat_smile:

**Comment by MiguelPires** [comment]
wtf, I don't remember even seeing this issue. Sorry @Zelldon @saig0, that definitely wasn't on purpose

**Comment by Zelldon** [comment]
I think this is related to something setup with Codetree @npepinpe otherwise I can't explain it. I merged the PR and it closed the issue by @MiguelPires :laughing:

**Comment by MiguelPires** [comment]
This time I'm sure it wasn't me (I was having lunch) so it must CodeTree or something :laughing: But it's nice to know I'm not losing my mind
