### ISSUE TITLE
Edit this page link is broken

### ISSUE THREAD

**Issue by joebowbeer** [zeebe-io/zeebe#6236]
**Description**

Clicking on **Edit this page** shows me a 404:
https://github.com/camunda-cloud/camunda-cloud-documentation/edit/master/docs/guides/setting-up-development-project.md

Is https://github.com/camunda-cloud/camunda-cloud-documentation no longer public?

Where?

- https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/getting-started/next-steps-resources
- https://docs.camunda.io/docs/guides/setting-up-development-project
- ...

Possibly related to #6099

**Comment by akeller** [comment]
Thanks for this @joebowbeer! I responded to your Slack message as well. 

Working with the team to get the docs repo publicly facing. Since this is a new docs platform (as of Jan!) we had not flipped the switch to make it public quite yet. 

Thank you in advance for not only reading our docs, but being interested in contributing back!

**Comment by akeller** [comment]
Docs repo is now public! Please confirm and we can close this issue.

**Comment by joebowbeer** [comment]
Confirmed. Thanks!
