### ISSUE TITLE
Unknown gossip event type

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#639]
We often see log messages of unknown gossip events. Is this expected?

```
19:16:14.841 [localhost:51015] [actor-runner-broker-2] WARN  io.zeebe.gossip - Ignore sync response with type 'memberRaftStates' and sender 'localhost:41016'. Event type is unknown. 
19:16:14.842 [localhost:51015] [actor-runner-broker-2] WARN  io.zeebe.gossip - Ignore sync response with type 'memberRaftStates' and sender 'localhost:31016'. Event type is unknown. 
```

**Comment by Zelldon** [comment]
I Investigated this issue. 

 Before the description starts we define the following:

 * newNode is the new node which wants to joint the cluster
 * oldNode is the contact point of the new Node

### I observed that:
On start up, the newNode will send join request to the oldNode.

After that the newNode sends an sync request to the oldNode. 
The oldNode prepares a response. This response can consist of different custom event types. 

There exist a map which stores for each member and custom event type the corresponding term.
Before the response is send, the member and custom event types are checked.
If the oldNode has no term for a specific custom event type,
then the oldNode will skip this custom event in the sync response.

### This means in our case:

OldNode has prepared as sync response some memberRaftStates, but it hadn't received any
custom event of type memberRaftStates from the newNode. That is why it will skip this in the sync response. 

As first I tried to fix that custom events are skipped if we have no term. 
I simply used the term I had from the membership events, but this ends in really weird behavior. 
After that, I realized and remembered that each custom event has it's own gossip term. 

### Why custom events are skipped?

We need the term for this custom event type, which we not have if we have not received a first custom event of this type from the newNode. Each custom event type has it's own term.

### Conclusion
I think ignoring the custom events on the sync response should not be a problem at all, since the events are spread later and the cluster seems stable in the integration tests.

@menski we can discuss this if you like

**Comment by menski** [comment]
> OldNode has prepared as sync response some memberRaftStates, but it hadn't received any
custom event of type memberRaftStates from the newNode. 

I don't understand why this is important, as the term should be bound to the event and not the newNode. If the OldNode has custom events to share they should have a term or not?

**Comment by Zelldon** [comment]
For me it seems that each member creates a term for each custom event type
see here https://github.com/zeebe-io/zb-gossip/blob/master/src/main/java/io/zeebe/gossip/Gossip.java#L140-L146

**Comment by menski** [comment]
Yes if you create a new event for your own. But if you distribute events they should already have a term. Only the node which the event corresponds to is allowed to set/change the term. Broadcasting events from other nodes should not change the term.

**Comment by Zelldon** [comment]
That is right. OK I had the wrong assumption.
Fixed the 'problem'. We send a empty list of 'memberRaftStates' for a member.

### Example:
The node `51015` sends for each member in his list the raft states. Even if the list is empty it sends an custom event of type 'memberRaftStates', which is empty. This means it will send for `41015` an empty custom event of type `memberRaftStates`. It is empty because `51015` has not received any raft states from `41015`. That is also the reason why we have no term and we see this log msg.

I added a if statement, which checks if the list is empty.

Sorry for the confusion and thanks that we can talk about that. It helped a lot :D

**Comment by menski** [comment]
Did you pushed the change?

**Comment by Zelldon** [comment]
Not yet
