### ISSUE TITLE
Avoid proprietary API: sun.misc.VM

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe#680]
the build logs the following warning(s) for VerifyDirectMemoryTest

`[WARNING] .../zeebe/qa/integration-tests/src/test/java/io/zeebe/broker/it/VerifyDirectMemoryTest.java:[21,16] sun.misc.VM is internal proprietary API and may be removed in a future release`

usage should be avoided

**Comment by menski** [comment]
Hi @jangalinski,

this API is only used inside [the test case](https://github.com/zeebe-io/zeebe/blob/9e1907fe89ef12d8140c8b58ec4aca3b322550ee/qa/integration-tests/src/test/java/io/zeebe/broker/it/VerifyDirectMemoryTest.java#L28) itself to check if the test suite is configured with enough direct memory, as otherwise test may fail. If you know how to check this without using this API please let us known. Otherwise if there is not problem executing the test I would close this ticket for now.

Cheers,
Sebastian

**Comment by jangalinski** [comment]
fine with me ... just not a big fan of warnings during build runs
