### ISSUE TITLE
Make future blocking actor phase opt-in

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#696]
Make if possible for an actor to wait on a future in a way that the actor stays in its current lifecycle phase until the future is completed.

Example: while in the STARTING phase I want to open a subscription and wait until this future completes before I transition to the STARTING phase or get interrupted by close().

In that case I can 

```
protected void onActorStarted()
{
    actor.runOnCompletion(subscription.openAsync(), ActorLifecyclePhase.STARTING, handler);
}
```

the important part is the `ActorLifecyclePhase.STARTING` parameter which is passed in.
If we do not pass this parameter, the actor will run the handler on completion but it will not wait in the STARTING phase until this future gets completed.

**Comment by meyerdan** [comment]
I have had a look at this now and it is actually supposed to work this way: from onActorStarted, we call run(...) which is executed immediately, this way the actor is still in the STARTING phase and from the method we then call runOnCompletion which causes the actor to remain in the STARTING phase. While in the STARTING phase, the timer does not trigger.

So this is expected behavior but it is completely non obvious and when you showed it to me on Friday I did not immediatly recognize it. I have an idea about how to make this more explicit in the API which I will propose.

**Comment by Zelldon** [comment]
Ah ok, makes sense. Thank you. :)

**Comment by Zelldon** [comment]
Hey Daniel,

I have maybe also an Idea to make this clearer.

The actor could have an callback for each method for example:
```java
public class ZbActor
{
  void onStarting(StartingControl control);
  void onStarted(ActorControl control);
  void onClosing(ClosingControl control);
}
```
The interfaces `StartingControl` and `ClosingControl` give only limited access to the ActorControl,
which means it is only possible to call `run`, `runOnCompletion` and other stuff which are possible in the Starting or Closing phase. In the `onStarted` method we have the full access and are able to submit timers. I think this makes it clearer in which state timers are triggered and when I can submit them.
The interfaces could look like this:

```java
public interface StartingControl
{
  void run(...);
  void runOnCompletion(..);
  [...]
}

public interface ClosingControl extends StartingControl
{
}

public interface ActorControl extends StartingControl, ClosingControl
{
 void runAtFixedRate(...);
 void runDelayed(...);
void consume(...);
}
```


What do you think?
