### ISSUE TITLE
Add assertions to scheduler

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#707]
Let's add `assert` statements to ensure invariants in the actor scheduler. Assertions should then be activated as part of our test suite. This helps us detect bugs faster, for example the issue in #705 could be detected by asserting that a job cannot be linked to itself.

**Comment by menski** [comment]
let's do it

**Comment by Zelldon** [comment]
Hey @ThorbenLindhauer was was the reason behind the change of  this  [line](https://github.com/zeebe-io/zb-util/blob/3ffade93c081cfdeb5e43a35ab04cbabe906218c/util/src/main/java/io/zeebe/util/sched/ActorControl.java#L442) ? 

This changes the behavior completely and breaks the broker tests, because for example the StreamprocessorController does not execute the methods onEvent, executeSideEffects, WriteEvent etc in the correct order :see_no_evil:

**Comment by meyerdan** [comment]
@Zelldon I fixed it

**Comment by Zelldon** [comment]
@meyerdan yeah saw this afterwards. Thanks for this :)

**Comment by ThorbenLindhauer** [comment]
Just thought that there is no guaranteed order anyway and preferred to have one `append` entry point. So feel free to revert it.
