### ISSUE TITLE
Improve accuracy of job timeout trigger

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#724]
Current implementation:

* Iterates all timers every 30 seconds and checks for expiration

Idea for improvement:

* After iterating all timers, schedule the next check for the time when the next task is going to expire
* Also reschedule timer if a new task is locked that expires even sooner
* Still the check should be at most performed once per second (or similar), to avoid constantly checking for expired timers

Future issues:

* Stream processor should have its own timer wheel: https://github.com/zeebe-io/zeebe/issues/745

**Comment by ThorbenLindhauer** [comment]
We discussed this and instead of going for an intermediary solution wanted to try out if we can make use of a timer wheel immediately. We would work around the limitation of not being able to serialize the wheel by keeping both the ZbMap and a wheel and generate the wheel from the map on stream processor recovery. I implemented this on branch #724, but I have the impression that Agrona's timer wheel implementation is not suited for the way we want to use it. The detailed reasons follow from this code: https://github.com/zeebe-io/zeebe/blob/97fedccffe80198e76f373779a38e8b2213364ad/broker-core/src/main/java/io/zeebe/broker/task/processor/TaskExpireLockStreamProcessor2.java#L95-L112

**Comment by ThorbenLindhauer** [comment]
Postponing this.

**Comment by npepinpe** [comment]
Not sure this is still something we want to do - anyone? :eyes:

**Comment by Zelldon** [comment]
I think this is still the case

**Comment by npepinpe** [comment]
If I understand correctly, this is related to `JobTimeoutTrigger`, correct? My understanding is the intermediate solution proposed in the issue is essentially a solution for https://github.com/zeebe-io/zeebe/issues/5073? I would then close this in favour of https://github.com/zeebe-io/zeebe/issues/5073, but maybe I'm missing something - I'll wait for @Zelldon or @saig0 or someone who maybe remembers this to confirm.

**Comment by saig0** [comment]
@npepinpe correct :+1: 
We can close this issue in favor of #5073.
