### ISSUE TITLE
Investigate and improve client request retry controller

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#734]
The transport throughput when using the client request retry controller may be improved.

- [x] unify api and implementation
- [x] port all modules to the new api
- [x] factor out stress test into new profile and run with JMH
- [x] make fast by having timers for timeouts properly cancelled #735

**Comment by ThorbenLindhauer** [comment]
I would like to have a test that fails when a defined throughput goal is not met. May be hard to achieve though, when the test can be run in different environments.

**Comment by menski** [comment]
We can disable such test per default for example using a maven profile. And enable it on Jenkins.

**Comment by ThorbenLindhauer** [comment]
Fixes implemented in https://github.com/zeebe-io/zb-transport/commit/a264939d8d6fbc4370f72b1f91f4f08a3acb2dcd:

* `ClientRequestController`
  * I was suspecting that there is a chance that `#init` is called while the actor is still in `STARTING` phase. The actor would then proceed to make the request in that phase and so the request timeout would not apply. I wrote a test for this and found out that this is apparently not a problem, as `#init` calls `ActorControl#run` which behaves like `#call` when called from a different actor/non-actor thread. So the request is only ever made in the `STARTED` phase.
  * `#processResponse` and `#fail` are in a race condition, because `#processResponse` makes a decision based on the response future outside of the actor context. It can happen that `#processResponse` copies the response into the response buffer, while `#fail` is run in parallel and completes the future exceptionally. The solution to this is to check the future state a second time in the actor context.
* `ClientReceiveHandler`
  * There's a race condition with reusal of request controllers. The handler may receive a response and look up the corresponding request controller. If in the meantime the request controller is reused, the handler would correlate the response to the new request. To avoid that, we must check the response's request id a second time from within the controller's actor context. The same pattern exists in `ClientSendFailureHandler`
* Javadoc in `ClientOutput` was not entirely up to date
* `ClientRequestPool`: when closing the client transport (and therefore the pool), it should only resolve the close future when all request controllers have been closed. This avoids situations where the request controllers are still running while the send buffer is already teared down.
