### ISSUE TITLE
Remove autodetect of thread count in broker

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#789]
Currently, when the broker starts and no thread count is provieded in the configuration, it will automatically determine the "best" number of threads to use for the scheduler. The logic is NumberOfProcessors - 2. NumberOfProcessors is returned by the JVM.

This will almost always take the wrong decision, particularly if the user has
* Hyperthreading enabled
* Uses Docker and has restricted CPU quotas
* Wants to run other things besides Zeebe on this machine :)

The result is that the Zeebe Scheduler does it's job too well and oversubscribes the CPU and the OS CPU scheduler has to preempt threads at non-safepoint state all the time. This leads to very bad behavior.

I think we should simply remove this feature and distribute Zeebe with a configuration where threadcount is set to 1 and document how the user should configure this.

**Comment by menski** [comment]
At least the docker use case should improve with newer Java versions, see https://blog.docker.com/2018/04/improved-docker-container-integration-with-java-10/

So for these deployment scenarios a auto config options might make sense as otherwise you have to configure the limits in multiple places. WDYT?

**Comment by meyerdan** [comment]
All magic is removed via #815
