### ISSUE TITLE
Validate client API redesign

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#793]
- Use mockup API created in #792 and give it to some users (Bernd, consultants, operate and optimize team, public slack channel, ...)
- Record findings here

**Comment by ThorbenLindhauer** [comment]
Feedback from user test with @JoHeinem:

* liked the step builder approach of being guided through subscription creation
* liked async-only
* liked command/event distinction in subscriptions
* #handler method on topic subscription builder is a little too broad => name it such that it reflects the handler's purpose (e.g. genericHandler)

**Comment by ThorbenLindhauer** [comment]
Feedback from user test with @sdorokhova:

* Structure of client accessors: it would be more logical to have `zeebeClient.topicClient("topic").workflowClient()` than `zeebeClient.topicClient("topic")` and `zeebeClient.workflowClient("topic")`. The former reflects the hierarchy better (choosing topic is one dimension, choosing workflow/workitem operations is another dimension) whereas the latter leaves questions where to find operations (e.g. I want to subscribe to all workflow events)
* It is not obvious when to use which kind of subscription and where to find them
* Likes the step builder approach; choosing one parameter at a time is nice
* Would like some more defaults (e.g. lock time of a work item subscription)

**Comment by ThorbenLindhauer** [comment]
Feedback from user test with @nikku:

- Likes the step builder approach
- Not obvious how to access the key of an event (indirection via metadata). Especially since the key is relevant for some APIs like create workflow instance
- Would like defaults for lock time and lock owner
- Likes that event/command concept is visible in the API. Raises awareness for how the system works
- Would like to have a variant of `WorkItemHandler` without the `client` argument when the handler accesses client in another way (e.g. field)
- Uniqueness of topic subscription names: It is easy to make mistakes by choosing clashing subscription names when independent developers work with the same Zeebe cluster
- It is confusing that `WorkflowInstanceEvent` represents both workflow and activity instances. For example, when the create command returns a `WorkflowInstanceEvent`, then a method like `#getActivity` makes no sense in that context.
- Requirements of event and work item handlers with respect to thread-safety should be documented in fluent builder methods.

**Comment by ThorbenLindhauer** [comment]
Feedback from consultant session last Thursday:

* better than old API
* not obvious what a topic subscription name is for and why it is required
* things like `WorkflowInstanceEvent#isStarted` `WorkflowInstanceEvent#isEnded` in addition to state enums
* `#send` is sometimes missed (people are not sure if required)
* API can be confusing when Zeebe concepts are not known yet

**Comment by ThorbenLindhauer** [comment]
As the next step we will post the draft in the public slack channel and ask for feedback. We will continue with implementing it in parallel.

**Comment by Zelldon** [comment]
As you already know I really like the step builder pattern ;)
I also like the current implementation with the hierarchic clients and the default topic usage if no topic is set.

I have some further proposals perhaps you can think about them:

### 1. Proposal 
I will take as example the JobClient but this also effects the WorkflowClient I would say.

Currently to create an Job you can do this:
```java
 final JobEvent jobEvent = topicClient
            .jobClient()
            .newCreateCommand()
            .jobType("task")
            .payload("{}")
            .send()
            .join();
```

and to complete a job you can do this:
```java
        // via job subscription
        pollableJobSubscription.poll((client, job) ->
        {
            // ...
            client.newCompleteCommand()
                .event(job)
                .send();
        });

        // OR ASYNC
        // String json = db.load(...)
        final String json = "{}";

        final JobEvent job = zeebeClient
                .objectMapper()
                .fromJson(json, JobEvent.class);

        zeebeClient.topicClient(job.getMetadata().getTopicName())
            .jobClient()
            .newCompleteCommand()
            .event(job)
            .payload("{}")
            .send();
```

I think it would be easier if `topicClient.jobClient()` returns an JobCreationClient, on which you can create task and if you use ``topicClient.jobClient(job)` it returns an JobUpdateClient, on which you can update the retries, payload, complete etc. 

I think would also easier for beginners. They can simple create an task and if they get an job, they can put it into the `jobClient` method and update the current job. This also will remove the `event` step.

Would look like this:

```java
        zeebeClient.topicClient("topic")
            .jobClient(job)
            .newCompleteCommand()
            .payload("{}")
            .send();
```

And in the job subscription the handler only gets the job and the JobUpdateClient.

What do you think?


### 2. Proposal 

On Intellij and Netbeans code completion methods which are direct implemented in a class are highlighted, inherited methods are not, which means
the `send` method for example is not highlighted this could mean an user can miss this call. The same applies to the topic subscription handlers. (ManagedTopicSubscriptionBuilderStep4 extends of ManagedTopicSubscriptionBuilderStep3) .

One solution for this would be that we have no inheritance in the interfaces. But this would decrease the maintainability I think. It is not really a proposal more a remark to be aware of, that this can be a pitfall.

![intellij-methods](https://user-images.githubusercontent.com/2758593/39170053-5e96923e-479a-11e8-9112-17ea541d03e7.png)
![intellij-method-send](https://user-images.githubusercontent.com/2758593/39170054-5eb33844-479a-11e8-9680-6410f6bbf728.png)
![netbeans-methods](https://user-images.githubusercontent.com/2758593/39170055-5ecc5f18-479a-11e8-870f-920613c03903.png)
![netbeans-method-send](https://user-images.githubusercontent.com/2758593/39170056-5ee6c33a-479a-11e8-8cc3-824aa2c21a09.png)

### 3. Proposal

Why we have on every command an `new` prefix? 
Since we have it on each command I'm not seeing any value on this prefix.
Can we remove it?

![commands](https://user-images.githubusercontent.com/2758593/39170278-3a38c37a-479b-11e8-8591-47e174fa0870.png)
![screenshot2018-04-2408 37 20](https://user-images.githubusercontent.com/2758593/39170279-3a56ab74-479b-11e8-915a-1f5f1fee16b0.png)


### 4. Proposal
I think `withoutPayload` can be removed right?

```java
zeebeClient.topicClient().jobClient().newCompleteCommand().event().withoutPayload()
```

**Comment by ThorbenLindhauer** [comment]
Thanks for your feedback.

Re 1: I wouldn't do this for two reasons. 1) People may want to reference the clients in fields; having a larger number of clients doesn't make this easy 2) The distinction may not be obvious to everyone; finding the command your are looking for may become harder

Re 2: Good point, I wasn't aware of that. Not sure if we should change this for the reasons you mention.

Re 3: The value would be readability of the code and thus also a matter of taste.

Re 4: Can you please elaborate on that?

**Comment by Zelldon** [comment]
1.
> 1) People may want to reference the clients in fields; having a larger number of clients doesn't make this easy 

True but I think that is why they will have only the topic client in one field, so then it would be no difference. 

> 2) The distinction may not be obvious to everyone; finding the command your are looking for may become harder

For me it felt more intuitive to update something which I already have and work on this.

3. But why do you think it is more readable? Without the `new` prefix I see faster the difference in the code completion. Furthermore it is every time a new command right? I mean I can't reuse one so I have no need to distinguish I would say. But yeah perhaps matter of taste.

4. Since we have the step builder pattern and optional parameters like payload or version we have no real need to have methods like `withoutPayload` or `latestVersion` (this is default).  But perhaps it makes the api clearer.

**Comment by ThorbenLindhauer** [comment]
Re 4: `withoutPayload` is not the default. The default is sending the payload you received. With respect to `latestVersion` you are right. I personally find it ok to force users to choose a version explicitly, but I am fine either way.

**Comment by ThorbenLindhauer** [comment]
Re 1: An object named `client` suggests that it can be used more than once. This would not be the case for `JobUpdateClient`, because the second command will always fail once #795 is in place. In the sense of your argument, the syntax we had in the first draft version would maybe make sense, i.e. `jobClient.newCompleteCommand(job)`.
