### ISSUE TITLE
Create examples for basic Zeebe use cases

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#801]
* A reference of the most common operations and how they look like when done correctly
* Some people like to start coding that way (i.e. take example and extend it from there)
* This will help people spot their mistakes (e.g. forgetting to send a command)
* Could be on github or in docs (or both)
* Snippets could be: Deploy a workflow, start an instance, cancel an instance, minimal job subscription, minimal topic subscription

**Comment by Zelldon** [comment]
## Review

 ## Proposal 
  * Lets create an read me in the examples, which contains a link to the docs  
  * Lets try to link from the examples to the corresponding sections which explains the stuff in more detail

  ## docs/src/java-client-examples/workflow-deployment-request.md

   > Make sure workflows are deployed, e.g. run the [Deploy a Workflow example](java-client-examples/workflow-deploy.html) multiple times
  Sounds like it is necessary otherwise it will not being deployed. Maybe we can change the wording
