### ISSUE TITLE
Ensure event producers are closed before replication factor is lost

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe#807]

**Comment by menski** [comment]
Why would you stop commiting? We cannot stop commiting as this would break raft. If you actually mean to prevent the client API to accept more user events then the title of this issue is misleading.

**Comment by meyerdan** [comment]
Would this be better?:

"Ensure no more non-raft events are comitted after replication factor is lost"

It is about both
- commands / events added thorugh client api
- commands / events added by stream processors.

**Comment by menski** [comment]
I think we should not interfere with committing events. As this is a concern of raft and if messed up might lead to undefined behavior. Also it is not possible to commit partially as the log is a sequence of events where the commit position is only advanced. What do we want to achieve within this issue?

**Comment by menski** [comment]
What we want to achieve with this issue is that if the raft member size will drop below the replication factor we have to make sure that all non-raft event producers (client API, stream processors) are stop before we accept the leave of the member. Otherwise we might commit events with a smaller quorum then the replication factor requires.

**Comment by Zelldon** [comment]
Add some doc and some integration tests in the broker.

I also created an follow up issue since some of the clustering tests fail because they take the wrong assumption since now the partition service is removed if the replication factor is not satisfied anymore. (see #844 )
