### ISSUE TITLE
The raft metadata file is persisted as JSON instead of msgpack

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#826]
At the moment the raft metadata file is in msgpack format. This makes it hard for operators to edit the file. In recovering scenarios it might be required to edit the file manually to remove brokers from the raft group. To ease that operation and make the file human readable it should be in JSON format.

**Comment by npepinpe** [comment]
A few things to note:

1. since it uses jackson instead of the zeebe msgpack implementation, we don't control allocation anymore. probably not that important considering this is configuration related.
2. I simplified the serializable POJOs (the metadata stuff) to be as simple/plain as possible, since they were pretty much only used in the RaftPersistentConfiguration class, which was/still is the main interface to it.

**Comment by npepinpe** [comment]
As we discussed, I'd rather not have had to hardcode the path to the persisted configuration file, but I prefer that to modifying the visibility for the test's sake.
