### ISSUE TITLE
JVM crash on log stream reader usage

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#866]
Occurred running the integration test suite. Crashed in `CreateTopicClusteredTest`. 3 out of 3 times this happened in `*ClusteredTest` classes.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000772a3ae6, pid=9812, tid=6568
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b26) (build 1.8.0_40-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ntdll.dll+0xd3ae6]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\camunda\repos\tngp\zeebe\qa\integration-tests\hs_err_pid9812.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

[hs_err_pid9812.log](https://github.com/zeebe-io/zeebe/files/2008389/hs_err_pid9812.log)

**Comment by menski** [comment]
At the moment we assess this issue as a Windows specific problem. We were not able to reproduce this on another system. It is also possible that it is caused by bad memory. We will keep investigating and hopefully find a solution for @ThorbenLindhauer. If anyone else experience this issue please let us know and reopen this issue.
