### ISSUE TITLE
Client RecordMetadata contains source record position

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#869]
[RecordMetadata](https://github.com/zeebe-io/zeebe/blob/21c542bde0b2a547328a8ea6fd0aac154a6a4775/client-java/src/main/java/io/zeebe/client/api/record/RecordMetadata.java) contains a property which contains the source record position of this record.

AT:
- ExecuteCommandResponse and SubscribedRecord contains `sourcePosition` which exposes the [LogEntry source event position](https://github.com/zeebe-io/zb-logstreams/blob/9a59f9eadad922198ed240c0b8118b5a96279ad4/src/main/java/io/zeebe/logstreams/impl/LogEntryDescriptor.java#L44) which is set by the TypedResponseWriter to the current record position
- Client RecordMetadata contains `sourcePosition` property
- Client sets `sourcePosition` on ExecuteCommandRequest
- ClientApiMessageHandler sets `sourceEventPosition` of Log Entry to `sourcePosition` of ExecuteCommandRequest

**Comment by menski** [comment]
@Zelldon we should ping @jsam when we push this to master as it will immediately break the go client

**Comment by Zelldon** [comment]
@jsam I would like to push this to master in the next days

**Comment by menski** [comment]
lets wait til Friday, as we have to check if we need a patch release

**Comment by Zelldon** [comment]
Ok :+1:

**Comment by ThorbenLindhauer** [comment]
Review:

* Broker
  * Jobs pushed via Job subscription do not contain source position => fix and test
  * Explain in `TypedResponseWriter` javadoc in which situations `writeEventUnchanged` or `writeEvent` must be used
* Protocol
  * we can remove the field `position` from `ExecuteCommandRequest` because it is not used by the broker => create a separate issue as this is unrelated to the changes here
* Java Client
  * should set the position of the base event as the source position to be consistent with commands that the broker generates (currently, we use the base event's source position)
  * Remove `Record#getSourceRecordPosition`
  * Improve javadoc for `RecordMetadata#getSourceRecordPosition`. Explain a little more in detail what the source position refers to, when it is set, and which value range indicates that the source position is set or not
  * Tests: Stub classes: A couple of stubbing methods force tests to define a source record position for the stubbed response. There should be a no-args option again, as source record position is not relevant for most tests

**Comment by Zelldon** [comment]
@jsam gave me a hint that we have to do set the presence to optional on SubscribedRecord so it can use the default value
