### ISSUE TITLE
Raft follower replicates snapshot from leader

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe#878]
Restore follower partition service and group, and use a group reference to manage sub services for each follower partitions, and replicating the leader's snapshots.

Related to #876 and #877

**Comment by menski** [comment]
Maybe we will bring back the follower partition service, see https://github.com/zeebe-io/zeebe/commit/2387a7e1e8a2c41758074ab8e3213d1923972020#diff-2fba5caf998b7aebede1bf3301f78418R148

**Comment by npepinpe** [comment]
Ah, it looks like it linked commits from my branch as opposed to just the last merge commit (which makes sense, I guess). My bad.

**Comment by npepinpe** [comment]
The current process is as follows:

1. ClusterComponent on set up installs SnapshotReplicationInstallService, which will track follower partitions using a reference group.
1. Follower partition services are installed by the PartitionInstallService on raft state change, and remove accordingly on raft state changes.
1. On new follower partition, install SnapshotReplicationService, which is dependent on the Partition service (such that if that service is removed, so is the replication service).

SnapshotReplicationService implements very basic folder mirroring: 

1. Periodically (defined in the config file, by default 5 minute) poll the partition leader for a manifest of the snapshot it currently has: name, log position, size, and checksum.
1. For every snapshot S not currently on the follower, start replicating it:
    1. Allocate a temporary writer, which will write the incoming data to a temporary file, and on finish will move that file to the correct snapshot file + write the checksum file, iff the checksum matches from the manifest.
    1. Starting at offset 0, loop and fetch chunks of bytes in a fixed amount (at the moment 512k), incrementing the offset by the amount of bytes read, and requesting a new one.
    1. On error, abort current snapshot and move on to the next snapshot (or schedule a new polling-for-manifest operation)
    1. Once it has read the amount of bytes advertised by the manifest, validate and commit the snapshot. Regardless of error or success, move on to the next snapshot to replicate.

Things that could be improved:

1. Extract single snapshot replication to a separate class to better separate concerns of the service (i.e. reading manifest, looping of each entry, replicating, etc.), and avoid having a single class keeping so much state. Plus it would simplify the overall code, and improve readability.
1. Better error handling: some errors during replication of a single snapshot might better warrant a retry of the chunk vs aborting the whole thing.
1. Defining replicability of a snapshot: FsStorageConfiguration decides at the moment what snapshots are replicable using a terrible string-match for !blockIdx, but that feels very hacky-ish. Ideally a snapshot would know if it is replicable or not, but as we don't write snapshot metadata at the moment (other than the checksum), not sure what's the ideal way of implementing this.
1. Checking if a snapshot is committed or not: a snapshot is committed iff it has both the data + checksum file on disk; without the checksum file, we consider it uncommitted, but potentially being written. That also isn't very explicit, and perhaps moving the SnapshotStorage to its own service/actor through which all others have to go through would alleviate the issue (then keeping a list of currently-being-written snapshots it in memory would be sufficient).
1. Depending on snapshot-size + network condition, the above process is most likely not very performant.

**Comment by Zelldon** [comment]
Possible race condition in `SnapshotReplicationServiceTest#shouldRetryOnTopologyError` on line [137](https://github.com/zeebe-io/zeebe/blob/master/broker-core/src/test/java/io/zeebe/broker/clustering/base/snapshots/SnapshotReplicationServiceTest.java#L137).
You need to do this in the `SnapshotReplicationService` actor otherwise it can interfere with the `SnapshotReplicationService` execution actor thread and the main thread which runs the test method.

Mockito will have problems to change the mocks at sometime and then it will fail like this:

```java
08:41:48 [INFO] Running io.zeebe.broker.clustering.base.snapshots.SnapshotReplicationServiceTest
08:41:49 [ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.363 s <<< FAILURE! - in io.zeebe.broker.clustering.base.snapshots.SnapshotReplicationServiceTest
08:41:49 [ERROR] shouldRetryOnTopologyError(io.zeebe.broker.clustering.base.snapshots.SnapshotReplicationServiceTest)  Time elapsed: 0.014 s  <<< ERROR!
08:41:49 org.mockito.exceptions.misusing.UnfinishedStubbingException: 
08:41:49 
08:41:49 Unfinished stubbing detected here:
08:41:49 -> at io.zeebe.broker.clustering.base.snapshots.SnapshotReplicationServiceTest.shouldRetryOnTopologyError(SnapshotReplicationServiceTest.java:137)
08:41:49 
08:41:49 E.g. thenReturn() may be missing.
08:41:49 Examples of correct stubbing:
08:41:49     when(mock.isOk()).thenReturn(true);
08:41:49     when(mock.isOk()).thenThrow(exception);
08:41:49     doThrow(exception).when(mock).someVoidMethod();
08:41:49 Hints:
08:41:49  1. missing thenReturn()
08:41:49  2. you are trying to stub a final method, which is not supported
08:41:49  3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed
08:41:49 
08:41:49 	at io.zeebe.broker.clustering.base.snapshots.SnapshotReplicationServiceTest.shouldRetryOnTopologyError(SnapshotReplicationServiceTest.java:137)
08:41:49 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:41:49 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:41:49 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:41:49 	at java.lang.reflect.Method.invoke(Method.java:498)
08:41:49 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
08:41:49 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
08:41:49 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
08:41:49 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
08:41:49 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
08:41:49 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
08:41:49 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
08:41:49 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
08:41:49 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
08:41:49 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
08:41:49 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
08:41:49 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
08:41:49 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
08:41:49 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
08:41:49 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
08:41:49 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
08:41:49 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
08:41:49 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
08:41:49 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
08:41:49 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
08:41:49 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
08:41:49 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
08:41:49 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
08:41:49 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
08:41:49 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
08:41:49 
```

Corresponding build https://hq2.camunda.com/jenkins/zeebe/job/zeebe-DISTRO-maven-deploy/1301/consoleFull

Also there is a possible NullPointer on `#shouldAbortCurrentSnapshotIfOneChunkFailsAndMoveToNextOne` see failing test build
https://hq2.camunda.com/jenkins/zeebe/job/zeebe-DISTRO-maven-deploy/1303/consoleFull

Maybe you can have a look into this.

**Comment by npepinpe** [comment]
Thanks @Zelldon for pointing it out. Should be fixed now.

**Comment by Zelldon** [comment]
Cool :+1:

**Comment by npepinpe** [comment]
Found a bug when multiple brokers download the same snapshot (only happens with large files, but I imagine that's just because it increases the likelihood). Not really 100% sure why this happens, but I can reproduce it, so I'll check it out. I'll add a test case once I know exactly what's going on (afaik fseek for reads should handle concurrency since they're using different file descriptors in different requests...I think).

**Comment by npepinpe** [comment]
Another bug, aborting due to mismatched checksums throws an NPE, which...not sure how it happens, but should be fixed (not too terrible considering that it happens once we've already aborted, so whatever, but still ugly).

**Comment by ThorbenLindhauer** [comment]
Review:

### SnapshotReplicationService

* the error case when the leader of a partition changes and we receive a corresponding ErrorResponse seems not to be handled very well
  * we do not update the leader address in this case
  * The error handling in `#handleListSnapshotsResponse` results in a livelock
* `#replicateNextSnapshot`
  * The log message could state for which snapshot the exception occurred; could be useful to understand the problem when seeing the message
* `#abortCurrentSnapshotReplication`:
  * if this is called for the last snapshot of the current list (i.e. `snapshotsToReplicate.isEmpty()` is true), snapshot replication stops
* Log messages: Would be nice for all the log messages to have a common prefix (e.g. `Snapshot replication:`) which could make the log files easier to read and understand
* `#stop`
  * this method is invoked from a service container actor and should therefore not directly modify the service's state (e.g. not call `#abortCurrentSnapshotReplication`); cleanup logic should rather go into `#onActorClosing` or similar

### FsTemporarySnapshotWriter

* `#writeToDisk`
  * if `Files.move` fails we have no snapshot anymore (since `super.writeToDisk` removed the last one already)
* open TODO should be resolved
* usage of `StandardCopyOption.ATOMIC_MOVE`; see javadoc for Files.move: all other options are ignored, operation may fail if file exists which contradicts the intention of using `StandardCopyOption.REPLACE_EXISTING`; similar logic is in `RaftPersistentConfiguration#save`
* SuppressWarnings annotations and comments for unused return values etc.; I guess these are generated by IntelliJ; Eclipse doesn't recognize them and reports them as unnecessary and we also do not use these annotations anywhere else

### SnapshotReplicationServiceTest

* open TODO: why not use a shared constant then?

### Tests

* test that snapshots with size > chunkSize can be replicated

### Regarding the things that could be improved you listed in https://github.com/zeebe-io/zeebe/issues/878#issuecomment-396482196

  * these things sound sensible to me; feel free to create issues for improvement or do them straight away (e.g. anything related to code quality should be considered as part of this issue)

**Comment by npepinpe** [comment]
Changes applied after review.

As for next issues, there is one already to do proper load tests (i.e. not just my local machine). As for the others, 1) and 2) would be premature I think (2 being a special case we account for, and 1 being an easy optimization). 

As for the 5th point, I gave a shot quickly to see how it would go, and while I think it makes it easier for introspection at runtime (i.e. knowing which state you're in, debugger showing the strict minimum state necessary to understand what's going on, etc.) at the cost of a little abstraction overhead. So I think it's worth thinking about refactoring to such a model, but it can definitely be deferred to the next iteration (i.e. if we rewrite for performance by switching from request/response to messages).

As for 4, it will be addressed in another issue.

**Comment by npepinpe** [comment]
I would postpone the review until #953 is resolved.
