### ISSUE TITLE
Release Zeebe 0.10.0

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#897]

**Comment by ThorbenLindhauer** [comment]
- new Java client API based on user feedback
  - clear command/event separation
  - JSON (de-)serialization of records
  - distinction *topic subscription* vs *job worker*
  - *task* -> *job*

**Comment by npepinpe** [comment]
Here's a quick list by looking at the issues closed since the last release:

* [Every logged event now has a timestamp](https://github.com/zeebe-io/zeebe/issues/849)
* [Default topic can be created through configuration file](https://github.com/zeebe-io/zeebe/issues/835)
* [Reiterate sending of requests in transport](https://github.com/zeebe-io/zeebe/issues/858
* [Use common sha1sum format for checksum files](https://github.com/zeebe-io/zeebe/issues/425)
* [Resilience of workflow deploy](https://github.com/zeebe-io/zeebe/issues/843)
* [Workflow API](https://github.com/zeebe-io/zeebe/issues/852)

Additionally, bugfixes and documentation improvements. Couldn't tell which ones are particularly important enough for a release announcement, so if you do know, add it here.

**Comment by menski** [comment]
- first NodeJs client release using FFI of zbc-go 
  - https://www.npmjs.com/package/zbc-node
  - https://github.com/zeebe-io/zbc-node
  - https://github.com/zeebe-io/zbc-node#get-started
  - https://github.com/zeebe-io/libzbc
