### ISSUE TITLE
Raft tests unstable

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#920]
The default leave timeout of 1 second is sometimes too short, which causes test failures.

**Comment by ThorbenLindhauer** [comment]
Decided to only increase the leave timeout in the raft test suite. Increasing the general default led to a couple of test timeouts in the integration test suite (clustered tests)

**Comment by menski** [comment]
In general I think our close timeouts are to much focused on unit testing instead of real use cases. In normal environments a user probably prefers a graceful shutdown which takes longer then a fast shutdown, which will leave nodes in a still joined state in the cluster. The timeouts in the cluster tests was probably caused by the system context close timeout  also being 10s
https://github.com/zeebe-io/zeebe/blob/53615b0f92d7e64f46cdb8b1380a456def2a910a/broker-core/src/main/java/io/zeebe/broker/system/SystemContext.java#L40

But as there is also the issue that if a partiton leader is shutdown no graceful step down is happening which requires a leader change before the next broker can leave. Which will most likely at the end trigger a timeout nevertheless or stopping a cluster test takes quite long. Therefore I agree that changing the timeout in the raft test suite at the moment is a better solution.

**Comment by ThorbenLindhauer** [comment]
> The timeouts in the cluster tests was probably caused by the system context close timeout also being 10s

Yeah, I set this to 20 seconds. Then the `TimeoutRule` kicked in after 30 seconds in a couple of tests and that's where I grew tired of adapting timeouts :)
