### ISSUE TITLE
Client: TopicSubscriptionTest can hang indefinitely

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe#939]
On Jenkins: https://hq2.camunda.com/jenkins/zeebe/job/zeebe-DISTRO-maven-deploy/1298/
I also had this locally very rarely (< 5 % of cases)

**Comment by npepinpe** [comment]
Hangs in shouldCloseSubscriptionOnClientClose when joining with the closing thread (so client::close sometimes never finishes).

**Comment by Zelldon** [comment]
https://hq2.camunda.com/jenkins/zeebe/job/zeebe-DISTRO-maven-deploy/1302/

**Comment by npepinpe** [comment]
The issue was related to [SubscriberGroup#closeSubscriber:259](https://github.com/zeebe-io/zeebe/blob/7aa4d1ab6d3551cbf94d62d2b7756e44eb2e000b/client-java/src/main/java/io/zeebe/client/impl/subscription/SubscriberGroup.java#L235)

Essentially, a continuation job was submitted that should block the current phase; when the actor was closing, in the CLOSE_REQUESTED state, this job would prevent it from moving on to the next state, so preventing it from actually closing.

That continuation job relied on a future provided by [TopicSubscriberGroup#doCloseSubscriber:109](https://github.com/zeebe-io/zeebe/blob/71f6b49569566005b84ebfa59db68328e5b171e4/client-java/src/main/java/io/zeebe/client/impl/subscription/topic/TopicSubscriberGroup.java#L109). That future was completed only after a CloseTopicSubscriptionCommand would complete, but was submitted as a normal continuation job, *on the same actor*.

So when the actor was requested to close, it would discard all next jobs, including the one which would complete said future, resulting in the subscription blocking the CLOSE_REQUESTED state to never complete, and so in ActorTask#onAllJobsDone the state would never change.

I'm not sure if I'm explaining this well enough, so maybe let's just go over it face to face. I might even be partially wrong about the details, since I haven't completely wrapped my head around the scheduler stuff yet.
