### ISSUE TITLE
Run client and broker test suite in parallel

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#943]
Currently we have a relative slow mvn build , which is kind of frustrating if we try to check if everything works before pushing to master.

Maybe we can improve on this by running broker and client test suite in parallel (maybe more)?  
Since the are independent from each other this could work. We need to ensure that the client test suite for example uses an different port than the broker test suite, but this should not be the problem right?

To run builds in parallel there are some parameters for maven:
https://stackoverflow.com/questions/581465/maven-how-to-do-parallel-builds

```java
mvn -T 4 clean install # Builds with 4 threads
mvn -T 1C clean install # 1 thread per cpu core
mvn -T 1.5C clean install # 1.5 thread per cpu core
```

Perhaps we should think about broker port self assignment  (ports which are free) Or configure the tests in other way? 

 
What do you guys think?

**Comment by npepinpe** [comment]
I think the port self assignment in general would be really useful for testing, if only so I can run multiple instances at the same time. Maybe even for local development (although that's not the end of the world, but still).

:+1:

**Comment by menski** [comment]
`mvn -T` isn't about executing tests in a single test suite in parallel, but execution maven module builds in parallel if they are not dependent on each other. But even this is currently not possible in our Zeebe build as for example gossip and raft use the same ports during the tests but are not dependent, so maven would execute them in parallel and one will fail as the port is already in use.

**Comment by Zelldon** [comment]
Yes, but this can also be changed right?

**Comment by menski** [comment]
Of course I just documented the current state :smile:

**Comment by menski** [comment]
I adjusted the test suite to allow us to build maven modules in parallel, see #1140.

> I think the port self assignment in general would be really useful for testing

This problem is not trivial to solve. A strategy where we first detect a free port and then start a broker with this port configured has an inherent race condition between detection and binding another test could also detect the port as free and tries to use it.

If we configure the broker to immediately bind to a free port, i.e. configure it to use port `0` for all sockets, it is not trivial to configure the remaining test environment correctly. For example the client has to know the port the broker choose, but this should be solvable. Which is more complex is the broker to broker communication, i.e. the initial contact point given in a cluster setup, which has to be known on startup.
